// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for UserRole.
const (
	Admin        UserRole = "admin"
	BrandManager UserRole = "brand_manager"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case BrandManager:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	// Code Machine-readable error code (e.g. CREATOR_NOT_FOUND)
	Code string `json:"code"`

	// Message Human-readable fallback message (English)
	Message string `json:"message"`
}

// AssignManagerRequest defines model for AssignManagerRequest.
type AssignManagerRequest struct {
	Email string `json:"email"`
}

// AssignManagerResult defines model for AssignManagerResult.
type AssignManagerResult struct {
	Data struct {
		Email        string  `json:"email"`
		Role         string  `json:"role"`
		TempPassword *string `json:"tempPassword,omitempty"`
		UserId       string  `json:"userId"`
	} `json:"data"`
}

// AuditLogEntry defines model for AuditLogEntry.
type AuditLogEntry struct {
	Action     string      `json:"action"`
	ActorId    string      `json:"actorId"`
	ActorRole  string      `json:"actorRole"`
	CreatedAt  time.Time   `json:"createdAt"`
	EntityId   *string     `json:"entityId,omitempty"`
	EntityType string      `json:"entityType"`
	Id         string      `json:"id"`
	IpAddress  string      `json:"ipAddress"`
	NewValue   interface{} `json:"newValue,omitempty"`
	OldValue   interface{} `json:"oldValue,omitempty"`
}

// AuditLogsResult defines model for AuditLogsResult.
type AuditLogsResult struct {
	Data struct {
		Logs    []AuditLogEntry `json:"logs"`
		Page    int             `json:"page"`
		PerPage int             `json:"perPage"`
		Total   int             `json:"total"`
	} `json:"data"`
}

// Brand defines model for Brand.
type Brand struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	LogoUrl   *string   `json:"logoUrl,omitempty"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// BrandListItem defines model for BrandListItem.
type BrandListItem struct {
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	LogoUrl      *string   `json:"logoUrl,omitempty"`
	ManagerCount int       `json:"managerCount"`
	Name         string    `json:"name"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// BrandResult defines model for BrandResult.
type BrandResult struct {
	Data Brand `json:"data"`
}

// CreateBrandRequest defines model for CreateBrandRequest.
type CreateBrandRequest struct {
	LogoUrl *string `json:"logoUrl,omitempty"`
	Name    string  `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// GetBrandResult defines model for GetBrandResult.
type GetBrandResult struct {
	Data struct {
		CreatedAt time.Time     `json:"createdAt"`
		Id        string        `json:"id"`
		LogoUrl   *string       `json:"logoUrl,omitempty"`
		Managers  []ManagerInfo `json:"managers"`
		Name      string        `json:"name"`
		UpdatedAt time.Time     `json:"updatedAt"`
	} `json:"data"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ListBrandsResult defines model for ListBrandsResult.
type ListBrandsResult struct {
	Data struct {
		Brands []BrandListItem `json:"brands"`
	} `json:"data"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Data struct {
		AccessToken string `json:"accessToken"`
		User        User   `json:"user"`
	} `json:"data"`
}

// ManagerInfo defines model for ManagerInfo.
type ManagerInfo struct {
	AssignedAt time.Time `json:"assignedAt"`
	Email      string    `json:"email"`
	UserId     string    `json:"userId"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Data struct {
		Message string `json:"message"`
	} `json:"data"`
}

// PasswordResetBody defines model for PasswordResetBody.
type PasswordResetBody struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// PasswordResetRequestBody defines model for PasswordResetRequestBody.
type PasswordResetRequestBody struct {
	Email openapi_types.Email `json:"email"`
}

// UpdateBrandRequest defines model for UpdateBrandRequest.
type UpdateBrandRequest struct {
	LogoUrl *string `json:"logoUrl,omitempty"`
	Name    string  `json:"name"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Role  UserRole            `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	ActorId    *string    `form:"actor_id,omitempty" json:"actor_id,omitempty"`
	EntityType *string    `form:"entity_type,omitempty" json:"entity_type,omitempty"`
	EntityId   *string    `form:"entity_id,omitempty" json:"entity_id,omitempty"`
	Action     *string    `form:"action,omitempty" json:"action,omitempty"`
	DateFrom   *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`
	DateTo     *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`
	Page       *int       `form:"page,omitempty" json:"page,omitempty"`
	PerPage    *int       `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = PasswordResetBody

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequestBody

// CreateBrandJSONRequestBody defines body for CreateBrand for application/json ContentType.
type CreateBrandJSONRequestBody = CreateBrandRequest

// UpdateBrandJSONRequestBody defines body for UpdateBrand for application/json ContentType.
type UpdateBrandJSONRequestBody = UpdateBrandRequest

// AssignManagerJSONRequestBody defines body for AssignManager for application/json ContentType.
type AssignManagerJSONRequestBody = AssignManagerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List audit logs (admin only)
	// (GET /audit-logs)
	ListAuditLogs(w http.ResponseWriter, r *http.Request, params ListAuditLogsParams)
	// Authenticate with email and password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout and invalidate refresh token
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Reset password with a valid token
	// (POST /auth/password-reset)
	ResetPassword(w http.ResponseWriter, r *http.Request)
	// Request a password reset token
	// (POST /auth/password-reset-request)
	RequestPasswordReset(w http.ResponseWriter, r *http.Request)
	// Refresh access token using refresh token cookie
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// List brands (admin sees all, manager sees own)
	// (GET /brands)
	ListBrands(w http.ResponseWriter, r *http.Request)
	// Create a new brand
	// (POST /brands)
	CreateBrand(w http.ResponseWriter, r *http.Request)
	// Delete brand
	// (DELETE /brands/{brandID})
	DeleteBrand(w http.ResponseWriter, r *http.Request, brandID string)
	// Get brand details with managers
	// (GET /brands/{brandID})
	GetBrand(w http.ResponseWriter, r *http.Request, brandID string)
	// Update brand
	// (PUT /brands/{brandID})
	UpdateBrand(w http.ResponseWriter, r *http.Request, brandID string)
	// Assign manager to brand
	// (POST /brands/{brandID}/managers)
	AssignManager(w http.ResponseWriter, r *http.Request, brandID string)
	// Remove manager from brand
	// (DELETE /brands/{brandID}/managers/{userID})
	RemoveManager(w http.ResponseWriter, r *http.Request, brandID string, userID string)
	// Health check
	// (GET /healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List audit logs (admin only)
// (GET /audit-logs)
func (_ Unimplemented) ListAuditLogs(w http.ResponseWriter, r *http.Request, params ListAuditLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate with email and password
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout and invalidate refresh token
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset password with a valid token
// (POST /auth/password-reset)
func (_ Unimplemented) ResetPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a password reset token
// (POST /auth/password-reset-request)
func (_ Unimplemented) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh access token using refresh token cookie
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List brands (admin sees all, manager sees own)
// (GET /brands)
func (_ Unimplemented) ListBrands(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new brand
// (POST /brands)
func (_ Unimplemented) CreateBrand(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete brand
// (DELETE /brands/{brandID})
func (_ Unimplemented) DeleteBrand(w http.ResponseWriter, r *http.Request, brandID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get brand details with managers
// (GET /brands/{brandID})
func (_ Unimplemented) GetBrand(w http.ResponseWriter, r *http.Request, brandID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update brand
// (PUT /brands/{brandID})
func (_ Unimplemented) UpdateBrand(w http.ResponseWriter, r *http.Request, brandID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign manager to brand
// (POST /brands/{brandID}/managers)
func (_ Unimplemented) AssignManager(w http.ResponseWriter, r *http.Request, brandID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove manager from brand
// (DELETE /brands/{brandID}/managers/{userID})
func (_ Unimplemented) RemoveManager(w http.ResponseWriter, r *http.Request, brandID string, userID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAuditLogs operation middleware
func (siw *ServerInterfaceWrapper) ListAuditLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditLogsParams

	// ------------- Optional query parameter "actor_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_id", r.URL.Query(), &params.ActorId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor_id", Err: err})
		return
	}

	// ------------- Optional query parameter "entity_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "entity_type", r.URL.Query(), &params.EntityType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_type", Err: err})
		return
	}

	// ------------- Optional query parameter "entity_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "entity_id", r.URL.Query(), &params.EntityId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_id", Err: err})
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", r.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	// ------------- Optional query parameter "date_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date_from", r.URL.Query(), &params.DateFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_from", Err: err})
		return
	}

	// ------------- Optional query parameter "date_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date_to", r.URL.Query(), &params.DateTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_to", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBrands operation middleware
func (siw *ServerInterfaceWrapper) ListBrands(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBrands(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBrand operation middleware
func (siw *ServerInterfaceWrapper) CreateBrand(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBrand(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBrand operation middleware
func (siw *ServerInterfaceWrapper) DeleteBrand(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "brandID" -------------
	var brandID string

	err = runtime.BindStyledParameterWithOptions("simple", "brandID", chi.URLParam(r, "brandID"), &brandID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "brandID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBrand(w, r, brandID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBrand operation middleware
func (siw *ServerInterfaceWrapper) GetBrand(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "brandID" -------------
	var brandID string

	err = runtime.BindStyledParameterWithOptions("simple", "brandID", chi.URLParam(r, "brandID"), &brandID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "brandID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBrand(w, r, brandID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBrand operation middleware
func (siw *ServerInterfaceWrapper) UpdateBrand(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "brandID" -------------
	var brandID string

	err = runtime.BindStyledParameterWithOptions("simple", "brandID", chi.URLParam(r, "brandID"), &brandID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "brandID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBrand(w, r, brandID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignManager operation middleware
func (siw *ServerInterfaceWrapper) AssignManager(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "brandID" -------------
	var brandID string

	err = runtime.BindStyledParameterWithOptions("simple", "brandID", chi.URLParam(r, "brandID"), &brandID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "brandID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignManager(w, r, brandID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveManager operation middleware
func (siw *ServerInterfaceWrapper) RemoveManager(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "brandID" -------------
	var brandID string

	err = runtime.BindStyledParameterWithOptions("simple", "brandID", chi.URLParam(r, "brandID"), &brandID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "brandID", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveManager(w, r, brandID, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/audit-logs", wrapper.ListAuditLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset", wrapper.ResetPassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset-request", wrapper.RequestPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/brands", wrapper.ListBrands)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/brands", wrapper.CreateBrand)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/brands/{brandID}", wrapper.DeleteBrand)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/brands/{brandID}", wrapper.GetBrand)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/brands/{brandID}", wrapper.UpdateBrand)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/brands/{brandID}/managers", wrapper.AssignManager)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/brands/{brandID}/managers/{userID}", wrapper.RemoveManager)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)
	})

	return r
}
