// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditRepoFactory creates a new instance of MockAuditRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditRepoFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditRepoFactory {
	mock := &MockAuditRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditRepoFactory is an autogenerated mock type for the AuditRepoFactory type
type MockAuditRepoFactory struct {
	mock.Mock
}

type MockAuditRepoFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditRepoFactory) EXPECT() *MockAuditRepoFactory_Expecter {
	return &MockAuditRepoFactory_Expecter{mock: &_m.Mock}
}

// NewAuditRepo provides a mock function for the type MockAuditRepoFactory
func (_mock *MockAuditRepoFactory) NewAuditRepo(db dbutil.DB) repository.AuditRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewAuditRepo")
	}

	var r0 repository.AuditRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.AuditRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AuditRepo)
		}
	}
	return r0
}

// MockAuditRepoFactory_NewAuditRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAuditRepo'
type MockAuditRepoFactory_NewAuditRepo_Call struct {
	*mock.Call
}

// NewAuditRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockAuditRepoFactory_Expecter) NewAuditRepo(db interface{}) *MockAuditRepoFactory_NewAuditRepo_Call {
	return &MockAuditRepoFactory_NewAuditRepo_Call{Call: _e.mock.On("NewAuditRepo", db)}
}

func (_c *MockAuditRepoFactory_NewAuditRepo_Call) Run(run func(db dbutil.DB)) *MockAuditRepoFactory_NewAuditRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditRepoFactory_NewAuditRepo_Call) Return(auditRepo repository.AuditRepo) *MockAuditRepoFactory_NewAuditRepo_Call {
	_c.Call.Return(auditRepo)
	return _c
}

func (_c *MockAuditRepoFactory_NewAuditRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.AuditRepo) *MockAuditRepoFactory_NewAuditRepo_Call {
	_c.Call.Return(run)
	return _c
}
