// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorRepoFactory creates a new instance of MockCreatorRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorRepoFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorRepoFactory {
	mock := &MockCreatorRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorRepoFactory is an autogenerated mock type for the CreatorRepoFactory type
type MockCreatorRepoFactory struct {
	mock.Mock
}

type MockCreatorRepoFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorRepoFactory) EXPECT() *MockCreatorRepoFactory_Expecter {
	return &MockCreatorRepoFactory_Expecter{mock: &_m.Mock}
}

// NewCreatorCategoryRepo provides a mock function for the type MockCreatorRepoFactory
func (_mock *MockCreatorRepoFactory) NewCreatorCategoryRepo(db dbutil.DB) repository.CreatorCategoryRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewCreatorCategoryRepo")
	}

	var r0 repository.CreatorCategoryRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.CreatorCategoryRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CreatorCategoryRepo)
		}
	}
	return r0
}

// MockCreatorRepoFactory_NewCreatorCategoryRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCreatorCategoryRepo'
type MockCreatorRepoFactory_NewCreatorCategoryRepo_Call struct {
	*mock.Call
}

// NewCreatorCategoryRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockCreatorRepoFactory_Expecter) NewCreatorCategoryRepo(db interface{}) *MockCreatorRepoFactory_NewCreatorCategoryRepo_Call {
	return &MockCreatorRepoFactory_NewCreatorCategoryRepo_Call{Call: _e.mock.On("NewCreatorCategoryRepo", db)}
}

func (_c *MockCreatorRepoFactory_NewCreatorCategoryRepo_Call) Run(run func(db dbutil.DB)) *MockCreatorRepoFactory_NewCreatorCategoryRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreatorRepoFactory_NewCreatorCategoryRepo_Call) Return(creatorCategoryRepo repository.CreatorCategoryRepo) *MockCreatorRepoFactory_NewCreatorCategoryRepo_Call {
	_c.Call.Return(creatorCategoryRepo)
	return _c
}

func (_c *MockCreatorRepoFactory_NewCreatorCategoryRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.CreatorCategoryRepo) *MockCreatorRepoFactory_NewCreatorCategoryRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreatorRepo provides a mock function for the type MockCreatorRepoFactory
func (_mock *MockCreatorRepoFactory) NewCreatorRepo(db dbutil.DB) repository.CreatorRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewCreatorRepo")
	}

	var r0 repository.CreatorRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.CreatorRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CreatorRepo)
		}
	}
	return r0
}

// MockCreatorRepoFactory_NewCreatorRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCreatorRepo'
type MockCreatorRepoFactory_NewCreatorRepo_Call struct {
	*mock.Call
}

// NewCreatorRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockCreatorRepoFactory_Expecter) NewCreatorRepo(db interface{}) *MockCreatorRepoFactory_NewCreatorRepo_Call {
	return &MockCreatorRepoFactory_NewCreatorRepo_Call{Call: _e.mock.On("NewCreatorRepo", db)}
}

func (_c *MockCreatorRepoFactory_NewCreatorRepo_Call) Run(run func(db dbutil.DB)) *MockCreatorRepoFactory_NewCreatorRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreatorRepoFactory_NewCreatorRepo_Call) Return(creatorRepo repository.CreatorRepo) *MockCreatorRepoFactory_NewCreatorRepo_Call {
	_c.Call.Return(creatorRepo)
	return _c
}

func (_c *MockCreatorRepoFactory_NewCreatorRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.CreatorRepo) *MockCreatorRepoFactory_NewCreatorRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreatorSocialRepo provides a mock function for the type MockCreatorRepoFactory
func (_mock *MockCreatorRepoFactory) NewCreatorSocialRepo(db dbutil.DB) repository.CreatorSocialRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewCreatorSocialRepo")
	}

	var r0 repository.CreatorSocialRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.CreatorSocialRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CreatorSocialRepo)
		}
	}
	return r0
}

// MockCreatorRepoFactory_NewCreatorSocialRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCreatorSocialRepo'
type MockCreatorRepoFactory_NewCreatorSocialRepo_Call struct {
	*mock.Call
}

// NewCreatorSocialRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockCreatorRepoFactory_Expecter) NewCreatorSocialRepo(db interface{}) *MockCreatorRepoFactory_NewCreatorSocialRepo_Call {
	return &MockCreatorRepoFactory_NewCreatorSocialRepo_Call{Call: _e.mock.On("NewCreatorSocialRepo", db)}
}

func (_c *MockCreatorRepoFactory_NewCreatorSocialRepo_Call) Run(run func(db dbutil.DB)) *MockCreatorRepoFactory_NewCreatorSocialRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreatorRepoFactory_NewCreatorSocialRepo_Call) Return(creatorSocialRepo repository.CreatorSocialRepo) *MockCreatorRepoFactory_NewCreatorSocialRepo_Call {
	_c.Call.Return(creatorSocialRepo)
	return _c
}

func (_c *MockCreatorRepoFactory_NewCreatorSocialRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.CreatorSocialRepo) *MockCreatorRepoFactory_NewCreatorSocialRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewDictionaryRepo provides a mock function for the type MockCreatorRepoFactory
func (_mock *MockCreatorRepoFactory) NewDictionaryRepo(db dbutil.DB) repository.DictionaryRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewDictionaryRepo")
	}

	var r0 repository.DictionaryRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.DictionaryRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.DictionaryRepo)
		}
	}
	return r0
}

// MockCreatorRepoFactory_NewDictionaryRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewDictionaryRepo'
type MockCreatorRepoFactory_NewDictionaryRepo_Call struct {
	*mock.Call
}

// NewDictionaryRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockCreatorRepoFactory_Expecter) NewDictionaryRepo(db interface{}) *MockCreatorRepoFactory_NewDictionaryRepo_Call {
	return &MockCreatorRepoFactory_NewDictionaryRepo_Call{Call: _e.mock.On("NewDictionaryRepo", db)}
}

func (_c *MockCreatorRepoFactory_NewDictionaryRepo_Call) Run(run func(db dbutil.DB)) *MockCreatorRepoFactory_NewDictionaryRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreatorRepoFactory_NewDictionaryRepo_Call) Return(dictionaryRepo repository.DictionaryRepo) *MockCreatorRepoFactory_NewDictionaryRepo_Call {
	_c.Call.Return(dictionaryRepo)
	return _c
}

func (_c *MockCreatorRepoFactory_NewDictionaryRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.DictionaryRepo) *MockCreatorRepoFactory_NewDictionaryRepo_Call {
	_c.Call.Return(run)
	return _c
}
