// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDictionaryRepoFactory creates a new instance of MockDictionaryRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDictionaryRepoFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDictionaryRepoFactory {
	mock := &MockDictionaryRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDictionaryRepoFactory is an autogenerated mock type for the DictionaryRepoFactory type
type MockDictionaryRepoFactory struct {
	mock.Mock
}

type MockDictionaryRepoFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDictionaryRepoFactory) EXPECT() *MockDictionaryRepoFactory_Expecter {
	return &MockDictionaryRepoFactory_Expecter{mock: &_m.Mock}
}

// NewDictionaryRepo provides a mock function for the type MockDictionaryRepoFactory
func (_mock *MockDictionaryRepoFactory) NewDictionaryRepo(db dbutil.DB) repository.DictionaryRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewDictionaryRepo")
	}

	var r0 repository.DictionaryRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.DictionaryRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.DictionaryRepo)
		}
	}
	return r0
}

// MockDictionaryRepoFactory_NewDictionaryRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewDictionaryRepo'
type MockDictionaryRepoFactory_NewDictionaryRepo_Call struct {
	*mock.Call
}

// NewDictionaryRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockDictionaryRepoFactory_Expecter) NewDictionaryRepo(db interface{}) *MockDictionaryRepoFactory_NewDictionaryRepo_Call {
	return &MockDictionaryRepoFactory_NewDictionaryRepo_Call{Call: _e.mock.On("NewDictionaryRepo", db)}
}

func (_c *MockDictionaryRepoFactory_NewDictionaryRepo_Call) Run(run func(db dbutil.DB)) *MockDictionaryRepoFactory_NewDictionaryRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDictionaryRepoFactory_NewDictionaryRepo_Call) Return(dictionaryRepo repository.DictionaryRepo) *MockDictionaryRepoFactory_NewDictionaryRepo_Call {
	_c.Call.Return(dictionaryRepo)
	return _c
}

func (_c *MockDictionaryRepoFactory_NewDictionaryRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.DictionaryRepo) *MockDictionaryRepoFactory_NewDictionaryRepo_Call {
	_c.Call.Return(run)
	return _c
}
