// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/telegram"
	mock "github.com/stretchr/testify/mock"
)

// NewMockcreatorAppTelegramNotifier creates a new instance of MockcreatorAppTelegramNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcreatorAppTelegramNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcreatorAppTelegramNotifier {
	mock := &MockcreatorAppTelegramNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockcreatorAppTelegramNotifier is an autogenerated mock type for the creatorAppTelegramNotifier type
type MockcreatorAppTelegramNotifier struct {
	mock.Mock
}

type MockcreatorAppTelegramNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcreatorAppTelegramNotifier) EXPECT() *MockcreatorAppTelegramNotifier_Expecter {
	return &MockcreatorAppTelegramNotifier_Expecter{mock: &_m.Mock}
}

// NotifyApplicationLinked provides a mock function for the type MockcreatorAppTelegramNotifier
func (_mock *MockcreatorAppTelegramNotifier) NotifyApplicationLinked(ctx context.Context, chatID int64, p telegram.ApplicationLinkedPayload) {
	_mock.Called(ctx, chatID, p)
	return
}

// MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyApplicationLinked'
type MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call struct {
	*mock.Call
}

// NotifyApplicationLinked is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - p telegram.ApplicationLinkedPayload
func (_e *MockcreatorAppTelegramNotifier_Expecter) NotifyApplicationLinked(ctx interface{}, chatID interface{}, p interface{}) *MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call {
	return &MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call{Call: _e.mock.On("NotifyApplicationLinked", ctx, chatID, p)}
}

func (_c *MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call) Run(run func(ctx context.Context, chatID int64, p telegram.ApplicationLinkedPayload)) *MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 telegram.ApplicationLinkedPayload
		if args[2] != nil {
			arg2 = args[2].(telegram.ApplicationLinkedPayload)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call) Return() *MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call) RunAndReturn(run func(ctx context.Context, chatID int64, p telegram.ApplicationLinkedPayload)) *MockcreatorAppTelegramNotifier_NotifyApplicationLinked_Call {
	_c.Run(run)
	return _c
}
