// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorApplicationTelegramRepoFactory creates a new instance of MockCreatorApplicationTelegramRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorApplicationTelegramRepoFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorApplicationTelegramRepoFactory {
	mock := &MockCreatorApplicationTelegramRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorApplicationTelegramRepoFactory is an autogenerated mock type for the CreatorApplicationTelegramRepoFactory type
type MockCreatorApplicationTelegramRepoFactory struct {
	mock.Mock
}

type MockCreatorApplicationTelegramRepoFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorApplicationTelegramRepoFactory) EXPECT() *MockCreatorApplicationTelegramRepoFactory_Expecter {
	return &MockCreatorApplicationTelegramRepoFactory_Expecter{mock: &_m.Mock}
}

// NewAuditRepo provides a mock function for the type MockCreatorApplicationTelegramRepoFactory
func (_mock *MockCreatorApplicationTelegramRepoFactory) NewAuditRepo(db dbutil.DB) repository.AuditRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewAuditRepo")
	}

	var r0 repository.AuditRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.AuditRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AuditRepo)
		}
	}
	return r0
}

// MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAuditRepo'
type MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call struct {
	*mock.Call
}

// NewAuditRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockCreatorApplicationTelegramRepoFactory_Expecter) NewAuditRepo(db interface{}) *MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call {
	return &MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call{Call: _e.mock.On("NewAuditRepo", db)}
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call) Run(run func(db dbutil.DB)) *MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call) Return(auditRepo repository.AuditRepo) *MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call {
	_c.Call.Return(auditRepo)
	return _c
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.AuditRepo) *MockCreatorApplicationTelegramRepoFactory_NewAuditRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreatorApplicationRepo provides a mock function for the type MockCreatorApplicationTelegramRepoFactory
func (_mock *MockCreatorApplicationTelegramRepoFactory) NewCreatorApplicationRepo(db dbutil.DB) repository.CreatorApplicationRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewCreatorApplicationRepo")
	}

	var r0 repository.CreatorApplicationRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.CreatorApplicationRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CreatorApplicationRepo)
		}
	}
	return r0
}

// MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCreatorApplicationRepo'
type MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call struct {
	*mock.Call
}

// NewCreatorApplicationRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockCreatorApplicationTelegramRepoFactory_Expecter) NewCreatorApplicationRepo(db interface{}) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call {
	return &MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call{Call: _e.mock.On("NewCreatorApplicationRepo", db)}
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call) Run(run func(db dbutil.DB)) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call) Return(creatorApplicationRepo repository.CreatorApplicationRepo) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call {
	_c.Call.Return(creatorApplicationRepo)
	return _c
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.CreatorApplicationRepo) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreatorApplicationTelegramLinkRepo provides a mock function for the type MockCreatorApplicationTelegramRepoFactory
func (_mock *MockCreatorApplicationTelegramRepoFactory) NewCreatorApplicationTelegramLinkRepo(db dbutil.DB) repository.CreatorApplicationTelegramLinkRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewCreatorApplicationTelegramLinkRepo")
	}

	var r0 repository.CreatorApplicationTelegramLinkRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.CreatorApplicationTelegramLinkRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CreatorApplicationTelegramLinkRepo)
		}
	}
	return r0
}

// MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCreatorApplicationTelegramLinkRepo'
type MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call struct {
	*mock.Call
}

// NewCreatorApplicationTelegramLinkRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockCreatorApplicationTelegramRepoFactory_Expecter) NewCreatorApplicationTelegramLinkRepo(db interface{}) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call {
	return &MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call{Call: _e.mock.On("NewCreatorApplicationTelegramLinkRepo", db)}
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call) Run(run func(db dbutil.DB)) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call) Return(creatorApplicationTelegramLinkRepo repository.CreatorApplicationTelegramLinkRepo) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call {
	_c.Call.Return(creatorApplicationTelegramLinkRepo)
	return _c
}

func (_c *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.CreatorApplicationTelegramLinkRepo) *MockCreatorApplicationTelegramRepoFactory_NewCreatorApplicationTelegramLinkRepo_Call {
	_c.Call.Return(run)
	return _c
}
