// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-telegram/bot"
	"github.com/go-telegram/bot/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockSender
func (_mock *MockSender) SendMessage(ctx context.Context, params *bot.SendMessageParams) (*models.Message, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *models.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bot.SendMessageParams) (*models.Message, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bot.SendMessageParams) *models.Message); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bot.SendMessageParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *bot.SendMessageParams
func (_e *MockSender_Expecter) SendMessage(ctx interface{}, params interface{}) *MockSender_SendMessage_Call {
	return &MockSender_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, params)}
}

func (_c *MockSender_SendMessage_Call) Run(run func(ctx context.Context, params *bot.SendMessageParams)) *MockSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bot.SendMessageParams
		if args[1] != nil {
			arg1 = args[1].(*bot.SendMessageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSender_SendMessage_Call) Return(message *models.Message, err error) *MockSender_SendMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockSender_SendMessage_Call) RunAndReturn(run func(ctx context.Context, params *bot.SendMessageParams) (*models.Message, error)) *MockSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
