FROM golang:1.25-alpine AS builder
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.20
COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY migrations/ /migrations/

ENTRYPOINT ["goose", "-dir", "/migrations", "postgres", "postgres://ugcboost:ugcboost_test@postgres:5432/ugcboost_test?sslmode=disable", "up"]
