FROM golang:1.25-alpine AS builder
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.20
COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY migrations/ /migrations/

ENTRYPOINT ["sh", "-c", "goose -dir /migrations postgres \"$DATABASE_URL\" up"]
