dir: "{{.InterfaceDir}}/mocks"
structname: "Mock{{.InterfaceName}}"
pkgname: mocks
filename: "mock_{{.InterfaceName | snakecase}}.go"
template: testify
all: true
packages:
  github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil:
  github.com/alikhanmurzayev/ugcboost/backend/internal/repository:
  github.com/alikhanmurzayev/ugcboost/backend/internal/service:
  github.com/alikhanmurzayev/ugcboost/backend/internal/handler:
  github.com/alikhanmurzayev/ugcboost/backend/internal/middleware:
  github.com/alikhanmurzayev/ugcboost/backend/internal/authz:
  github.com/alikhanmurzayev/ugcboost/backend/internal/logger:
