dir: "{{.InterfaceDir}}/mocks"
structname: "Mock{{.InterfaceName}}"
pkgname: mocks
filename: "mock_{{.InterfaceName | snakecase}}.go"
template: testify
packages:
  github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil:
    interfaces:
      DB: {}
  github.com/alikhanmurzayev/ugcboost/backend/internal/handler:
    interfaces:
      AuthService: {}
      BrandService: {}
      AuditLogService: {}
  github.com/alikhanmurzayev/ugcboost/backend/internal/service:
    interfaces:
      UserRepo: {}
      TokenGenerator: {}
      BrandRepo: {}
      BrandUserRepo: {}
  github.com/alikhanmurzayev/ugcboost/backend/internal/middleware:
    interfaces:
      TokenValidator: {}
