// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for UserRole.
const (
	Admin        UserRole = "admin"
	BrandManager UserRole = "brand_manager"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case BrandManager:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	// Code Machine-readable error code (e.g. CREATOR_NOT_FOUND)
	Code string `json:"code"`

	// Message Human-readable fallback message (English)
	Message string `json:"message"`
}

// AssignManagerRequest defines model for AssignManagerRequest.
type AssignManagerRequest struct {
	Email string `json:"email"`
}

// AssignManagerResult defines model for AssignManagerResult.
type AssignManagerResult struct {
	Data struct {
		Email        string  `json:"email"`
		Role         string  `json:"role"`
		TempPassword *string `json:"tempPassword,omitempty"`
		UserId       string  `json:"userId"`
	} `json:"data"`
}

// AuditLogEntry defines model for AuditLogEntry.
type AuditLogEntry struct {
	Action     string      `json:"action"`
	ActorId    string      `json:"actorId"`
	ActorRole  string      `json:"actorRole"`
	CreatedAt  time.Time   `json:"createdAt"`
	EntityId   *string     `json:"entityId,omitempty"`
	EntityType string      `json:"entityType"`
	Id         string      `json:"id"`
	IpAddress  string      `json:"ipAddress"`
	NewValue   interface{} `json:"newValue,omitempty"`
	OldValue   interface{} `json:"oldValue,omitempty"`
}

// AuditLogsResult defines model for AuditLogsResult.
type AuditLogsResult struct {
	Data struct {
		Logs    []AuditLogEntry `json:"logs"`
		Page    int             `json:"page"`
		PerPage int             `json:"perPage"`
		Total   int             `json:"total"`
	} `json:"data"`
}

// Brand defines model for Brand.
type Brand struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	LogoUrl   *string   `json:"logoUrl,omitempty"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// BrandListItem defines model for BrandListItem.
type BrandListItem struct {
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	LogoUrl      *string   `json:"logoUrl,omitempty"`
	ManagerCount int       `json:"managerCount"`
	Name         string    `json:"name"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// BrandResult defines model for BrandResult.
type BrandResult struct {
	Data Brand `json:"data"`
}

// CreateBrandRequest defines model for CreateBrandRequest.
type CreateBrandRequest struct {
	LogoUrl *string `json:"logoUrl,omitempty"`
	Name    string  `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// GetBrandResult defines model for GetBrandResult.
type GetBrandResult struct {
	Data struct {
		CreatedAt time.Time     `json:"createdAt"`
		Id        string        `json:"id"`
		LogoUrl   *string       `json:"logoUrl,omitempty"`
		Managers  []ManagerInfo `json:"managers"`
		Name      string        `json:"name"`
		UpdatedAt time.Time     `json:"updatedAt"`
	} `json:"data"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ListBrandsResult defines model for ListBrandsResult.
type ListBrandsResult struct {
	Data struct {
		Brands []BrandListItem `json:"brands"`
	} `json:"data"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Data struct {
		AccessToken string `json:"accessToken"`
		User        User   `json:"user"`
	} `json:"data"`
}

// ManagerInfo defines model for ManagerInfo.
type ManagerInfo struct {
	AssignedAt time.Time `json:"assignedAt"`
	Email      string    `json:"email"`
	UserId     string    `json:"userId"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Data struct {
		Message string `json:"message"`
	} `json:"data"`
}

// PasswordResetBody defines model for PasswordResetBody.
type PasswordResetBody struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// PasswordResetRequestBody defines model for PasswordResetRequestBody.
type PasswordResetRequestBody struct {
	Email openapi_types.Email `json:"email"`
}

// UpdateBrandRequest defines model for UpdateBrandRequest.
type UpdateBrandRequest struct {
	LogoUrl *string `json:"logoUrl,omitempty"`
	Name    string  `json:"name"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Role  UserRole            `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	ActorId    *string    `form:"actor_id,omitempty" json:"actor_id,omitempty"`
	EntityType *string    `form:"entity_type,omitempty" json:"entity_type,omitempty"`
	EntityId   *string    `form:"entity_id,omitempty" json:"entity_id,omitempty"`
	Action     *string    `form:"action,omitempty" json:"action,omitempty"`
	DateFrom   *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`
	DateTo     *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`
	Page       *int       `form:"page,omitempty" json:"page,omitempty"`
	PerPage    *int       `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = PasswordResetBody

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequestBody

// CreateBrandJSONRequestBody defines body for CreateBrand for application/json ContentType.
type CreateBrandJSONRequestBody = CreateBrandRequest

// UpdateBrandJSONRequestBody defines body for UpdateBrand for application/json ContentType.
type UpdateBrandJSONRequestBody = UpdateBrandRequest

// AssignManagerJSONRequestBody defines body for AssignManager for application/json ContentType.
type AssignManagerJSONRequestBody = AssignManagerRequest
