// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ConsentType.
const (
	CrossBorder ConsentType = "cross_border"
	Processing  ConsentType = "processing"
	Terms       ConsentType = "terms"
	ThirdParty  ConsentType = "third_party"
)

// Valid indicates whether the value is a known member of the ConsentType enum.
func (e ConsentType) Valid() bool {
	switch e {
	case CrossBorder:
		return true
	case Processing:
		return true
	case Terms:
		return true
	case ThirdParty:
		return true
	default:
		return false
	}
}

// Defines values for CreatorApplicationListSortField.
const (
	BirthDate CreatorApplicationListSortField = "birth_date"
	CityName  CreatorApplicationListSortField = "city_name"
	CreatedAt CreatorApplicationListSortField = "created_at"
	FullName  CreatorApplicationListSortField = "full_name"
	UpdatedAt CreatorApplicationListSortField = "updated_at"
)

// Valid indicates whether the value is a known member of the CreatorApplicationListSortField enum.
func (e CreatorApplicationListSortField) Valid() bool {
	switch e {
	case BirthDate:
		return true
	case CityName:
		return true
	case CreatedAt:
		return true
	case FullName:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for CreatorApplicationStatus.
const (
	Approved     CreatorApplicationStatus = "approved"
	Moderation   CreatorApplicationStatus = "moderation"
	Rejected     CreatorApplicationStatus = "rejected"
	Verification CreatorApplicationStatus = "verification"
	Withdrawn    CreatorApplicationStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the CreatorApplicationStatus enum.
func (e CreatorApplicationStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Moderation:
		return true
	case Rejected:
		return true
	case Verification:
		return true
	case Withdrawn:
		return true
	default:
		return false
	}
}

// Defines values for SocialPlatform.
const (
	Instagram SocialPlatform = "instagram"
	Threads   SocialPlatform = "threads"
	Tiktok    SocialPlatform = "tiktok"
)

// Valid indicates whether the value is a known member of the SocialPlatform enum.
func (e SocialPlatform) Valid() bool {
	switch e {
	case Instagram:
		return true
	case Threads:
		return true
	case Tiktok:
		return true
	default:
		return false
	}
}

// Defines values for SocialVerificationMethod.
const (
	Auto   SocialVerificationMethod = "auto"
	Manual SocialVerificationMethod = "manual"
)

// Valid indicates whether the value is a known member of the SocialVerificationMethod enum.
func (e SocialVerificationMethod) Valid() bool {
	switch e {
	case Auto:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for SortOrder.
const (
	Asc  SortOrder = "asc"
	Desc SortOrder = "desc"
)

// Valid indicates whether the value is a known member of the SortOrder enum.
func (e SortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin        UserRole = "admin"
	BrandManager UserRole = "brand_manager"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case BrandManager:
		return true
	default:
		return false
	}
}

// Defines values for ListDictionaryParamsType.
const (
	Categories ListDictionaryParamsType = "categories"
	Cities     ListDictionaryParamsType = "cities"
)

// Valid indicates whether the value is a known member of the ListDictionaryParamsType enum.
func (e ListDictionaryParamsType) Valid() bool {
	switch e {
	case Categories:
		return true
	case Cities:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	// Code Machine-readable error code (e.g. CREATOR_NOT_FOUND)
	Code string `json:"code"`

	// Message Human-readable fallback message (English)
	Message string `json:"message"`
}

// AssignManagerData defines model for AssignManagerData.
type AssignManagerData struct {
	Email        string  `json:"email"`
	Role         string  `json:"role"`
	TempPassword *string `json:"tempPassword,omitempty"`
	UserId       string  `json:"userId"`
}

// AssignManagerRequest defines model for AssignManagerRequest.
type AssignManagerRequest struct {
	Email string `json:"email"`
}

// AssignManagerResult defines model for AssignManagerResult.
type AssignManagerResult struct {
	Data AssignManagerData `json:"data"`
}

// AuditLogEntry defines model for AuditLogEntry.
type AuditLogEntry struct {
	Action string `json:"action"`

	// ActorId Null for system / public actions (e.g. public creator application submit).
	ActorId    *string     `json:"actorId,omitempty"`
	ActorRole  string      `json:"actorRole"`
	CreatedAt  time.Time   `json:"createdAt"`
	EntityId   *string     `json:"entityId,omitempty"`
	EntityType string      `json:"entityType"`
	Id         string      `json:"id"`
	IpAddress  string      `json:"ipAddress"`
	NewValue   interface{} `json:"newValue,omitempty"`
	OldValue   interface{} `json:"oldValue,omitempty"`
}

// AuditLogsResult defines model for AuditLogsResult.
type AuditLogsResult struct {
	Data ListAuditLogsData `json:"data"`
}

// Brand defines model for Brand.
type Brand struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	LogoUrl   *string   `json:"logoUrl,omitempty"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// BrandDetailData defines model for BrandDetailData.
type BrandDetailData struct {
	CreatedAt time.Time     `json:"createdAt"`
	Id        string        `json:"id"`
	LogoUrl   *string       `json:"logoUrl,omitempty"`
	Managers  []ManagerInfo `json:"managers"`
	Name      string        `json:"name"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

// BrandInput Mutable subset of a brand — used for create and update.
type BrandInput struct {
	LogoUrl *string `json:"logoUrl,omitempty"`
	Name    string  `json:"name"`
}

// BrandListItem defines model for BrandListItem.
type BrandListItem struct {
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	LogoUrl      *string   `json:"logoUrl,omitempty"`
	ManagerCount int       `json:"managerCount"`
	Name         string    `json:"name"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// BrandResult defines model for BrandResult.
type BrandResult struct {
	Data Brand `json:"data"`
}

// ConsentType Canonical consent type captured at creator application submission.
type ConsentType string

// CreatorAggregate Full creator profile assembled from `creators` plus the snapshot tables
// `creator_socials` and `creator_categories`. The Telegram block is
// flattened (no separate object) because the only path to materialise a
// creator is via approve, which guarantees a Telegram link existed at
// that moment. City and category codes are returned alongside their
// localised names hydrated from the active public dictionaries; missing
// dictionary entries degrade to a `name == code` fallback.
type CreatorAggregate struct {
	Address   *string            `json:"address,omitempty"`
	BirthDate openapi_types.Date `json:"birthDate"`

	// Categories Categories sorted by code.
	Categories []CreatorAggregateCategory `json:"categories"`

	// CategoryOtherText Free-text niche description; non-null only when categories include "other".
	CategoryOtherText *string `json:"categoryOtherText,omitempty"`

	// CityCode Stable city code copied from the originating application.
	CityCode string `json:"cityCode"`

	// CityName Localised city label hydrated from the active cities dictionary; falls back to `cityCode` when the entry has been deactivated.
	CityName  string             `json:"cityName"`
	CreatedAt time.Time          `json:"createdAt"`
	FirstName string             `json:"firstName"`
	Id        openapi_types.UUID `json:"id"`

	// Iin Kazakhstani individual identification number (12 digits).
	Iin        string  `json:"iin"`
	LastName   string  `json:"lastName"`
	MiddleName *string `json:"middleName,omitempty"`
	Phone      string  `json:"phone"`

	// Socials Social accounts sorted by (platform, handle).
	Socials []CreatorAggregateSocial `json:"socials"`

	// SourceApplicationId ID of the originating creator application; allows admin and analytics joins.
	SourceApplicationId openapi_types.UUID `json:"sourceApplicationId"`
	TelegramFirstName   *string            `json:"telegramFirstName,omitempty"`
	TelegramLastName    *string            `json:"telegramLastName,omitempty"`

	// TelegramUserId Telegram numeric user id (BIGINT) — stable identifier of the linked account.
	TelegramUserId   int64     `json:"telegramUserId"`
	TelegramUsername *string   `json:"telegramUsername,omitempty"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

// CreatorAggregateCategory One category linked to a creator. `code` is the stable machine
// identifier copied from the application; `name` is hydrated from the
// active categories dictionary at read time, with a fallback to `code`
// when the dictionary entry has been deactivated.
type CreatorAggregateCategory struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// CreatorAggregateSocial Snapshot of one social account attached to a creator at the moment of
// approve. The verification fields are copied from the application's
// social row 1:1 — they reflect the verification state at approval time
// even if the dictionary or the originating application later changes.
type CreatorAggregateSocial struct {
	// CreatedAt When the snapshot row was inserted into creator_socials.
	CreatedAt time.Time          `json:"createdAt"`
	Handle    string             `json:"handle"`
	Id        openapi_types.UUID `json:"id"`

	// Method How a social account was verified. `auto` — webhook from SendPulse caught
	// the verification code in an Instagram DM. `manual` — admin marked the
	// social as verified from the application drawer.
	Method *SocialVerificationMethod `json:"method,omitempty"`

	// Platform Supported social network for creator accounts (MVP scope).
	Platform SocialPlatform `json:"platform"`

	// Verified Whether ownership of this social account was confirmed at approval time.
	Verified bool `json:"verified"`

	// VerifiedAt When verification succeeded; null when the row stays unverified.
	VerifiedAt *time.Time `json:"verifiedAt,omitempty"`

	// VerifiedByUserId Admin who pressed manual-verify; null on auto-verified and unverified rows.
	VerifiedByUserId *openapi_types.UUID `json:"verifiedByUserId,omitempty"`
}

// CreatorApplicationDetailConsent defines model for CreatorApplicationDetailConsent.
type CreatorApplicationDetailConsent struct {
	AcceptedAt time.Time `json:"acceptedAt"`

	// ConsentType Canonical consent type captured at creator application submission.
	ConsentType ConsentType `json:"consentType"`

	// DocumentVersion Document version stamp recorded at the moment of consent.
	DocumentVersion string `json:"documentVersion"`

	// IpAddress Client IP recorded at submission (raw stored as-is).
	IpAddress string `json:"ipAddress"`

	// UserAgent Truncated User-Agent recorded at submission.
	UserAgent string `json:"userAgent"`
}

// CreatorApplicationDetailData defines model for CreatorApplicationDetailData.
type CreatorApplicationDetailData struct {
	Address *string `json:"address,omitempty"`

	// BirthDate Birth date derived from the IIN at submission time.
	BirthDate openapi_types.Date `json:"birthDate"`

	// Categories Categories selected by the creator, sorted by sort_order then code.
	Categories []DictionaryItem `json:"categories"`

	// CategoryOtherText Free-text niche description when categories include "other".
	CategoryOtherText *string `json:"categoryOtherText,omitempty"`

	// City Single entry from a public dictionary (categories, cities, etc.).
	// Reused for the dictionary-listing endpoint and for hydrated dictionary
	// references on creator-application reads, where the backend falls back
	// to `(code, code, 0)` when the underlying dictionary row has been
	// deactivated.
	City DictionaryItem `json:"city"`

	// Consents Consents in canonical order (processing → third_party → cross_border → terms),
	// independent of the order they appear in the database.
	Consents  []CreatorApplicationDetailConsent `json:"consents"`
	CreatedAt time.Time                         `json:"createdAt"`
	FirstName string                            `json:"firstName"`
	Id        openapi_types.UUID                `json:"id"`

	// Iin Kazakhstani individual identification number (12 digits).
	Iin        string  `json:"iin"`
	LastName   string  `json:"lastName"`
	MiddleName *string `json:"middleName,omitempty"`
	Phone      string  `json:"phone"`

	// Rejection Present only when `status` is `rejected`. Mirrors the
	// `verifiedByUserId` / `verifiedAt` shape used on socials: it carries
	// who took the action, when, and which status it transitioned from.
	// The rejected application's other fields (telegramLink, socials,
	// consents) stay populated so downstream flows (chunk 14 notifier,
	// future broadcasts) can still reach the creator.
	Rejection *CreatorApplicationRejection `json:"rejection,omitempty"`

	// Socials Social accounts attached to the application, sorted by platform then handle.
	Socials []CreatorApplicationDetailSocial `json:"socials"`

	// Status Lifecycle status of a creator application. Values follow the state
	// machine described in `_bmad-output/planning-artifacts/creator-application-state-machine.md`.
	Status CreatorApplicationStatus `json:"status"`

	// TelegramBotUrl Deep-link in form `https://t.me/{bot}?start={applicationId}`. The
	// admin shares it with the creator (e.g. via WhatsApp) when
	// `telegramLink` is null. Always returned regardless of link state so
	// the response shape stays stable; the frontend renders the copy
	// action only when not yet bound.
	TelegramBotUrl string `json:"telegramBotUrl"`

	// TelegramLink Telegram account linked to this application. Null when the creator
	// has not yet opened the bot.
	TelegramLink *TelegramLink `json:"telegramLink,omitempty"`
	UpdatedAt    time.Time     `json:"updatedAt"`

	// VerificationCode 6-digit `UGC-NNNNNN` code the creator must DM to the official
	// Instagram for auto-verification. Visible only via this admin
	// endpoint — never returned by public/landing routes.
	VerificationCode string `json:"verificationCode"`
}

// CreatorApplicationDetailSocial defines model for CreatorApplicationDetailSocial.
type CreatorApplicationDetailSocial struct {
	Handle string `json:"handle"`

	// Id Stable identifier for the social row. Required by the admin
	// manual-verify action (POST /creators/applications/{id}/socials/{socialId}/verify).
	Id openapi_types.UUID `json:"id"`

	// Method How a social account was verified. `auto` — webhook from SendPulse caught
	// the verification code in an Instagram DM. `manual` — admin marked the
	// social as verified from the application drawer.
	Method *SocialVerificationMethod `json:"method,omitempty"`

	// Platform Supported social network for creator accounts (MVP scope).
	Platform SocialPlatform `json:"platform"`

	// Verified Whether the creator's ownership of this social account has been confirmed.
	Verified bool `json:"verified"`

	// VerifiedAt When verification succeeded; null while the account is unverified.
	VerifiedAt *time.Time `json:"verifiedAt,omitempty"`

	// VerifiedByUserId Admin who pressed the manual-verify button. Null on auto and on unverified rows.
	VerifiedByUserId *openapi_types.UUID `json:"verifiedByUserId,omitempty"`
}

// CreatorApplicationListItem defines model for CreatorApplicationListItem.
type CreatorApplicationListItem struct {
	BirthDate openapi_types.Date `json:"birthDate"`

	// Categories Categories selected by the creator, sorted by sort_order then code.
	Categories []DictionaryItem `json:"categories"`

	// City Single entry from a public dictionary (categories, cities, etc.).
	// Reused for the dictionary-listing endpoint and for hydrated dictionary
	// references on creator-application reads, where the backend falls back
	// to `(code, code, 0)` when the underlying dictionary row has been
	// deactivated.
	City       DictionaryItem     `json:"city"`
	CreatedAt  time.Time          `json:"createdAt"`
	FirstName  string             `json:"firstName"`
	Id         openapi_types.UUID `json:"id"`
	LastName   string             `json:"lastName"`
	MiddleName *string            `json:"middleName,omitempty"`

	// Socials Social accounts attached to the application, sorted by platform then handle.
	Socials []CreatorApplicationDetailSocial `json:"socials"`

	// Status Lifecycle status of a creator application. Values follow the state
	// machine described in `_bmad-output/planning-artifacts/creator-application-state-machine.md`.
	Status CreatorApplicationStatus `json:"status"`

	// TelegramLinked True when the creator has bound a Telegram account via /start.
	TelegramLinked bool      `json:"telegramLinked"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// CreatorApplicationListSortField Sort field for the admin list. Mapped to a SQL column / expression on
// the backend. Unknown values are rejected with 422.
type CreatorApplicationListSortField string

// CreatorApplicationRejection Reject metadata derived from the latest
// `creator_application_status_transitions` row with `to_status=rejected`.
type CreatorApplicationRejection struct {
	// FromStatus Lifecycle status of a creator application. Values follow the state
	// machine described in `_bmad-output/planning-artifacts/creator-application-state-machine.md`.
	FromStatus       CreatorApplicationStatus `json:"fromStatus"`
	RejectedAt       time.Time                `json:"rejectedAt"`
	RejectedByUserId openapi_types.UUID       `json:"rejectedByUserId"`
}

// CreatorApplicationStatus Lifecycle status of a creator application. Values follow the state
// machine described in `_bmad-output/planning-artifacts/creator-application-state-machine.md`.
type CreatorApplicationStatus string

// CreatorApplicationStatusCount Single (status, count) pair returned by GET /creators/applications/counts.
type CreatorApplicationStatusCount struct {
	// Count Number of creator applications currently in this status.
	Count int64 `json:"count"`

	// Status Lifecycle status of a creator application. Values follow the state
	// machine described in `_bmad-output/planning-artifacts/creator-application-state-machine.md`.
	Status CreatorApplicationStatus `json:"status"`
}

// CreatorApplicationSubmitData defines model for CreatorApplicationSubmitData.
type CreatorApplicationSubmitData struct {
	// ApplicationId UUID of the newly created application (also embedded into the bot deep-link).
	ApplicationId openapi_types.UUID `json:"applicationId"`

	// TelegramBotUrl Deep-link to the Telegram bot carrying application id as start parameter.
	TelegramBotUrl string `json:"telegramBotUrl"`
}

// CreatorApplicationSubmitRequest defines model for CreatorApplicationSubmitRequest.
type CreatorApplicationSubmitRequest struct {
	// AcceptedAll Single consent flag covering all four canonical consent types
	// (processing / third_party / cross_border / terms). The legal model
	// (privacy-policy.md §9.2) treats acceptance of the Privacy Policy as
	// unconditional consent to all four. Backend writes four rows in
	// creator_application_consents bound to the current document versions.
	// Must be true; otherwise the request is rejected with 422 MISSING_CONSENT.
	AcceptedAll bool `json:"acceptedAll"`

	// Address Optional legal/postal address. Empty on the landing form (the bot
	// collects it later); admins may patch it via moderation tooling.
	Address *string `json:"address,omitempty"`

	// Categories One or more category codes from the categories catalogue. Must be non-empty.
	// Maximum three codes; submissions with more are rejected with 422.
	Categories []string `json:"categories"`

	// CategoryOtherText Free-text description of the creator's niche when "other" appears in
	// categories. Required when "other" is present (otherwise the request is
	// rejected with 422 VALIDATION_ERROR). Ignored when "other" is absent.
	CategoryOtherText *string `json:"categoryOtherText,omitempty"`
	City              string  `json:"city"`
	FirstName         string  `json:"firstName"`

	// Iin Kazakhstani individual identification number (12 digits).
	Iin      string `json:"iin"`
	LastName string `json:"lastName"`

	// MiddleName Optional patronymic (not every applicant has one).
	MiddleName *string `json:"middleName,omitempty"`
	Phone      string  `json:"phone"`

	// Socials One or more social accounts. Multiple handles on the same platform are allowed.
	Socials []SocialAccountInput `json:"socials"`
}

// CreatorApplicationSubmitResult defines model for CreatorApplicationSubmitResult.
type CreatorApplicationSubmitResult struct {
	Data CreatorApplicationSubmitData `json:"data"`
}

// CreatorApplicationsCountsData Sparse counts payload — see the operation description on the
// `getCreatorApplicationsCounts` endpoint for the contract details.
// `items` is alphabetically sorted by `status` for deterministic output.
type CreatorApplicationsCountsData struct {
	// Items Sparse list — only statuses with at least one application appear here.
	Items []CreatorApplicationStatusCount `json:"items"`
}

// CreatorApplicationsCountsResult defines model for CreatorApplicationsCountsResult.
type CreatorApplicationsCountsResult struct {
	// Data Sparse counts payload — see the operation description on the
	// `getCreatorApplicationsCounts` endpoint for the contract details.
	// `items` is alphabetically sorted by `status` for deterministic output.
	Data CreatorApplicationsCountsData `json:"data"`
}

// CreatorApplicationsListData defines model for CreatorApplicationsListData.
type CreatorApplicationsListData struct {
	Items   []CreatorApplicationListItem `json:"items"`
	Page    int                          `json:"page"`
	PerPage int                          `json:"perPage"`

	// Total Total number of matching applications across all pages.
	Total int64 `json:"total"`
}

// CreatorApplicationsListRequest defines model for CreatorApplicationsListRequest.
type CreatorApplicationsListRequest struct {
	// AgeFrom Inclusive lower bound for the creator's age in full years (computed from birth_date).
	AgeFrom *int `json:"ageFrom,omitempty"`

	// AgeTo Inclusive upper bound for the creator's age in full years.
	AgeTo *int `json:"ageTo,omitempty"`

	// Categories Match applications that include any of these category codes.
	Categories *[]string `json:"categories,omitempty"`

	// Cities Match any of these city codes (from the cities dictionary).
	Cities *[]string `json:"cities,omitempty"`

	// DateFrom Inclusive lower bound for `created_at`.
	DateFrom *time.Time `json:"dateFrom,omitempty"`

	// DateTo Inclusive upper bound for `created_at`.
	DateTo *time.Time `json:"dateTo,omitempty"`

	// Order Sort direction.
	Order SortOrder `json:"order"`

	// Page 1-based page index.
	Page int `json:"page"`

	// PerPage Page size, between 1 and 200 inclusive.
	PerPage int `json:"perPage"`

	// Search Free-text search across last_name, first_name, middle_name, IIN
	// (case-insensitive) and social-account handles. Trimmed; empty/blank
	// after trim disables the filter. Carries PII — the endpoint is POST
	// so this never lands in URL params.
	Search *string `json:"search,omitempty"`

	// Sort Sort field for the admin list. Mapped to a SQL column / expression on
	// the backend. Unknown values are rejected with 422.
	Sort CreatorApplicationListSortField `json:"sort"`

	// Statuses Match any of these statuses. Empty/missing → all statuses.
	Statuses *[]CreatorApplicationStatus `json:"statuses,omitempty"`

	// TelegramLinked When true, only applications already bound to a Telegram account
	// are returned. When false, only those still without a link.
	// Missing/null disables the filter.
	TelegramLinked *bool `json:"telegramLinked,omitempty"`
}

// CreatorApplicationsListResult defines model for CreatorApplicationsListResult.
type CreatorApplicationsListResult struct {
	Data CreatorApplicationsListData `json:"data"`
}

// CreatorApprovalData Payload returned by POST /creators/applications/{id}/approve.
type CreatorApprovalData struct {
	// CreatorId ID of the creator row created by the approve action.
	CreatorId openapi_types.UUID `json:"creatorId"`
}

// CreatorApprovalResult defines model for CreatorApprovalResult.
type CreatorApprovalResult struct {
	// Data Payload returned by POST /creators/applications/{id}/approve.
	Data CreatorApprovalData `json:"data"`
}

// DictionaryItem Single entry from a public dictionary (categories, cities, etc.).
// Reused for the dictionary-listing endpoint and for hydrated dictionary
// references on creator-application reads, where the backend falls back
// to `(code, code, 0)` when the underlying dictionary row has been
// deactivated.
type DictionaryItem struct {
	// Code Stable machine-readable identifier (snake_case).
	Code string `json:"code"`

	// Name Human-readable label rendered to the user.
	Name string `json:"name"`

	// SortOrder Sort key — lower values appear first in the UI.
	SortOrder int `json:"sortOrder"`
}

// DictionaryListResult defines model for DictionaryListResult.
type DictionaryListResult struct {
	Data ListDictionaryData `json:"data"`
}

// EmptyResult Generic empty success envelope for endpoints that do not carry a
// payload back. Clients should refetch the relevant resource to
// observe state changes.
type EmptyResult = map[string]interface{}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// GetBrandResult defines model for GetBrandResult.
type GetBrandResult struct {
	Data BrandDetailData `json:"data"`
}

// GetCreatorApplicationResult defines model for GetCreatorApplicationResult.
type GetCreatorApplicationResult struct {
	Data CreatorApplicationDetailData `json:"data"`
}

// GetCreatorResult defines model for GetCreatorResult.
type GetCreatorResult struct {
	// Data Full creator profile assembled from `creators` plus the snapshot tables
	// `creator_socials` and `creator_categories`. The Telegram block is
	// flattened (no separate object) because the only path to materialise a
	// creator is via approve, which guarantees a Telegram link existed at
	// that moment. City and category codes are returned alongside their
	// localised names hydrated from the active public dictionaries; missing
	// dictionary entries degrade to a `name == code` fallback.
	Data CreatorAggregate `json:"data"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ListAuditLogsData defines model for ListAuditLogsData.
type ListAuditLogsData struct {
	Logs    []AuditLogEntry `json:"logs"`
	Page    int             `json:"page"`
	PerPage int             `json:"perPage"`
	Total   int64           `json:"total"`
}

// ListBrandsData defines model for ListBrandsData.
type ListBrandsData struct {
	Brands []BrandListItem `json:"brands"`
}

// ListBrandsResult defines model for ListBrandsResult.
type ListBrandsResult struct {
	Data ListBrandsData `json:"data"`
}

// ListDictionaryData defines model for ListDictionaryData.
type ListDictionaryData struct {
	Items []DictionaryItem `json:"items"`

	// Type Dictionary type echoed back to the client.
	Type string `json:"type"`
}

// LoginData defines model for LoginData.
type LoginData struct {
	AccessToken string `json:"accessToken"`
	User        User   `json:"user"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Data LoginData `json:"data"`
}

// ManagerInfo defines model for ManagerInfo.
type ManagerInfo struct {
	AssignedAt time.Time `json:"assignedAt"`
	Email      string    `json:"email"`
	UserId     string    `json:"userId"`
}

// MessageData defines model for MessageData.
type MessageData struct {
	Message string `json:"message"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Data MessageData `json:"data"`
}

// PaginationInput Shared 1-based pagination payload for body-paginated list endpoints.
type PaginationInput struct {
	// Page 1-based page index.
	Page int `json:"page"`

	// PerPage Page size, between 1 and 200 inclusive.
	PerPage int `json:"perPage"`
}

// PasswordResetBody defines model for PasswordResetBody.
type PasswordResetBody struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// PasswordResetRequestBody defines model for PasswordResetRequestBody.
type PasswordResetRequestBody struct {
	Email openapi_types.Email `json:"email"`
}

// SendPulseInstagramWebhookRequest Custom JSON payload SendPulse delivers from the Instagram chatbot.
// `username` and `lastMessage` come from the configured "send custom
// data" action; `contactId` is SendPulse's opaque contact identifier
// kept for trace correlation.
type SendPulseInstagramWebhookRequest struct {
	// ContactId Optional SendPulse contact id; opaque to backend, kept for correlation.
	ContactId *string `json:"contactId,omitempty"`

	// LastMessage Body of the last message in the IG DM thread.
	LastMessage string `json:"lastMessage"`

	// Username Instagram handle of the message sender as SendPulse received it.
	Username string `json:"username"`
}

// SendPulseInstagramWebhookResult Empty object — the SendPulse webhook never carries data back. Both
// success (200) and the constant-time auth failure (401) emit the
// same `{}` body.
type SendPulseInstagramWebhookResult = map[string]interface{}

// SocialAccountInput defines model for SocialAccountInput.
type SocialAccountInput struct {
	// Handle Account handle or public identifier on the given platform.
	Handle string `json:"handle"`

	// Platform Supported social network for creator accounts (MVP scope).
	Platform SocialPlatform `json:"platform"`
}

// SocialPlatform Supported social network for creator accounts (MVP scope).
type SocialPlatform string

// SocialVerificationMethod How a social account was verified. `auto` — webhook from SendPulse caught
// the verification code in an Instagram DM. `manual` — admin marked the
// social as verified from the application drawer.
type SocialVerificationMethod string

// SortOrder Sort direction.
type SortOrder string

// TelegramLink Telegram account linked to a creator application via /start deep-link.
type TelegramLink struct {
	// LinkedAt Timestamp of the successful link.
	LinkedAt time.Time `json:"linkedAt"`

	// TelegramFirstName Telegram first_name at link time. Nullable.
	TelegramFirstName *string `json:"telegramFirstName,omitempty"`

	// TelegramLastName Telegram last_name at link time. Nullable.
	TelegramLastName *string `json:"telegramLastName,omitempty"`

	// TelegramUserId Telegram numeric user id (BIGINT) — stable identifier of the linked account.
	TelegramUserId int64 `json:"telegramUserId"`

	// TelegramUsername Telegram @username at link time (no leading @). Nullable.
	TelegramUsername *string `json:"telegramUsername,omitempty"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`

	// Role Role of an authenticated user.
	Role UserRole `json:"role"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// UserRole Role of an authenticated user.
type UserRole string

// PageQueryParam defines model for PageQueryParam.
type PageQueryParam = int

// PerPageQueryParam defines model for PerPageQueryParam.
type PerPageQueryParam = int

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError = ErrorResponse

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	ActorId    *string    `form:"actorId,omitempty" json:"actorId,omitempty"`
	EntityType *string    `form:"entityType,omitempty" json:"entityType,omitempty"`
	EntityId   *string    `form:"entityId,omitempty" json:"entityId,omitempty"`
	Action     *string    `form:"action,omitempty" json:"action,omitempty"`
	DateFrom   *time.Time `form:"dateFrom,omitempty" json:"dateFrom,omitempty"`
	DateTo     *time.Time `form:"dateTo,omitempty" json:"dateTo,omitempty"`

	// Page 1-based page index.
	Page *PageQueryParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size, between 1 and 200 inclusive.
	PerPage *PerPageQueryParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// VerifyCreatorApplicationSocialJSONBody defines parameters for VerifyCreatorApplicationSocial.
type VerifyCreatorApplicationSocialJSONBody = map[string]interface{}

// ListDictionaryParamsType defines parameters for ListDictionary.
type ListDictionaryParamsType string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = PasswordResetBody

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequestBody

// CreateBrandJSONRequestBody defines body for CreateBrand for application/json ContentType.
type CreateBrandJSONRequestBody = BrandInput

// UpdateBrandJSONRequestBody defines body for UpdateBrand for application/json ContentType.
type UpdateBrandJSONRequestBody = BrandInput

// AssignManagerJSONRequestBody defines body for AssignManager for application/json ContentType.
type AssignManagerJSONRequestBody = AssignManagerRequest

// SubmitCreatorApplicationJSONRequestBody defines body for SubmitCreatorApplication for application/json ContentType.
type SubmitCreatorApplicationJSONRequestBody = CreatorApplicationSubmitRequest

// ListCreatorApplicationsJSONRequestBody defines body for ListCreatorApplications for application/json ContentType.
type ListCreatorApplicationsJSONRequestBody = CreatorApplicationsListRequest

// VerifyCreatorApplicationSocialJSONRequestBody defines body for VerifyCreatorApplicationSocial for application/json ContentType.
type VerifyCreatorApplicationSocialJSONRequestBody = VerifyCreatorApplicationSocialJSONBody

// SendPulseInstagramWebhookJSONRequestBody defines body for SendPulseInstagramWebhook for application/json ContentType.
type SendPulseInstagramWebhookJSONRequestBody = SendPulseInstagramWebhookRequest
