-- +goose Up
-- +goose StatementBegin
-- contracts.serial_number — sequence для TrustMe NumberDial. Существующие
-- ряды backfill'ятся через GENERATED IDENTITY (Postgres ≥10 при ALTER TABLE
-- ADD COLUMN IDENTITY заполняет existing rows автоматически).
ALTER TABLE contracts
    ADD COLUMN serial_number BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ADD CONSTRAINT contracts_serial_number_unique UNIQUE (serial_number);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE contracts
    DROP CONSTRAINT IF EXISTS contracts_serial_number_unique,
    DROP COLUMN IF EXISTS serial_number;
-- +goose StatementEnd
