package handler

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/api"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/domain"
)

// CreateCampaign handles POST /campaigns (admin-only).
//
// Authorisation runs first so non-admin callers receive 403 before any DB
// touch. After authz, name and tmaUrl are trimmed and validated against the
// granular CodeCampaign* contract — empty / >255-name / empty / >2048-url
// each surface as their own 422 code. The 23505 race on
// campaigns_name_active_unique is translated by the repo into
// domain.ErrCampaignNameTaken (a *BusinessError) and rendered as 409
// CAMPAIGN_NAME_TAKEN by respondError's generic *BusinessError branch.
func (s *Server) CreateCampaign(ctx context.Context, request api.CreateCampaignRequestObject) (api.CreateCampaignResponseObject, error) {
	if err := s.authzService.CanCreateCampaign(ctx); err != nil {
		return nil, err
	}

	name := strings.TrimSpace(request.Body.Name)
	tmaURL := strings.TrimSpace(request.Body.TmaUrl)
	if err := domain.ValidateCampaignName(name); err != nil {
		return nil, err
	}
	if err := domain.ValidateCampaignTmaURL(tmaURL); err != nil {
		return nil, err
	}

	campaign, err := s.campaignService.CreateCampaign(ctx, name, tmaURL)
	if err != nil {
		return nil, err
	}

	apiCampaign, err := domainCampaignToAPI(campaign)
	if err != nil {
		return nil, err
	}
	return api.CreateCampaign201JSONResponse{Data: apiCampaign}, nil
}

// domainCampaignToAPI maps the service domain object onto its strict-server
// counterpart. The campaign id is generated by Postgres (gen_random_uuid())
// and travels as a string through the service layer; a parse failure here
// would mean a corrupted DB row, not user input — surface it as a wrapped
// 500 via respondError instead of swallowing.
func domainCampaignToAPI(c *domain.Campaign) (api.Campaign, error) {
	id, err := uuid.Parse(c.ID)
	if err != nil {
		return api.Campaign{}, fmt.Errorf("parse campaign id %q: %w", c.ID, err)
	}
	return api.Campaign{
		Id:        id,
		Name:      c.Name,
		TmaUrl:    c.TmaURL,
		IsDeleted: c.IsDeleted,
		CreatedAt: c.CreatedAt,
		UpdatedAt: c.UpdatedAt,
	}, nil
}
