package handler

import (
	"bytes"
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/api"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/domain"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/handler/mocks"
	logmocks "github.com/alikhanmurzayev/ugcboost/backend/internal/logger/mocks"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/middleware"
)

// validRequest returns a payload that the handler will accept end-to-end so
// scenarios can mutate one field to hit a specific branch.
func validRequest() api.CreatorApplicationSubmitRequest {
	middle := "Ивановна"
	return api.CreatorApplicationSubmitRequest{
		LastName:   "Муратова",
		FirstName:  "Айдана",
		MiddleName: &middle,
		Iin:        "950515312348",
		Phone:      "+77001234567",
		City:       "Алматы",
		Address:    "ул. Абая 1",
		Categories: []string{"beauty", "fashion"},
		Socials: []api.SocialAccountInput{
			{Platform: api.Instagram, Handle: "@aidana"},
			{Platform: api.Tiktok, Handle: "aidana_tt"},
		},
		Consents: api.ConsentsInput{
			Processing:  true,
			ThirdParty:  true,
			CrossBorder: true,
			Terms:       true,
		},
	}
}

func serverWithCreator(t *testing.T, creator CreatorApplicationService, log *logmocks.MockLogger) *Server {
	t.Helper()
	return NewServer(nil, nil, nil, nil, creator, ServerConfig{
		Version:               "test-version",
		TelegramBotUsername:   "ugcboost_test_bot",
		LegalAgreementVersion: "2026-04-20",
		LegalPrivacyVersion:   "2026-04-20",
	}, log)
}

func TestServer_SubmitCreatorApplication(t *testing.T) {
	t.Parallel()

	t.Run("invalid json body returns 422", func(t *testing.T) {
		t.Parallel()
		router := newTestRouter(t, serverWithCreator(t, nil, logmocks.NewMockLogger(t)))

		req := httptest.NewRequest(http.MethodPost, "/creators/applications", bytes.NewReader([]byte("not json")))
		req.Header.Set("Content-Type", "application/json")
		w := httptest.NewRecorder()
		router.ServeHTTP(w, req)

		require.Equal(t, http.StatusUnprocessableEntity, w.Code)
	})

	t.Run("service validation error passes through as 422", func(t *testing.T) {
		t.Parallel()
		creator := mocks.NewMockCreatorApplicationService(t)
		creator.EXPECT().Submit(mock.Anything, mock.Anything).
			Return(nil, domain.NewValidationError(domain.CodeInvalidIIN, "Некорректный ИИН"))

		router := newTestRouter(t, serverWithCreator(t, creator, logmocks.NewMockLogger(t)))
		w, resp := doJSON[api.ErrorResponse](t, router, http.MethodPost, "/creators/applications", validRequest())

		require.Equal(t, http.StatusUnprocessableEntity, w.Code)
		require.Equal(t, domain.CodeInvalidIIN, resp.Error.Code)
	})

	t.Run("duplicate returns 409", func(t *testing.T) {
		t.Parallel()
		creator := mocks.NewMockCreatorApplicationService(t)
		creator.EXPECT().Submit(mock.Anything, mock.Anything).
			Return(nil, domain.NewBusinessError(domain.CodeCreatorApplicationDuplicate, "already exists"))

		router := newTestRouter(t, serverWithCreator(t, creator, logmocks.NewMockLogger(t)))
		w, resp := doJSON[api.ErrorResponse](t, router, http.MethodPost, "/creators/applications", validRequest())

		require.Equal(t, http.StatusConflict, w.Code)
		require.Equal(t, domain.CodeCreatorApplicationDuplicate, resp.Error.Code)
	})

	t.Run("success returns 201 with deep link and forwards every request field", func(t *testing.T) {
		t.Parallel()
		appID := uuid.MustParse("11111111-2222-3333-4444-555555555555")
		creator := mocks.NewMockCreatorApplicationService(t)
		var captured domain.CreatorApplicationInput
		creator.EXPECT().Submit(mock.Anything, mock.Anything).
			Run(func(_ context.Context, in domain.CreatorApplicationInput) {
				captured = in
			}).
			Return(&domain.CreatorApplicationSubmission{
				ApplicationID: appID.String(),
				BirthDate:     time.Date(1995, 5, 15, 0, 0, 0, 0, time.UTC),
			}, nil)

		router := newTestRouterWithClientIP(t, serverWithCreator(t, creator, logmocks.NewMockLogger(t)))
		before := time.Now().UTC()
		w, resp := doJSON[api.CreatorApplicationSubmitResult](t, router, http.MethodPost, "/creators/applications", validRequest(),
			func(r *http.Request) {
				r.Header.Set("User-Agent", "go-test/1")
				r.RemoteAddr = "203.0.113.7:4567"
			})
		after := time.Now().UTC()

		require.Equal(t, http.StatusCreated, w.Code)
		require.Equal(t, api.CreatorApplicationSubmitResult{
			Data: api.CreatorApplicationSubmitData{
				ApplicationId:  appID,
				TelegramBotUrl: "https://t.me/ugcboost_test_bot?start=" + appID.String(),
			},
		}, resp)

		// Every field forwarded verbatim, including IP from the ClientIP
		// middleware. Check Now separately (it's generated by the handler).
		require.WithinDuration(t, before, captured.Now, after.Sub(before)+time.Second)
		captured.Now = time.Time{}
		require.Equal(t, domain.CreatorApplicationInput{
			LastName:         "Муратова",
			FirstName:        "Айдана",
			MiddleName:       strptr("Ивановна"),
			IIN:              "950515312348",
			Phone:            "+77001234567",
			City:             "Алматы",
			Address:          "ул. Абая 1",
			CategoryCodes:    []string{"beauty", "fashion"},
			Socials: []domain.SocialAccountInput{
				{Platform: "instagram", Handle: "@aidana"},
				{Platform: "tiktok", Handle: "aidana_tt"},
			},
			Consents: domain.ConsentsInput{
				Processing: true, ThirdParty: true, CrossBorder: true, Terms: true,
			},
			IPAddress:        "203.0.113.7",
			UserAgent:        "go-test/1",
			AgreementVersion: "2026-04-20",
			PrivacyVersion:   "2026-04-20",
		}, captured)
	})

	t.Run("oversized user agent is truncated", func(t *testing.T) {
		t.Parallel()
		appID := uuid.MustParse("22222222-3333-4444-5555-666666666666")
		oversized := strings.Repeat("x", maxUserAgentLength+128)

		creator := mocks.NewMockCreatorApplicationService(t)
		var captured domain.CreatorApplicationInput
		creator.EXPECT().Submit(mock.Anything, mock.Anything).
			Run(func(_ context.Context, in domain.CreatorApplicationInput) {
				captured = in
			}).
			Return(&domain.CreatorApplicationSubmission{
				ApplicationID: appID.String(),
				BirthDate:     time.Date(1995, 5, 15, 0, 0, 0, 0, time.UTC),
			}, nil)

		router := newTestRouter(t, serverWithCreator(t, creator, logmocks.NewMockLogger(t)))
		w, _ := doJSON[api.CreatorApplicationSubmitResult](t, router, http.MethodPost, "/creators/applications", validRequest(),
			func(r *http.Request) { r.Header.Set("User-Agent", oversized) })

		require.Equal(t, http.StatusCreated, w.Code)
		require.Len(t, captured.UserAgent, maxUserAgentLength)
	})

	t.Run("service returns non-uuid application id yields 500", func(t *testing.T) {
		t.Parallel()
		creator := mocks.NewMockCreatorApplicationService(t)
		creator.EXPECT().Submit(mock.Anything, mock.Anything).
			Return(&domain.CreatorApplicationSubmission{
				ApplicationID: "not-a-uuid",
				BirthDate:     time.Date(1995, 5, 15, 0, 0, 0, 0, time.UTC),
			}, nil)

		log := logmocks.NewMockLogger(t)
		expectHandlerUnexpectedErrorLog(log, "/creators/applications")
		router := newTestRouter(t, serverWithCreator(t, creator, log))
		w, _ := doJSON[api.ErrorResponse](t, router, http.MethodPost, "/creators/applications", validRequest())

		require.Equal(t, http.StatusInternalServerError, w.Code)
	})

	t.Run("bot username with url-unsafe characters is escaped in deep link", func(t *testing.T) {
		t.Parallel()
		appID := uuid.MustParse("33333333-4444-5555-6666-777777777777")
		creator := mocks.NewMockCreatorApplicationService(t)
		creator.EXPECT().Submit(mock.Anything, mock.Anything).
			Return(&domain.CreatorApplicationSubmission{
				ApplicationID: appID.String(),
				BirthDate:     time.Date(1995, 5, 15, 0, 0, 0, 0, time.UTC),
			}, nil)

		// Simulate a misconfigured env: slashes and spaces should be escaped
		// rather than corrupting the URL path.
		server := NewServer(nil, nil, nil, nil, creator, ServerConfig{
			Version:               "test-version",
			TelegramBotUsername:   "bad name/bot",
			LegalAgreementVersion: "2026-04-20",
			LegalPrivacyVersion:   "2026-04-20",
		}, logmocks.NewMockLogger(t))
		router := newTestRouter(t, server)
		w, resp := doJSON[api.CreatorApplicationSubmitResult](t, router, http.MethodPost, "/creators/applications", validRequest())

		require.Equal(t, http.StatusCreated, w.Code)
		require.Equal(t, "https://t.me/bad%20name%2Fbot?start="+appID.String(), resp.Data.TelegramBotUrl)
	})
}

// newTestRouterWithClientIP wires the ClientIP middleware the same way
// cmd/api does, so handler tests can verify that IPAddress flows from
// r.RemoteAddr into the service input.
func newTestRouterWithClientIP(t *testing.T, s *Server) chi.Router {
	t.Helper()
	r := chi.NewRouter()
	r.Use(middleware.ClientIP)
	api.HandlerWithOptions(s, api.ChiServerOptions{
		BaseRouter:       r,
		ErrorHandlerFunc: HandleParamError(logmocks.NewMockLogger(t)),
	})
	return r
}
