import type { Campaign } from "../types";

const ALMATY = { code: "almaty", name: "Алматы" };
const ASTANA = { code: "astana", name: "Астана" };

const BEAUTY = { code: "beauty", name: "Бьюти (макияж, уход)" };
const FOOD = { code: "food", name: "Еда / Рестораны" };
const LIFESTYLE = { code: "lifestyle", name: "Лайфстайл" };
const FASHION = { code: "fashion", name: "Мода / Стиль" };

const BRAND_ID = "00000000-0000-0000-0000-0000000000aa";
const BRAND_NAME = "Fixprice";

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "c1000000-0000-0000-0000-000000000001",
    brandId: BRAND_ID,
    brandName: BRAND_NAME,
    type: "product",
    status: "active",
    title: "Челлендж «Что я купил за 5000 тенге в Fixprice»",
    description:
      "Каждый креатор получает 5000 тг сертификат на покупки в Fixprice. Делает Reels-челлендж: обзор покупок с эмоциями, каждый товар в кадре, итоговая сумма на чеке.",
    hashtags: "#fixprice",
    mentionsInCaption: "@fixprice.kz",
    references: [
      {
        url: "https://www.instagram.com/reel/CtExample1",
        description: "Динамичный челлендж-формат, чек в кадре",
      },
      {
        url: "https://www.instagram.com/reel/CtExample2",
        description: "Сторителлинг с озвучкой и реакциями",
      },
    ],
    attachments: [
      {
        id: "att-001",
        name: "fixprice_logo.png",
        url: "/mock-files/fixprice_logo.png",
        contentType: "image/png",
        sizeBytes: 84_000,
      },
      {
        id: "att-002",
        name: "brand_guidelines.pdf",
        url: "/mock-files/brand_guidelines.pdf",
        contentType: "application/pdf",
        sizeBytes: 1_200_000,
      },
    ],
    creatorsCount: 3,
    anyCategories: false,
    categories: [BEAUTY, FASHION],
    minFollowers: 1000,
    minAvgViews: 3000,
    ageMin: 18,
    ageMax: 35,
    anyCities: false,
    cities: [ALMATY, ASTANA],
    genders: ["female"],
    languages: ["ru", "kz"],
    socialPlatform: "instagram",
    contentFormats: ["reels", "stories"],
    postsByFormat: { reels: 1, stories: 1 },
    publishDeadline: "2026-05-15T23:59:59Z",
    publishDeadlineMode: "until",
    paymentType: "barter",
    barterDescription:
      "Сертификат Fixprice 5000 ₸ на покупки в магазине",
    barterValue: 5000,
    barterAttachments: [],
    requiresScriptApproval: false,
    publicationMode: "creator",
    isCollabPost: false,
    collabBrandHandles: [],
    crossposting: "creator_choice",
    requiresMaterialApproval: true,
    requiresVisit: false,
    createdAt: "2026-04-25T10:00:00Z",
    updatedAt: "2026-04-26T12:00:00Z",
    publishedAt: "2026-04-26T12:00:00Z",
  },
  {
    id: "c1000000-0000-0000-0000-000000000002",
    brandId: BRAND_ID,
    brandName: BRAND_NAME,
    type: "product",
    status: "pending_moderation",
    title: "Обзор товаров для уборки и дома",
    description:
      "Высылаем набор товаров для дома (швабра, средства, аксессуары). Креатор показывает результат до/после уборки, делает обзор удобства.",
    hashtags: "#fixprice",
    mentionsInCaption: "@fixprice.kz",
    references: [
      {
        url: "https://www.tiktok.com/@example/video/123",
        description: "Распаковка сетов с эстетикой",
      },
    ],
    attachments: [],
    creatorsCount: 5,
    anyCategories: false,
    categories: [FOOD, LIFESTYLE],
    minFollowers: 1000,
    minAvgViews: 2000,
    ageMin: 20,
    ageMax: 40,
    anyCities: false,
    cities: [ALMATY],
    genders: ["male", "female"],
    languages: ["ru"],
    socialPlatform: "tiktok",
    contentFormats: [],
    postsByFormat: { post: 1 },
    publishDeadline: "2026-05-10T23:59:59Z",
    publishDeadlineMode: "until",
    paymentType: "fixed",
    paymentAmount: 30000,
    barterAttachments: [],
    requiresScriptApproval: true,
    publicationMode: "creator",
    isCollabPost: false,
    collabBrandHandles: [],
    crossposting: "creator_choice",
    requiresMaterialApproval: true,
    requiresVisit: false,
    createdAt: "2026-04-26T14:00:00Z",
    updatedAt: "2026-04-27T08:30:00Z",
  },
  {
    id: "c1000000-0000-0000-0000-000000000003",
    brandId: BRAND_ID,
    brandName: BRAND_NAME,
    type: "event",
    status: "draft",
    title: "Открытие нового магазина Fixprice",
    description:
      "Открытие флагманского магазина в ТРЦ Mega Park. Нужны Stories с момента открытия и Reels-обзор первого торгового зала.",
    hashtags: "#fixprice",
    mentionsInCaption: "@fixprice.kz",
    references: [],
    attachments: [
      {
        id: "att-003",
        name: "afisha_open.jpg",
        url: "/mock-files/afisha_open.jpg",
        contentType: "image/jpeg",
        sizeBytes: 540_000,
      },
    ],
    creatorsCount: 3,
    anyCategories: false,
    categories: [BEAUTY, LIFESTYLE],
    minFollowers: 500,
    minAvgViews: 1500,
    anyCities: false,
    cities: [ALMATY],
    genders: ["female", "male"],
    languages: ["ru", "kz"],
    socialPlatform: "instagram",
    contentFormats: ["reels", "stories"],
    postsByFormat: { reels: 1, stories: 1 },
    publishDeadline: "2026-05-30T23:59:59Z",
    publishDeadlineMode: "until",
    paymentType: "barter",
    barterDescription:
      "Welcome-набор Fixprice (товары на 7 000 ₸) + бесплатный вход на открытие",
    barterValue: 7000,
    barterAttachments: [],
    requiresScriptApproval: false,
    publicationMode: "creator",
    isCollabPost: false,
    collabBrandHandles: [],
    crossposting: "creator_choice",
    requiresMaterialApproval: false,
    requiresVisit: true,
    eventDetails: {
      country: "Казахстан",
      city: "Алматы",
      date: "2026-05-25",
      timeFrom: "11:00",
      timeTo: "14:00",
      address: "ТРЦ Mega Park, 1 этаж",
      dressCode: "Smart casual",
      parking: "free",
      entryInstructions:
        "Пригласительный высылается на e-mail. Вход строго по списку гостей — возьмите с собой документ, удостоверяющий личность.",
      transfer: {
        type: "group",
        pickup: "ст. метро «Алмалы», у выхода №2",
        schedule: "Сбор в 10:30, выезд в 10:45",
      },
    },
    createdAt: "2026-04-27T09:15:00Z",
    updatedAt: "2026-04-27T09:15:00Z",
  },
  {
    id: "c1000000-0000-0000-0000-000000000004",
    brandId: BRAND_ID,
    brandName: BRAND_NAME,
    type: "service",
    status: "rejected",
    title: "Тест упаковки подарков от Fixprice",
    description:
      "Креатор приходит в магазин, берёт товары и тестирует услугу праздничной упаковки. Снимает процесс и итоговый результат.",
    hashtags: "#fixprice",
    mentionsInCaption: "@fixprice.kz",
    references: [],
    attachments: [],
    creatorsCount: 8,
    anyCategories: false,
    categories: [FASHION, LIFESTYLE],
    minFollowers: 2000,
    minAvgViews: 5000,
    ageMin: 18,
    ageMax: 45,
    anyCities: false,
    cities: [ALMATY],
    genders: ["female", "male"],
    languages: ["ru", "kz"],
    socialPlatform: "instagram",
    contentFormats: ["reels", "stories", "post"],
    postsByFormat: { reels: 1, stories: 1, post: 1 },
    publishDeadline: "2026-05-15T23:59:59Z",
    publishDeadlineMode: "until",
    paymentType: "fixed",
    paymentAmount: 30000,
    barterAttachments: [],
    requiresScriptApproval: false,
    publicationMode: "creator",
    isCollabPost: false,
    collabBrandHandles: [],
    crossposting: "creator_choice",
    requiresMaterialApproval: true,
    requiresVisit: true,
    visitDetails: {
      city: "Алматы",
      address: "ул. Толе би 100",
      slots: [],
    },
    rejectionComment:
      "В ТЗ не указан таймлайн съёмки и обязательный дисклеймер «реклама». Поправьте и отправьте на повторную модерацию.",
    createdAt: "2026-04-23T16:00:00Z",
    updatedAt: "2026-04-25T11:20:00Z",
  },
  {
    id: "c1000000-0000-0000-0000-000000000005",
    brandId: BRAND_ID,
    brandName: BRAND_NAME,
    type: "product",
    status: "completed",
    title: "Новогодние товары и декор (декабрь)",
    description:
      "Распаковка и обзор новогодней коллекции декора и подарков. Все работы сданы, кампания закрыта.",
    hashtags: "#fixprice",
    mentionsInCaption: "@fixprice.kz",
    references: [
      {
        url: "https://www.instagram.com/reel/CtWinter1",
        description: "Праздничная атмосфера, акцент на упаковке",
      },
    ],
    attachments: [],
    creatorsCount: 12,
    anyCategories: false,
    categories: [BEAUTY, FASHION, LIFESTYLE],
    minFollowers: 1000,
    minAvgViews: 3000,
    ageMin: 18,
    ageMax: 40,
    anyCities: false,
    cities: [ALMATY, ASTANA],
    genders: ["female"],
    languages: ["ru"],
    socialPlatform: "instagram",
    contentFormats: ["reels"],
    postsByFormat: { reels: 1 },
    publishDeadline: "2026-01-15T23:59:59Z",
    publishDeadlineMode: "until",
    paymentType: "barter",
    barterDescription: "Набор новогоднего декора Fixprice",
    barterValue: 8000,
    barterAttachments: [],
    requiresScriptApproval: false,
    publicationMode: "creator",
    isCollabPost: false,
    collabBrandHandles: [],
    crossposting: "creator_choice",
    requiresMaterialApproval: true,
    requiresVisit: false,
    createdAt: "2025-12-10T08:00:00Z",
    updatedAt: "2026-01-20T15:00:00Z",
    publishedAt: "2025-12-12T10:00:00Z",
  },
];
