// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkService creates a new instance of MockLinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkService {
	mock := &MockLinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkService is an autogenerated mock type for the LinkService type
type MockLinkService struct {
	mock.Mock
}

type MockLinkService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkService) EXPECT() *MockLinkService_Expecter {
	return &MockLinkService_Expecter{mock: &_m.Mock}
}

// LinkTelegram provides a mock function for the type MockLinkService
func (_mock *MockLinkService) LinkTelegram(ctx context.Context, in domain.TelegramLinkInput, now time.Time) (*domain.TelegramLinkResult, error) {
	ret := _mock.Called(ctx, in, now)

	if len(ret) == 0 {
		panic("no return value specified for LinkTelegram")
	}

	var r0 *domain.TelegramLinkResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TelegramLinkInput, time.Time) (*domain.TelegramLinkResult, error)); ok {
		return returnFunc(ctx, in, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TelegramLinkInput, time.Time) *domain.TelegramLinkResult); ok {
		r0 = returnFunc(ctx, in, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TelegramLinkResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TelegramLinkInput, time.Time) error); ok {
		r1 = returnFunc(ctx, in, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkService_LinkTelegram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkTelegram'
type MockLinkService_LinkTelegram_Call struct {
	*mock.Call
}

// LinkTelegram is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.TelegramLinkInput
//   - now time.Time
func (_e *MockLinkService_Expecter) LinkTelegram(ctx interface{}, in interface{}, now interface{}) *MockLinkService_LinkTelegram_Call {
	return &MockLinkService_LinkTelegram_Call{Call: _e.mock.On("LinkTelegram", ctx, in, now)}
}

func (_c *MockLinkService_LinkTelegram_Call) Run(run func(ctx context.Context, in domain.TelegramLinkInput, now time.Time)) *MockLinkService_LinkTelegram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TelegramLinkInput
		if args[1] != nil {
			arg1 = args[1].(domain.TelegramLinkInput)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLinkService_LinkTelegram_Call) Return(telegramLinkResult *domain.TelegramLinkResult, err error) *MockLinkService_LinkTelegram_Call {
	_c.Call.Return(telegramLinkResult, err)
	return _c
}

func (_c *MockLinkService_LinkTelegram_Call) RunAndReturn(run func(ctx context.Context, in domain.TelegramLinkInput, now time.Time) (*domain.TelegramLinkResult, error)) *MockLinkService_LinkTelegram_Call {
	_c.Call.Return(run)
	return _c
}
