// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/integration/telegram"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDispatcher creates a new instance of MockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatcher {
	mock := &MockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDispatcher is an autogenerated mock type for the Dispatcher type
type MockDispatcher struct {
	mock.Mock
}

type MockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatcher) EXPECT() *MockDispatcher_Expecter {
	return &MockDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type MockDispatcher
func (_mock *MockDispatcher) Dispatch(ctx context.Context, update telegram.IncomingUpdate) {
	_mock.Called(ctx, update)
	return
}

// MockDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - update telegram.IncomingUpdate
func (_e *MockDispatcher_Expecter) Dispatch(ctx interface{}, update interface{}) *MockDispatcher_Dispatch_Call {
	return &MockDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, update)}
}

func (_c *MockDispatcher_Dispatch_Call) Run(run func(ctx context.Context, update telegram.IncomingUpdate)) *MockDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 telegram.IncomingUpdate
		if args[1] != nil {
			arg1 = args[1].(telegram.IncomingUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatcher_Dispatch_Call) Return() *MockDispatcher_Dispatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, update telegram.IncomingUpdate)) *MockDispatcher_Dispatch_Call {
	_c.Run(run)
	return _c
}
