// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/integration/telegram"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStartCommandHandler creates a new instance of MockStartCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStartCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStartCommandHandler {
	mock := &MockStartCommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStartCommandHandler is an autogenerated mock type for the StartCommandHandler type
type MockStartCommandHandler struct {
	mock.Mock
}

type MockStartCommandHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStartCommandHandler) EXPECT() *MockStartCommandHandler_Expecter {
	return &MockStartCommandHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockStartCommandHandler
func (_mock *MockStartCommandHandler) Handle(ctx context.Context, update telegram.IncomingUpdate, payload string) {
	_mock.Called(ctx, update, payload)
	return
}

// MockStartCommandHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockStartCommandHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - update telegram.IncomingUpdate
//   - payload string
func (_e *MockStartCommandHandler_Expecter) Handle(ctx interface{}, update interface{}, payload interface{}) *MockStartCommandHandler_Handle_Call {
	return &MockStartCommandHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, update, payload)}
}

func (_c *MockStartCommandHandler_Handle_Call) Run(run func(ctx context.Context, update telegram.IncomingUpdate, payload string)) *MockStartCommandHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 telegram.IncomingUpdate
		if args[1] != nil {
			arg1 = args[1].(telegram.IncomingUpdate)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStartCommandHandler_Handle_Call) Return() *MockStartCommandHandler_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStartCommandHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, update telegram.IncomingUpdate, payload string)) *MockStartCommandHandler_Handle_Call {
	_c.Run(run)
	return _c
}
