// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTestAPICleanupRepoFactory creates a new instance of MockTestAPICleanupRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestAPICleanupRepoFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestAPICleanupRepoFactory {
	mock := &MockTestAPICleanupRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestAPICleanupRepoFactory is an autogenerated mock type for the TestAPICleanupRepoFactory type
type MockTestAPICleanupRepoFactory struct {
	mock.Mock
}

type MockTestAPICleanupRepoFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestAPICleanupRepoFactory) EXPECT() *MockTestAPICleanupRepoFactory_Expecter {
	return &MockTestAPICleanupRepoFactory_Expecter{mock: &_m.Mock}
}

// NewBrandRepo provides a mock function for the type MockTestAPICleanupRepoFactory
func (_mock *MockTestAPICleanupRepoFactory) NewBrandRepo(db dbutil.DB) repository.BrandRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewBrandRepo")
	}

	var r0 repository.BrandRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.BrandRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.BrandRepo)
		}
	}
	return r0
}

// MockTestAPICleanupRepoFactory_NewBrandRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBrandRepo'
type MockTestAPICleanupRepoFactory_NewBrandRepo_Call struct {
	*mock.Call
}

// NewBrandRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockTestAPICleanupRepoFactory_Expecter) NewBrandRepo(db interface{}) *MockTestAPICleanupRepoFactory_NewBrandRepo_Call {
	return &MockTestAPICleanupRepoFactory_NewBrandRepo_Call{Call: _e.mock.On("NewBrandRepo", db)}
}

func (_c *MockTestAPICleanupRepoFactory_NewBrandRepo_Call) Run(run func(db dbutil.DB)) *MockTestAPICleanupRepoFactory_NewBrandRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestAPICleanupRepoFactory_NewBrandRepo_Call) Return(brandRepo repository.BrandRepo) *MockTestAPICleanupRepoFactory_NewBrandRepo_Call {
	_c.Call.Return(brandRepo)
	return _c
}

func (_c *MockTestAPICleanupRepoFactory_NewBrandRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.BrandRepo) *MockTestAPICleanupRepoFactory_NewBrandRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo provides a mock function for the type MockTestAPICleanupRepoFactory
func (_mock *MockTestAPICleanupRepoFactory) NewUserRepo(db dbutil.DB) repository.UserRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewUserRepo")
	}

	var r0 repository.UserRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.UserRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepo)
		}
	}
	return r0
}

// MockTestAPICleanupRepoFactory_NewUserRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUserRepo'
type MockTestAPICleanupRepoFactory_NewUserRepo_Call struct {
	*mock.Call
}

// NewUserRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockTestAPICleanupRepoFactory_Expecter) NewUserRepo(db interface{}) *MockTestAPICleanupRepoFactory_NewUserRepo_Call {
	return &MockTestAPICleanupRepoFactory_NewUserRepo_Call{Call: _e.mock.On("NewUserRepo", db)}
}

func (_c *MockTestAPICleanupRepoFactory_NewUserRepo_Call) Run(run func(db dbutil.DB)) *MockTestAPICleanupRepoFactory_NewUserRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestAPICleanupRepoFactory_NewUserRepo_Call) Return(userRepo repository.UserRepo) *MockTestAPICleanupRepoFactory_NewUserRepo_Call {
	_c.Call.Return(userRepo)
	return _c
}

func (_c *MockTestAPICleanupRepoFactory_NewUserRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.UserRepo) *MockTestAPICleanupRepoFactory_NewUserRepo_Call {
	_c.Call.Return(run)
	return _c
}
