// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenStore creates a new instance of MockTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStore {
	mock := &MockTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenStore is an autogenerated mock type for the TokenStore type
type MockTokenStore struct {
	mock.Mock
}

type MockTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStore) EXPECT() *MockTokenStore_Expecter {
	return &MockTokenStore_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) GetToken(email string) (string, bool) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockTokenStore_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockTokenStore_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - email string
func (_e *MockTokenStore_Expecter) GetToken(email interface{}) *MockTokenStore_GetToken_Call {
	return &MockTokenStore_GetToken_Call{Call: _e.mock.On("GetToken", email)}
}

func (_c *MockTokenStore_GetToken_Call) Run(run func(email string)) *MockTokenStore_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenStore_GetToken_Call) Return(s string, b bool) *MockTokenStore_GetToken_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockTokenStore_GetToken_Call) RunAndReturn(run func(email string) (string, bool)) *MockTokenStore_GetToken_Call {
	_c.Call.Return(run)
	return _c
}
