// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthzService creates a new instance of MockAuthzService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthzService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthzService {
	mock := &MockAuthzService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthzService is an autogenerated mock type for the AuthzService type
type MockAuthzService struct {
	mock.Mock
}

type MockAuthzService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthzService) EXPECT() *MockAuthzService_Expecter {
	return &MockAuthzService_Expecter{mock: &_m.Mock}
}

// CanAssignManager provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanAssignManager(ctx context.Context, brandID string) error {
	ret := _mock.Called(ctx, brandID)

	if len(ret) == 0 {
		panic("no return value specified for CanAssignManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, brandID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthzService_CanAssignManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAssignManager'
type MockAuthzService_CanAssignManager_Call struct {
	*mock.Call
}

// CanAssignManager is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
func (_e *MockAuthzService_Expecter) CanAssignManager(ctx interface{}, brandID interface{}) *MockAuthzService_CanAssignManager_Call {
	return &MockAuthzService_CanAssignManager_Call{Call: _e.mock.On("CanAssignManager", ctx, brandID)}
}

func (_c *MockAuthzService_CanAssignManager_Call) Run(run func(ctx context.Context, brandID string)) *MockAuthzService_CanAssignManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanAssignManager_Call) Return(err error) *MockAuthzService_CanAssignManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthzService_CanAssignManager_Call) RunAndReturn(run func(ctx context.Context, brandID string) error) *MockAuthzService_CanAssignManager_Call {
	_c.Call.Return(run)
	return _c
}

// CanCreateBrand provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanCreateBrand(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CanCreateBrand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthzService_CanCreateBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanCreateBrand'
type MockAuthzService_CanCreateBrand_Call struct {
	*mock.Call
}

// CanCreateBrand is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthzService_Expecter) CanCreateBrand(ctx interface{}) *MockAuthzService_CanCreateBrand_Call {
	return &MockAuthzService_CanCreateBrand_Call{Call: _e.mock.On("CanCreateBrand", ctx)}
}

func (_c *MockAuthzService_CanCreateBrand_Call) Run(run func(ctx context.Context)) *MockAuthzService_CanCreateBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanCreateBrand_Call) Return(err error) *MockAuthzService_CanCreateBrand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthzService_CanCreateBrand_Call) RunAndReturn(run func(ctx context.Context) error) *MockAuthzService_CanCreateBrand_Call {
	_c.Call.Return(run)
	return _c
}

// CanDeleteBrand provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanDeleteBrand(ctx context.Context, brandID string) error {
	ret := _mock.Called(ctx, brandID)

	if len(ret) == 0 {
		panic("no return value specified for CanDeleteBrand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, brandID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthzService_CanDeleteBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanDeleteBrand'
type MockAuthzService_CanDeleteBrand_Call struct {
	*mock.Call
}

// CanDeleteBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
func (_e *MockAuthzService_Expecter) CanDeleteBrand(ctx interface{}, brandID interface{}) *MockAuthzService_CanDeleteBrand_Call {
	return &MockAuthzService_CanDeleteBrand_Call{Call: _e.mock.On("CanDeleteBrand", ctx, brandID)}
}

func (_c *MockAuthzService_CanDeleteBrand_Call) Run(run func(ctx context.Context, brandID string)) *MockAuthzService_CanDeleteBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanDeleteBrand_Call) Return(err error) *MockAuthzService_CanDeleteBrand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthzService_CanDeleteBrand_Call) RunAndReturn(run func(ctx context.Context, brandID string) error) *MockAuthzService_CanDeleteBrand_Call {
	_c.Call.Return(run)
	return _c
}

// CanListAuditLogs provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanListAuditLogs(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CanListAuditLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthzService_CanListAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListAuditLogs'
type MockAuthzService_CanListAuditLogs_Call struct {
	*mock.Call
}

// CanListAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthzService_Expecter) CanListAuditLogs(ctx interface{}) *MockAuthzService_CanListAuditLogs_Call {
	return &MockAuthzService_CanListAuditLogs_Call{Call: _e.mock.On("CanListAuditLogs", ctx)}
}

func (_c *MockAuthzService_CanListAuditLogs_Call) Run(run func(ctx context.Context)) *MockAuthzService_CanListAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanListAuditLogs_Call) Return(err error) *MockAuthzService_CanListAuditLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthzService_CanListAuditLogs_Call) RunAndReturn(run func(ctx context.Context) error) *MockAuthzService_CanListAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// CanListBrands provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanListBrands(ctx context.Context) (bool, string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CanListBrands")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthzService_CanListBrands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListBrands'
type MockAuthzService_CanListBrands_Call struct {
	*mock.Call
}

// CanListBrands is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthzService_Expecter) CanListBrands(ctx interface{}) *MockAuthzService_CanListBrands_Call {
	return &MockAuthzService_CanListBrands_Call{Call: _e.mock.On("CanListBrands", ctx)}
}

func (_c *MockAuthzService_CanListBrands_Call) Run(run func(ctx context.Context)) *MockAuthzService_CanListBrands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanListBrands_Call) Return(canViewAll bool, userID string, err error) *MockAuthzService_CanListBrands_Call {
	_c.Call.Return(canViewAll, userID, err)
	return _c
}

func (_c *MockAuthzService_CanListBrands_Call) RunAndReturn(run func(ctx context.Context) (bool, string, error)) *MockAuthzService_CanListBrands_Call {
	_c.Call.Return(run)
	return _c
}

// CanRemoveManager provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanRemoveManager(ctx context.Context, brandID string, userID string) error {
	ret := _mock.Called(ctx, brandID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanRemoveManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, brandID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthzService_CanRemoveManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanRemoveManager'
type MockAuthzService_CanRemoveManager_Call struct {
	*mock.Call
}

// CanRemoveManager is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
//   - userID string
func (_e *MockAuthzService_Expecter) CanRemoveManager(ctx interface{}, brandID interface{}, userID interface{}) *MockAuthzService_CanRemoveManager_Call {
	return &MockAuthzService_CanRemoveManager_Call{Call: _e.mock.On("CanRemoveManager", ctx, brandID, userID)}
}

func (_c *MockAuthzService_CanRemoveManager_Call) Run(run func(ctx context.Context, brandID string, userID string)) *MockAuthzService_CanRemoveManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanRemoveManager_Call) Return(err error) *MockAuthzService_CanRemoveManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthzService_CanRemoveManager_Call) RunAndReturn(run func(ctx context.Context, brandID string, userID string) error) *MockAuthzService_CanRemoveManager_Call {
	_c.Call.Return(run)
	return _c
}

// CanUpdateBrand provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanUpdateBrand(ctx context.Context, brandID string) error {
	ret := _mock.Called(ctx, brandID)

	if len(ret) == 0 {
		panic("no return value specified for CanUpdateBrand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, brandID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthzService_CanUpdateBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanUpdateBrand'
type MockAuthzService_CanUpdateBrand_Call struct {
	*mock.Call
}

// CanUpdateBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
func (_e *MockAuthzService_Expecter) CanUpdateBrand(ctx interface{}, brandID interface{}) *MockAuthzService_CanUpdateBrand_Call {
	return &MockAuthzService_CanUpdateBrand_Call{Call: _e.mock.On("CanUpdateBrand", ctx, brandID)}
}

func (_c *MockAuthzService_CanUpdateBrand_Call) Run(run func(ctx context.Context, brandID string)) *MockAuthzService_CanUpdateBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanUpdateBrand_Call) Return(err error) *MockAuthzService_CanUpdateBrand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthzService_CanUpdateBrand_Call) RunAndReturn(run func(ctx context.Context, brandID string) error) *MockAuthzService_CanUpdateBrand_Call {
	_c.Call.Return(run)
	return _c
}

// CanViewBrand provides a mock function for the type MockAuthzService
func (_mock *MockAuthzService) CanViewBrand(ctx context.Context, brandID string) error {
	ret := _mock.Called(ctx, brandID)

	if len(ret) == 0 {
		panic("no return value specified for CanViewBrand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, brandID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthzService_CanViewBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanViewBrand'
type MockAuthzService_CanViewBrand_Call struct {
	*mock.Call
}

// CanViewBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
func (_e *MockAuthzService_Expecter) CanViewBrand(ctx interface{}, brandID interface{}) *MockAuthzService_CanViewBrand_Call {
	return &MockAuthzService_CanViewBrand_Call{Call: _e.mock.On("CanViewBrand", ctx, brandID)}
}

func (_c *MockAuthzService_CanViewBrand_Call) Run(run func(ctx context.Context, brandID string)) *MockAuthzService_CanViewBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthzService_CanViewBrand_Call) Return(err error) *MockAuthzService_CanViewBrand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthzService_CanViewBrand_Call) RunAndReturn(run func(ctx context.Context, brandID string) error) *MockAuthzService_CanViewBrand_Call {
	_c.Call.Return(run)
	return _c
}
