// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorService creates a new instance of MockCreatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorService {
	mock := &MockCreatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorService is an autogenerated mock type for the CreatorService type
type MockCreatorService struct {
	mock.Mock
}

type MockCreatorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorService) EXPECT() *MockCreatorService_Expecter {
	return &MockCreatorService_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockCreatorService
func (_mock *MockCreatorService) GetByID(ctx context.Context, creatorID string) (*domain.CreatorAggregate, error) {
	ret := _mock.Called(ctx, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.CreatorAggregate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.CreatorAggregate, error)); ok {
		return returnFunc(ctx, creatorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.CreatorAggregate); ok {
		r0 = returnFunc(ctx, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreatorAggregate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, creatorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatorService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCreatorService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID string
func (_e *MockCreatorService_Expecter) GetByID(ctx interface{}, creatorID interface{}) *MockCreatorService_GetByID_Call {
	return &MockCreatorService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, creatorID)}
}

func (_c *MockCreatorService_GetByID_Call) Run(run func(ctx context.Context, creatorID string)) *MockCreatorService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorService_GetByID_Call) Return(creatorAggregate *domain.CreatorAggregate, err error) *MockCreatorService_GetByID_Call {
	_c.Call.Return(creatorAggregate, err)
	return _c
}

func (_c *MockCreatorService_GetByID_Call) RunAndReturn(run func(ctx context.Context, creatorID string) (*domain.CreatorAggregate, error)) *MockCreatorService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
