// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCampaignActiveChecker creates a new instance of MockCampaignActiveChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignActiveChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignActiveChecker {
	mock := &MockCampaignActiveChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCampaignActiveChecker is an autogenerated mock type for the CampaignActiveChecker type
type MockCampaignActiveChecker struct {
	mock.Mock
}

type MockCampaignActiveChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCampaignActiveChecker) EXPECT() *MockCampaignActiveChecker_Expecter {
	return &MockCampaignActiveChecker_Expecter{mock: &_m.Mock}
}

// AssertActiveCampaigns provides a mock function for the type MockCampaignActiveChecker
func (_mock *MockCampaignActiveChecker) AssertActiveCampaigns(ctx context.Context, ids []string) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for AssertActiveCampaigns")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCampaignActiveChecker_AssertActiveCampaigns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertActiveCampaigns'
type MockCampaignActiveChecker_AssertActiveCampaigns_Call struct {
	*mock.Call
}

// AssertActiveCampaigns is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockCampaignActiveChecker_Expecter) AssertActiveCampaigns(ctx interface{}, ids interface{}) *MockCampaignActiveChecker_AssertActiveCampaigns_Call {
	return &MockCampaignActiveChecker_AssertActiveCampaigns_Call{Call: _e.mock.On("AssertActiveCampaigns", ctx, ids)}
}

func (_c *MockCampaignActiveChecker_AssertActiveCampaigns_Call) Run(run func(ctx context.Context, ids []string)) *MockCampaignActiveChecker_AssertActiveCampaigns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCampaignActiveChecker_AssertActiveCampaigns_Call) Return(err error) *MockCampaignActiveChecker_AssertActiveCampaigns_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCampaignActiveChecker_AssertActiveCampaigns_Call) RunAndReturn(run func(ctx context.Context, ids []string) error) *MockCampaignActiveChecker_AssertActiveCampaigns_Call {
	_c.Call.Return(run)
	return _c
}
