// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/integration/telegram"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelegramSpy creates a new instance of MockTelegramSpy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelegramSpy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelegramSpy {
	mock := &MockTelegramSpy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelegramSpy is an autogenerated mock type for the TelegramSpy type
type MockTelegramSpy struct {
	mock.Mock
}

type MockTelegramSpy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelegramSpy) EXPECT() *MockTelegramSpy_Expecter {
	return &MockTelegramSpy_Expecter{mock: &_m.Mock}
}

// Drain provides a mock function for the type MockTelegramSpy
func (_mock *MockTelegramSpy) Drain(chatID int64) []telegram.SentMessage {
	ret := _mock.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 []telegram.SentMessage
	if returnFunc, ok := ret.Get(0).(func(int64) []telegram.SentMessage); ok {
		r0 = returnFunc(chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]telegram.SentMessage)
		}
	}
	return r0
}

// MockTelegramSpy_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type MockTelegramSpy_Drain_Call struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
//   - chatID int64
func (_e *MockTelegramSpy_Expecter) Drain(chatID interface{}) *MockTelegramSpy_Drain_Call {
	return &MockTelegramSpy_Drain_Call{Call: _e.mock.On("Drain", chatID)}
}

func (_c *MockTelegramSpy_Drain_Call) Run(run func(chatID int64)) *MockTelegramSpy_Drain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTelegramSpy_Drain_Call) Return(sentMessages []telegram.SentMessage) *MockTelegramSpy_Drain_Call {
	_c.Call.Return(sentMessages)
	return _c
}

func (_c *MockTelegramSpy_Drain_Call) RunAndReturn(run func(chatID int64) []telegram.SentMessage) *MockTelegramSpy_Drain_Call {
	_c.Call.Return(run)
	return _c
}
