// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/integration/telegram"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelegramDispatcher creates a new instance of MockTelegramDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelegramDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelegramDispatcher {
	mock := &MockTelegramDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelegramDispatcher is an autogenerated mock type for the TelegramDispatcher type
type MockTelegramDispatcher struct {
	mock.Mock
}

type MockTelegramDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelegramDispatcher) EXPECT() *MockTelegramDispatcher_Expecter {
	return &MockTelegramDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type MockTelegramDispatcher
func (_mock *MockTelegramDispatcher) Dispatch(ctx context.Context, update telegram.IncomingUpdate) {
	_mock.Called(ctx, update)
	return
}

// MockTelegramDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockTelegramDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - update telegram.IncomingUpdate
func (_e *MockTelegramDispatcher_Expecter) Dispatch(ctx interface{}, update interface{}) *MockTelegramDispatcher_Dispatch_Call {
	return &MockTelegramDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, update)}
}

func (_c *MockTelegramDispatcher_Dispatch_Call) Run(run func(ctx context.Context, update telegram.IncomingUpdate)) *MockTelegramDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 telegram.IncomingUpdate
		if args[1] != nil {
			arg1 = args[1].(telegram.IncomingUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTelegramDispatcher_Dispatch_Call) Return() *MockTelegramDispatcher_Dispatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelegramDispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, update telegram.IncomingUpdate)) *MockTelegramDispatcher_Dispatch_Call {
	_c.Run(run)
	return _c
}
