// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCampaignService creates a new instance of MockCampaignService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignService {
	mock := &MockCampaignService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCampaignService is an autogenerated mock type for the CampaignService type
type MockCampaignService struct {
	mock.Mock
}

type MockCampaignService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCampaignService) EXPECT() *MockCampaignService_Expecter {
	return &MockCampaignService_Expecter{mock: &_m.Mock}
}

// CreateCampaign provides a mock function for the type MockCampaignService
func (_mock *MockCampaignService) CreateCampaign(ctx context.Context, name string, tmaURL string) (*domain.Campaign, error) {
	ret := _mock.Called(ctx, name, tmaURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateCampaign")
	}

	var r0 *domain.Campaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Campaign, error)); ok {
		return returnFunc(ctx, name, tmaURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Campaign); ok {
		r0 = returnFunc(ctx, name, tmaURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, tmaURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCampaignService_CreateCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCampaign'
type MockCampaignService_CreateCampaign_Call struct {
	*mock.Call
}

// CreateCampaign is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - tmaURL string
func (_e *MockCampaignService_Expecter) CreateCampaign(ctx interface{}, name interface{}, tmaURL interface{}) *MockCampaignService_CreateCampaign_Call {
	return &MockCampaignService_CreateCampaign_Call{Call: _e.mock.On("CreateCampaign", ctx, name, tmaURL)}
}

func (_c *MockCampaignService_CreateCampaign_Call) Run(run func(ctx context.Context, name string, tmaURL string)) *MockCampaignService_CreateCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCampaignService_CreateCampaign_Call) Return(campaign *domain.Campaign, err error) *MockCampaignService_CreateCampaign_Call {
	_c.Call.Return(campaign, err)
	return _c
}

func (_c *MockCampaignService_CreateCampaign_Call) RunAndReturn(run func(ctx context.Context, name string, tmaURL string) (*domain.Campaign, error)) *MockCampaignService_CreateCampaign_Call {
	_c.Call.Return(run)
	return _c
}
