// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrands creates a new instance of MockBrands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrands {
	mock := &MockBrands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrands is an autogenerated mock type for the Brands type
type MockBrands struct {
	mock.Mock
}

type MockBrands_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrands) EXPECT() *MockBrands_Expecter {
	return &MockBrands_Expecter{mock: &_m.Mock}
}

// AssignManager provides a mock function for the type MockBrands
func (_mock *MockBrands) AssignManager(ctx context.Context, brandID string, email string) (*repository.UserRow, string, error) {
	ret := _mock.Called(ctx, brandID, email)

	if len(ret) == 0 {
		panic("no return value specified for AssignManager")
	}

	var r0 *repository.UserRow
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.UserRow, string, error)); ok {
		return returnFunc(ctx, brandID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.UserRow); ok {
		r0 = returnFunc(ctx, brandID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.UserRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, brandID, email)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, brandID, email)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBrands_AssignManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignManager'
type MockBrands_AssignManager_Call struct {
	*mock.Call
}

// AssignManager is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
//   - email string
func (_e *MockBrands_Expecter) AssignManager(ctx interface{}, brandID interface{}, email interface{}) *MockBrands_AssignManager_Call {
	return &MockBrands_AssignManager_Call{Call: _e.mock.On("AssignManager", ctx, brandID, email)}
}

func (_c *MockBrands_AssignManager_Call) Run(run func(ctx context.Context, brandID string, email string)) *MockBrands_AssignManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrands_AssignManager_Call) Return(userRow *repository.UserRow, s string, err error) *MockBrands_AssignManager_Call {
	_c.Call.Return(userRow, s, err)
	return _c
}

func (_c *MockBrands_AssignManager_Call) RunAndReturn(run func(ctx context.Context, brandID string, email string) (*repository.UserRow, string, error)) *MockBrands_AssignManager_Call {
	_c.Call.Return(run)
	return _c
}

// CanViewBrand provides a mock function for the type MockBrands
func (_mock *MockBrands) CanViewBrand(ctx context.Context, userID string, role string, brandID string) error {
	ret := _mock.Called(ctx, userID, role, brandID)

	if len(ret) == 0 {
		panic("no return value specified for CanViewBrand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, role, brandID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrands_CanViewBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanViewBrand'
type MockBrands_CanViewBrand_Call struct {
	*mock.Call
}

// CanViewBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
//   - brandID string
func (_e *MockBrands_Expecter) CanViewBrand(ctx interface{}, userID interface{}, role interface{}, brandID interface{}) *MockBrands_CanViewBrand_Call {
	return &MockBrands_CanViewBrand_Call{Call: _e.mock.On("CanViewBrand", ctx, userID, role, brandID)}
}

func (_c *MockBrands_CanViewBrand_Call) Run(run func(ctx context.Context, userID string, role string, brandID string)) *MockBrands_CanViewBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBrands_CanViewBrand_Call) Return(err error) *MockBrands_CanViewBrand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrands_CanViewBrand_Call) RunAndReturn(run func(ctx context.Context, userID string, role string, brandID string) error) *MockBrands_CanViewBrand_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBrand provides a mock function for the type MockBrands
func (_mock *MockBrands) CreateBrand(ctx context.Context, name string, logoURL *string) (*repository.BrandRow, error) {
	ret := _mock.Called(ctx, name, logoURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateBrand")
	}

	var r0 *repository.BrandRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) (*repository.BrandRow, error)); ok {
		return returnFunc(ctx, name, logoURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) *repository.BrandRow); ok {
		r0 = returnFunc(ctx, name, logoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.BrandRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = returnFunc(ctx, name, logoURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrands_CreateBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBrand'
type MockBrands_CreateBrand_Call struct {
	*mock.Call
}

// CreateBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - logoURL *string
func (_e *MockBrands_Expecter) CreateBrand(ctx interface{}, name interface{}, logoURL interface{}) *MockBrands_CreateBrand_Call {
	return &MockBrands_CreateBrand_Call{Call: _e.mock.On("CreateBrand", ctx, name, logoURL)}
}

func (_c *MockBrands_CreateBrand_Call) Run(run func(ctx context.Context, name string, logoURL *string)) *MockBrands_CreateBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrands_CreateBrand_Call) Return(brandRow *repository.BrandRow, err error) *MockBrands_CreateBrand_Call {
	_c.Call.Return(brandRow, err)
	return _c
}

func (_c *MockBrands_CreateBrand_Call) RunAndReturn(run func(ctx context.Context, name string, logoURL *string) (*repository.BrandRow, error)) *MockBrands_CreateBrand_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBrand provides a mock function for the type MockBrands
func (_mock *MockBrands) DeleteBrand(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBrand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrands_DeleteBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBrand'
type MockBrands_DeleteBrand_Call struct {
	*mock.Call
}

// DeleteBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBrands_Expecter) DeleteBrand(ctx interface{}, id interface{}) *MockBrands_DeleteBrand_Call {
	return &MockBrands_DeleteBrand_Call{Call: _e.mock.On("DeleteBrand", ctx, id)}
}

func (_c *MockBrands_DeleteBrand_Call) Run(run func(ctx context.Context, id string)) *MockBrands_DeleteBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrands_DeleteBrand_Call) Return(err error) *MockBrands_DeleteBrand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrands_DeleteBrand_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockBrands_DeleteBrand_Call {
	_c.Call.Return(run)
	return _c
}

// GetBrand provides a mock function for the type MockBrands
func (_mock *MockBrands) GetBrand(ctx context.Context, id string) (*repository.BrandRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBrand")
	}

	var r0 *repository.BrandRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.BrandRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.BrandRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.BrandRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrands_GetBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBrand'
type MockBrands_GetBrand_Call struct {
	*mock.Call
}

// GetBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBrands_Expecter) GetBrand(ctx interface{}, id interface{}) *MockBrands_GetBrand_Call {
	return &MockBrands_GetBrand_Call{Call: _e.mock.On("GetBrand", ctx, id)}
}

func (_c *MockBrands_GetBrand_Call) Run(run func(ctx context.Context, id string)) *MockBrands_GetBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrands_GetBrand_Call) Return(brandRow *repository.BrandRow, err error) *MockBrands_GetBrand_Call {
	_c.Call.Return(brandRow, err)
	return _c
}

func (_c *MockBrands_GetBrand_Call) RunAndReturn(run func(ctx context.Context, id string) (*repository.BrandRow, error)) *MockBrands_GetBrand_Call {
	_c.Call.Return(run)
	return _c
}

// ListBrands provides a mock function for the type MockBrands
func (_mock *MockBrands) ListBrands(ctx context.Context, userID string, role string) ([]*repository.BrandWithManagerCount, error) {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for ListBrands")
	}

	var r0 []*repository.BrandWithManagerCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*repository.BrandWithManagerCount, error)); ok {
		return returnFunc(ctx, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*repository.BrandWithManagerCount); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.BrandWithManagerCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrands_ListBrands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBrands'
type MockBrands_ListBrands_Call struct {
	*mock.Call
}

// ListBrands is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
func (_e *MockBrands_Expecter) ListBrands(ctx interface{}, userID interface{}, role interface{}) *MockBrands_ListBrands_Call {
	return &MockBrands_ListBrands_Call{Call: _e.mock.On("ListBrands", ctx, userID, role)}
}

func (_c *MockBrands_ListBrands_Call) Run(run func(ctx context.Context, userID string, role string)) *MockBrands_ListBrands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrands_ListBrands_Call) Return(brandWithManagerCounts []*repository.BrandWithManagerCount, err error) *MockBrands_ListBrands_Call {
	_c.Call.Return(brandWithManagerCounts, err)
	return _c
}

func (_c *MockBrands_ListBrands_Call) RunAndReturn(run func(ctx context.Context, userID string, role string) ([]*repository.BrandWithManagerCount, error)) *MockBrands_ListBrands_Call {
	_c.Call.Return(run)
	return _c
}

// ListManagers provides a mock function for the type MockBrands
func (_mock *MockBrands) ListManagers(ctx context.Context, brandID string) ([]*repository.BrandManagerRow, error) {
	ret := _mock.Called(ctx, brandID)

	if len(ret) == 0 {
		panic("no return value specified for ListManagers")
	}

	var r0 []*repository.BrandManagerRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*repository.BrandManagerRow, error)); ok {
		return returnFunc(ctx, brandID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*repository.BrandManagerRow); ok {
		r0 = returnFunc(ctx, brandID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.BrandManagerRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, brandID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrands_ListManagers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManagers'
type MockBrands_ListManagers_Call struct {
	*mock.Call
}

// ListManagers is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
func (_e *MockBrands_Expecter) ListManagers(ctx interface{}, brandID interface{}) *MockBrands_ListManagers_Call {
	return &MockBrands_ListManagers_Call{Call: _e.mock.On("ListManagers", ctx, brandID)}
}

func (_c *MockBrands_ListManagers_Call) Run(run func(ctx context.Context, brandID string)) *MockBrands_ListManagers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrands_ListManagers_Call) Return(brandManagerRows []*repository.BrandManagerRow, err error) *MockBrands_ListManagers_Call {
	_c.Call.Return(brandManagerRows, err)
	return _c
}

func (_c *MockBrands_ListManagers_Call) RunAndReturn(run func(ctx context.Context, brandID string) ([]*repository.BrandManagerRow, error)) *MockBrands_ListManagers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveManager provides a mock function for the type MockBrands
func (_mock *MockBrands) RemoveManager(ctx context.Context, brandID string, userID string) error {
	ret := _mock.Called(ctx, brandID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, brandID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrands_RemoveManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveManager'
type MockBrands_RemoveManager_Call struct {
	*mock.Call
}

// RemoveManager is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
//   - userID string
func (_e *MockBrands_Expecter) RemoveManager(ctx interface{}, brandID interface{}, userID interface{}) *MockBrands_RemoveManager_Call {
	return &MockBrands_RemoveManager_Call{Call: _e.mock.On("RemoveManager", ctx, brandID, userID)}
}

func (_c *MockBrands_RemoveManager_Call) Run(run func(ctx context.Context, brandID string, userID string)) *MockBrands_RemoveManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrands_RemoveManager_Call) Return(err error) *MockBrands_RemoveManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrands_RemoveManager_Call) RunAndReturn(run func(ctx context.Context, brandID string, userID string) error) *MockBrands_RemoveManager_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBrand provides a mock function for the type MockBrands
func (_mock *MockBrands) UpdateBrand(ctx context.Context, id string, name string, logoURL *string) (*repository.BrandRow, error) {
	ret := _mock.Called(ctx, id, name, logoURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBrand")
	}

	var r0 *repository.BrandRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) (*repository.BrandRow, error)); ok {
		return returnFunc(ctx, id, name, logoURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) *repository.BrandRow); ok {
		r0 = returnFunc(ctx, id, name, logoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.BrandRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = returnFunc(ctx, id, name, logoURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrands_UpdateBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBrand'
type MockBrands_UpdateBrand_Call struct {
	*mock.Call
}

// UpdateBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - logoURL *string
func (_e *MockBrands_Expecter) UpdateBrand(ctx interface{}, id interface{}, name interface{}, logoURL interface{}) *MockBrands_UpdateBrand_Call {
	return &MockBrands_UpdateBrand_Call{Call: _e.mock.On("UpdateBrand", ctx, id, name, logoURL)}
}

func (_c *MockBrands_UpdateBrand_Call) Run(run func(ctx context.Context, id string, name string, logoURL *string)) *MockBrands_UpdateBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBrands_UpdateBrand_Call) Return(brandRow *repository.BrandRow, err error) *MockBrands_UpdateBrand_Call {
	_c.Call.Return(brandRow, err)
	return _c
}

func (_c *MockBrands_UpdateBrand_Call) RunAndReturn(run func(ctx context.Context, id string, name string, logoURL *string) (*repository.BrandRow, error)) *MockBrands_UpdateBrand_Call {
	_c.Call.Return(run)
	return _c
}
