// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDictionaryService creates a new instance of MockDictionaryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDictionaryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDictionaryService {
	mock := &MockDictionaryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDictionaryService is an autogenerated mock type for the DictionaryService type
type MockDictionaryService struct {
	mock.Mock
}

type MockDictionaryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDictionaryService) EXPECT() *MockDictionaryService_Expecter {
	return &MockDictionaryService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockDictionaryService
func (_mock *MockDictionaryService) List(ctx context.Context, t domain.DictionaryType) ([]domain.DictionaryEntry, error) {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.DictionaryEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DictionaryType) ([]domain.DictionaryEntry, error)); ok {
		return returnFunc(ctx, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DictionaryType) []domain.DictionaryEntry); ok {
		r0 = returnFunc(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DictionaryEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.DictionaryType) error); ok {
		r1 = returnFunc(ctx, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDictionaryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDictionaryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.DictionaryType
func (_e *MockDictionaryService_Expecter) List(ctx interface{}, t interface{}) *MockDictionaryService_List_Call {
	return &MockDictionaryService_List_Call{Call: _e.mock.On("List", ctx, t)}
}

func (_c *MockDictionaryService_List_Call) Run(run func(ctx context.Context, t domain.DictionaryType)) *MockDictionaryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DictionaryType
		if args[1] != nil {
			arg1 = args[1].(domain.DictionaryType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDictionaryService_List_Call) Return(dictionaryEntrys []domain.DictionaryEntry, err error) *MockDictionaryService_List_Call {
	_c.Call.Return(dictionaryEntrys, err)
	return _c
}

func (_c *MockDictionaryService_List_Call) RunAndReturn(run func(ctx context.Context, t domain.DictionaryType) ([]domain.DictionaryEntry, error)) *MockDictionaryService_List_Call {
	_c.Call.Return(run)
	return _c
}
