// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorApplicationStatusTransitionRepo creates a new instance of MockCreatorApplicationStatusTransitionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorApplicationStatusTransitionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorApplicationStatusTransitionRepo {
	mock := &MockCreatorApplicationStatusTransitionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorApplicationStatusTransitionRepo is an autogenerated mock type for the CreatorApplicationStatusTransitionRepo type
type MockCreatorApplicationStatusTransitionRepo struct {
	mock.Mock
}

type MockCreatorApplicationStatusTransitionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorApplicationStatusTransitionRepo) EXPECT() *MockCreatorApplicationStatusTransitionRepo_Expecter {
	return &MockCreatorApplicationStatusTransitionRepo_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockCreatorApplicationStatusTransitionRepo
func (_mock *MockCreatorApplicationStatusTransitionRepo) Insert(ctx context.Context, row repository.CreatorApplicationStatusTransitionRow) error {
	ret := _mock.Called(ctx, row)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreatorApplicationStatusTransitionRow) error); ok {
		r0 = returnFunc(ctx, row)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreatorApplicationStatusTransitionRepo_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCreatorApplicationStatusTransitionRepo_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - row repository.CreatorApplicationStatusTransitionRow
func (_e *MockCreatorApplicationStatusTransitionRepo_Expecter) Insert(ctx interface{}, row interface{}) *MockCreatorApplicationStatusTransitionRepo_Insert_Call {
	return &MockCreatorApplicationStatusTransitionRepo_Insert_Call{Call: _e.mock.On("Insert", ctx, row)}
}

func (_c *MockCreatorApplicationStatusTransitionRepo_Insert_Call) Run(run func(ctx context.Context, row repository.CreatorApplicationStatusTransitionRow)) *MockCreatorApplicationStatusTransitionRepo_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreatorApplicationStatusTransitionRow
		if args[1] != nil {
			arg1 = args[1].(repository.CreatorApplicationStatusTransitionRow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationStatusTransitionRepo_Insert_Call) Return(err error) *MockCreatorApplicationStatusTransitionRepo_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreatorApplicationStatusTransitionRepo_Insert_Call) RunAndReturn(run func(ctx context.Context, row repository.CreatorApplicationStatusTransitionRow) error) *MockCreatorApplicationStatusTransitionRepo_Insert_Call {
	_c.Call.Return(run)
	return _c
}
