// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorApplicationConsentRepo creates a new instance of MockCreatorApplicationConsentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorApplicationConsentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorApplicationConsentRepo {
	mock := &MockCreatorApplicationConsentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorApplicationConsentRepo is an autogenerated mock type for the CreatorApplicationConsentRepo type
type MockCreatorApplicationConsentRepo struct {
	mock.Mock
}

type MockCreatorApplicationConsentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorApplicationConsentRepo) EXPECT() *MockCreatorApplicationConsentRepo_Expecter {
	return &MockCreatorApplicationConsentRepo_Expecter{mock: &_m.Mock}
}

// InsertMany provides a mock function for the type MockCreatorApplicationConsentRepo
func (_mock *MockCreatorApplicationConsentRepo) InsertMany(ctx context.Context, rows []repository.CreatorApplicationConsentRow) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []repository.CreatorApplicationConsentRow) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreatorApplicationConsentRepo_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockCreatorApplicationConsentRepo_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []repository.CreatorApplicationConsentRow
func (_e *MockCreatorApplicationConsentRepo_Expecter) InsertMany(ctx interface{}, rows interface{}) *MockCreatorApplicationConsentRepo_InsertMany_Call {
	return &MockCreatorApplicationConsentRepo_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, rows)}
}

func (_c *MockCreatorApplicationConsentRepo_InsertMany_Call) Run(run func(ctx context.Context, rows []repository.CreatorApplicationConsentRow)) *MockCreatorApplicationConsentRepo_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []repository.CreatorApplicationConsentRow
		if args[1] != nil {
			arg1 = args[1].([]repository.CreatorApplicationConsentRow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationConsentRepo_InsertMany_Call) Return(err error) *MockCreatorApplicationConsentRepo_InsertMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreatorApplicationConsentRepo_InsertMany_Call) RunAndReturn(run func(ctx context.Context, rows []repository.CreatorApplicationConsentRow) error) *MockCreatorApplicationConsentRepo_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}
