// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorApplicationSocialRepo creates a new instance of MockCreatorApplicationSocialRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorApplicationSocialRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorApplicationSocialRepo {
	mock := &MockCreatorApplicationSocialRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorApplicationSocialRepo is an autogenerated mock type for the CreatorApplicationSocialRepo type
type MockCreatorApplicationSocialRepo struct {
	mock.Mock
}

type MockCreatorApplicationSocialRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorApplicationSocialRepo) EXPECT() *MockCreatorApplicationSocialRepo_Expecter {
	return &MockCreatorApplicationSocialRepo_Expecter{mock: &_m.Mock}
}

// InsertMany provides a mock function for the type MockCreatorApplicationSocialRepo
func (_mock *MockCreatorApplicationSocialRepo) InsertMany(ctx context.Context, rows []repository.CreatorApplicationSocialRow) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []repository.CreatorApplicationSocialRow) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreatorApplicationSocialRepo_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockCreatorApplicationSocialRepo_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []repository.CreatorApplicationSocialRow
func (_e *MockCreatorApplicationSocialRepo_Expecter) InsertMany(ctx interface{}, rows interface{}) *MockCreatorApplicationSocialRepo_InsertMany_Call {
	return &MockCreatorApplicationSocialRepo_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, rows)}
}

func (_c *MockCreatorApplicationSocialRepo_InsertMany_Call) Run(run func(ctx context.Context, rows []repository.CreatorApplicationSocialRow)) *MockCreatorApplicationSocialRepo_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []repository.CreatorApplicationSocialRow
		if args[1] != nil {
			arg1 = args[1].([]repository.CreatorApplicationSocialRow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationSocialRepo_InsertMany_Call) Return(err error) *MockCreatorApplicationSocialRepo_InsertMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreatorApplicationSocialRepo_InsertMany_Call) RunAndReturn(run func(ctx context.Context, rows []repository.CreatorApplicationSocialRow) error) *MockCreatorApplicationSocialRepo_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// ListByApplicationID provides a mock function for the type MockCreatorApplicationSocialRepo
func (_mock *MockCreatorApplicationSocialRepo) ListByApplicationID(ctx context.Context, applicationID string) ([]*repository.CreatorApplicationSocialRow, error) {
	ret := _mock.Called(ctx, applicationID)

	if len(ret) == 0 {
		panic("no return value specified for ListByApplicationID")
	}

	var r0 []*repository.CreatorApplicationSocialRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*repository.CreatorApplicationSocialRow, error)); ok {
		return returnFunc(ctx, applicationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*repository.CreatorApplicationSocialRow); ok {
		r0 = returnFunc(ctx, applicationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.CreatorApplicationSocialRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, applicationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatorApplicationSocialRepo_ListByApplicationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByApplicationID'
type MockCreatorApplicationSocialRepo_ListByApplicationID_Call struct {
	*mock.Call
}

// ListByApplicationID is a helper method to define mock.On call
//   - ctx context.Context
//   - applicationID string
func (_e *MockCreatorApplicationSocialRepo_Expecter) ListByApplicationID(ctx interface{}, applicationID interface{}) *MockCreatorApplicationSocialRepo_ListByApplicationID_Call {
	return &MockCreatorApplicationSocialRepo_ListByApplicationID_Call{Call: _e.mock.On("ListByApplicationID", ctx, applicationID)}
}

func (_c *MockCreatorApplicationSocialRepo_ListByApplicationID_Call) Run(run func(ctx context.Context, applicationID string)) *MockCreatorApplicationSocialRepo_ListByApplicationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationSocialRepo_ListByApplicationID_Call) Return(creatorApplicationSocialRows []*repository.CreatorApplicationSocialRow, err error) *MockCreatorApplicationSocialRepo_ListByApplicationID_Call {
	_c.Call.Return(creatorApplicationSocialRows, err)
	return _c
}

func (_c *MockCreatorApplicationSocialRepo_ListByApplicationID_Call) RunAndReturn(run func(ctx context.Context, applicationID string) ([]*repository.CreatorApplicationSocialRow, error)) *MockCreatorApplicationSocialRepo_ListByApplicationID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByApplicationIDs provides a mock function for the type MockCreatorApplicationSocialRepo
func (_mock *MockCreatorApplicationSocialRepo) ListByApplicationIDs(ctx context.Context, applicationIDs []string) (map[string][]*repository.CreatorApplicationSocialRow, error) {
	ret := _mock.Called(ctx, applicationIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListByApplicationIDs")
	}

	var r0 map[string][]*repository.CreatorApplicationSocialRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string][]*repository.CreatorApplicationSocialRow, error)); ok {
		return returnFunc(ctx, applicationIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string][]*repository.CreatorApplicationSocialRow); ok {
		r0 = returnFunc(ctx, applicationIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]*repository.CreatorApplicationSocialRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, applicationIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByApplicationIDs'
type MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call struct {
	*mock.Call
}

// ListByApplicationIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - applicationIDs []string
func (_e *MockCreatorApplicationSocialRepo_Expecter) ListByApplicationIDs(ctx interface{}, applicationIDs interface{}) *MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call {
	return &MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call{Call: _e.mock.On("ListByApplicationIDs", ctx, applicationIDs)}
}

func (_c *MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call) Run(run func(ctx context.Context, applicationIDs []string)) *MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call) Return(stringToCreatorApplicationSocialRows map[string][]*repository.CreatorApplicationSocialRow, err error) *MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call {
	_c.Call.Return(stringToCreatorApplicationSocialRows, err)
	return _c
}

func (_c *MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call) RunAndReturn(run func(ctx context.Context, applicationIDs []string) (map[string][]*repository.CreatorApplicationSocialRow, error)) *MockCreatorApplicationSocialRepo_ListByApplicationIDs_Call {
	_c.Call.Return(run)
	return _c
}
