// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorApplicationRepo creates a new instance of MockCreatorApplicationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorApplicationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorApplicationRepo {
	mock := &MockCreatorApplicationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorApplicationRepo is an autogenerated mock type for the CreatorApplicationRepo type
type MockCreatorApplicationRepo struct {
	mock.Mock
}

type MockCreatorApplicationRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorApplicationRepo) EXPECT() *MockCreatorApplicationRepo_Expecter {
	return &MockCreatorApplicationRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCreatorApplicationRepo
func (_mock *MockCreatorApplicationRepo) Create(ctx context.Context, row repository.CreatorApplicationRow) (*repository.CreatorApplicationRow, error) {
	ret := _mock.Called(ctx, row)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.CreatorApplicationRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreatorApplicationRow) (*repository.CreatorApplicationRow, error)); ok {
		return returnFunc(ctx, row)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreatorApplicationRow) *repository.CreatorApplicationRow); ok {
		r0 = returnFunc(ctx, row)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CreatorApplicationRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreatorApplicationRow) error); ok {
		r1 = returnFunc(ctx, row)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatorApplicationRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCreatorApplicationRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - row repository.CreatorApplicationRow
func (_e *MockCreatorApplicationRepo_Expecter) Create(ctx interface{}, row interface{}) *MockCreatorApplicationRepo_Create_Call {
	return &MockCreatorApplicationRepo_Create_Call{Call: _e.mock.On("Create", ctx, row)}
}

func (_c *MockCreatorApplicationRepo_Create_Call) Run(run func(ctx context.Context, row repository.CreatorApplicationRow)) *MockCreatorApplicationRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreatorApplicationRow
		if args[1] != nil {
			arg1 = args[1].(repository.CreatorApplicationRow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationRepo_Create_Call) Return(creatorApplicationRow *repository.CreatorApplicationRow, err error) *MockCreatorApplicationRepo_Create_Call {
	_c.Call.Return(creatorApplicationRow, err)
	return _c
}

func (_c *MockCreatorApplicationRepo_Create_Call) RunAndReturn(run func(ctx context.Context, row repository.CreatorApplicationRow) (*repository.CreatorApplicationRow, error)) *MockCreatorApplicationRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteForTests provides a mock function for the type MockCreatorApplicationRepo
func (_mock *MockCreatorApplicationRepo) DeleteForTests(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteForTests")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreatorApplicationRepo_DeleteForTests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteForTests'
type MockCreatorApplicationRepo_DeleteForTests_Call struct {
	*mock.Call
}

// DeleteForTests is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCreatorApplicationRepo_Expecter) DeleteForTests(ctx interface{}, id interface{}) *MockCreatorApplicationRepo_DeleteForTests_Call {
	return &MockCreatorApplicationRepo_DeleteForTests_Call{Call: _e.mock.On("DeleteForTests", ctx, id)}
}

func (_c *MockCreatorApplicationRepo_DeleteForTests_Call) Run(run func(ctx context.Context, id string)) *MockCreatorApplicationRepo_DeleteForTests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationRepo_DeleteForTests_Call) Return(err error) *MockCreatorApplicationRepo_DeleteForTests_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreatorApplicationRepo_DeleteForTests_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockCreatorApplicationRepo_DeleteForTests_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCreatorApplicationRepo
func (_mock *MockCreatorApplicationRepo) GetByID(ctx context.Context, id string) (*repository.CreatorApplicationRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *repository.CreatorApplicationRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.CreatorApplicationRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.CreatorApplicationRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CreatorApplicationRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatorApplicationRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCreatorApplicationRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCreatorApplicationRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockCreatorApplicationRepo_GetByID_Call {
	return &MockCreatorApplicationRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCreatorApplicationRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockCreatorApplicationRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationRepo_GetByID_Call) Return(creatorApplicationRow *repository.CreatorApplicationRow, err error) *MockCreatorApplicationRepo_GetByID_Call {
	_c.Call.Return(creatorApplicationRow, err)
	return _c
}

func (_c *MockCreatorApplicationRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*repository.CreatorApplicationRow, error)) *MockCreatorApplicationRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasActiveByIIN provides a mock function for the type MockCreatorApplicationRepo
func (_mock *MockCreatorApplicationRepo) HasActiveByIIN(ctx context.Context, iin string) (bool, error) {
	ret := _mock.Called(ctx, iin)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveByIIN")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, iin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, iin)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, iin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatorApplicationRepo_HasActiveByIIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActiveByIIN'
type MockCreatorApplicationRepo_HasActiveByIIN_Call struct {
	*mock.Call
}

// HasActiveByIIN is a helper method to define mock.On call
//   - ctx context.Context
//   - iin string
func (_e *MockCreatorApplicationRepo_Expecter) HasActiveByIIN(ctx interface{}, iin interface{}) *MockCreatorApplicationRepo_HasActiveByIIN_Call {
	return &MockCreatorApplicationRepo_HasActiveByIIN_Call{Call: _e.mock.On("HasActiveByIIN", ctx, iin)}
}

func (_c *MockCreatorApplicationRepo_HasActiveByIIN_Call) Run(run func(ctx context.Context, iin string)) *MockCreatorApplicationRepo_HasActiveByIIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorApplicationRepo_HasActiveByIIN_Call) Return(b bool, err error) *MockCreatorApplicationRepo_HasActiveByIIN_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCreatorApplicationRepo_HasActiveByIIN_Call) RunAndReturn(run func(ctx context.Context, iin string) (bool, error)) *MockCreatorApplicationRepo_HasActiveByIIN_Call {
	_c.Call.Return(run)
	return _c
}
