// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrandRepo creates a new instance of MockBrandRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrandRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrandRepo {
	mock := &MockBrandRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrandRepo is an autogenerated mock type for the BrandRepo type
type MockBrandRepo struct {
	mock.Mock
}

type MockBrandRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrandRepo) EXPECT() *MockBrandRepo_Expecter {
	return &MockBrandRepo_Expecter{mock: &_m.Mock}
}

// AssignManager provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) AssignManager(ctx context.Context, brandID string, userID string) error {
	ret := _mock.Called(ctx, brandID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, brandID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrandRepo_AssignManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignManager'
type MockBrandRepo_AssignManager_Call struct {
	*mock.Call
}

// AssignManager is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
//   - userID string
func (_e *MockBrandRepo_Expecter) AssignManager(ctx interface{}, brandID interface{}, userID interface{}) *MockBrandRepo_AssignManager_Call {
	return &MockBrandRepo_AssignManager_Call{Call: _e.mock.On("AssignManager", ctx, brandID, userID)}
}

func (_c *MockBrandRepo_AssignManager_Call) Run(run func(ctx context.Context, brandID string, userID string)) *MockBrandRepo_AssignManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrandRepo_AssignManager_Call) Return(err error) *MockBrandRepo_AssignManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrandRepo_AssignManager_Call) RunAndReturn(run func(ctx context.Context, brandID string, userID string) error) *MockBrandRepo_AssignManager_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) Create(ctx context.Context, name string, logoURL *string) (*repository.BrandRow, error) {
	ret := _mock.Called(ctx, name, logoURL)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.BrandRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) (*repository.BrandRow, error)); ok {
		return returnFunc(ctx, name, logoURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) *repository.BrandRow); ok {
		r0 = returnFunc(ctx, name, logoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.BrandRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = returnFunc(ctx, name, logoURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBrandRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - logoURL *string
func (_e *MockBrandRepo_Expecter) Create(ctx interface{}, name interface{}, logoURL interface{}) *MockBrandRepo_Create_Call {
	return &MockBrandRepo_Create_Call{Call: _e.mock.On("Create", ctx, name, logoURL)}
}

func (_c *MockBrandRepo_Create_Call) Run(run func(ctx context.Context, name string, logoURL *string)) *MockBrandRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrandRepo_Create_Call) Return(brandRow *repository.BrandRow, err error) *MockBrandRepo_Create_Call {
	_c.Call.Return(brandRow, err)
	return _c
}

func (_c *MockBrandRepo_Create_Call) RunAndReturn(run func(ctx context.Context, name string, logoURL *string) (*repository.BrandRow, error)) *MockBrandRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrandRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBrandRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBrandRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockBrandRepo_Delete_Call {
	return &MockBrandRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBrandRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockBrandRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrandRepo_Delete_Call) Return(err error) *MockBrandRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrandRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockBrandRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetBrandIDsForUser provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) GetBrandIDsForUser(ctx context.Context, userID string) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBrandIDsForUser")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_GetBrandIDsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBrandIDsForUser'
type MockBrandRepo_GetBrandIDsForUser_Call struct {
	*mock.Call
}

// GetBrandIDsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBrandRepo_Expecter) GetBrandIDsForUser(ctx interface{}, userID interface{}) *MockBrandRepo_GetBrandIDsForUser_Call {
	return &MockBrandRepo_GetBrandIDsForUser_Call{Call: _e.mock.On("GetBrandIDsForUser", ctx, userID)}
}

func (_c *MockBrandRepo_GetBrandIDsForUser_Call) Run(run func(ctx context.Context, userID string)) *MockBrandRepo_GetBrandIDsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrandRepo_GetBrandIDsForUser_Call) Return(strings []string, err error) *MockBrandRepo_GetBrandIDsForUser_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockBrandRepo_GetBrandIDsForUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]string, error)) *MockBrandRepo_GetBrandIDsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) GetByID(ctx context.Context, id string) (*repository.BrandRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *repository.BrandRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.BrandRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.BrandRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.BrandRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBrandRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBrandRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockBrandRepo_GetByID_Call {
	return &MockBrandRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBrandRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockBrandRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrandRepo_GetByID_Call) Return(brandRow *repository.BrandRow, err error) *MockBrandRepo_GetByID_Call {
	_c.Call.Return(brandRow, err)
	return _c
}

func (_c *MockBrandRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*repository.BrandRow, error)) *MockBrandRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsManager provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) IsManager(ctx context.Context, userID string, brandID string) (bool, error) {
	ret := _mock.Called(ctx, userID, brandID)

	if len(ret) == 0 {
		panic("no return value specified for IsManager")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, brandID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, brandID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, brandID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_IsManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsManager'
type MockBrandRepo_IsManager_Call struct {
	*mock.Call
}

// IsManager is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - brandID string
func (_e *MockBrandRepo_Expecter) IsManager(ctx interface{}, userID interface{}, brandID interface{}) *MockBrandRepo_IsManager_Call {
	return &MockBrandRepo_IsManager_Call{Call: _e.mock.On("IsManager", ctx, userID, brandID)}
}

func (_c *MockBrandRepo_IsManager_Call) Run(run func(ctx context.Context, userID string, brandID string)) *MockBrandRepo_IsManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrandRepo_IsManager_Call) Return(b bool, err error) *MockBrandRepo_IsManager_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBrandRepo_IsManager_Call) RunAndReturn(run func(ctx context.Context, userID string, brandID string) (bool, error)) *MockBrandRepo_IsManager_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) List(ctx context.Context) ([]*repository.BrandWithManagerCount, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*repository.BrandWithManagerCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*repository.BrandWithManagerCount, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*repository.BrandWithManagerCount); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.BrandWithManagerCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBrandRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBrandRepo_Expecter) List(ctx interface{}) *MockBrandRepo_List_Call {
	return &MockBrandRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockBrandRepo_List_Call) Run(run func(ctx context.Context)) *MockBrandRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBrandRepo_List_Call) Return(brandWithManagerCounts []*repository.BrandWithManagerCount, err error) *MockBrandRepo_List_Call {
	_c.Call.Return(brandWithManagerCounts, err)
	return _c
}

func (_c *MockBrandRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]*repository.BrandWithManagerCount, error)) *MockBrandRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) ListByUser(ctx context.Context, userID string) ([]*repository.BrandWithManagerCount, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*repository.BrandWithManagerCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*repository.BrandWithManagerCount, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*repository.BrandWithManagerCount); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.BrandWithManagerCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockBrandRepo_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBrandRepo_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockBrandRepo_ListByUser_Call {
	return &MockBrandRepo_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockBrandRepo_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockBrandRepo_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrandRepo_ListByUser_Call) Return(brandWithManagerCounts []*repository.BrandWithManagerCount, err error) *MockBrandRepo_ListByUser_Call {
	_c.Call.Return(brandWithManagerCounts, err)
	return _c
}

func (_c *MockBrandRepo_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*repository.BrandWithManagerCount, error)) *MockBrandRepo_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListManagers provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) ListManagers(ctx context.Context, brandID string) ([]*repository.BrandManagerRow, error) {
	ret := _mock.Called(ctx, brandID)

	if len(ret) == 0 {
		panic("no return value specified for ListManagers")
	}

	var r0 []*repository.BrandManagerRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*repository.BrandManagerRow, error)); ok {
		return returnFunc(ctx, brandID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*repository.BrandManagerRow); ok {
		r0 = returnFunc(ctx, brandID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.BrandManagerRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, brandID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_ListManagers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManagers'
type MockBrandRepo_ListManagers_Call struct {
	*mock.Call
}

// ListManagers is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
func (_e *MockBrandRepo_Expecter) ListManagers(ctx interface{}, brandID interface{}) *MockBrandRepo_ListManagers_Call {
	return &MockBrandRepo_ListManagers_Call{Call: _e.mock.On("ListManagers", ctx, brandID)}
}

func (_c *MockBrandRepo_ListManagers_Call) Run(run func(ctx context.Context, brandID string)) *MockBrandRepo_ListManagers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrandRepo_ListManagers_Call) Return(brandManagerRows []*repository.BrandManagerRow, err error) *MockBrandRepo_ListManagers_Call {
	_c.Call.Return(brandManagerRows, err)
	return _c
}

func (_c *MockBrandRepo_ListManagers_Call) RunAndReturn(run func(ctx context.Context, brandID string) ([]*repository.BrandManagerRow, error)) *MockBrandRepo_ListManagers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveManager provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) RemoveManager(ctx context.Context, brandID string, userID string) error {
	ret := _mock.Called(ctx, brandID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, brandID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrandRepo_RemoveManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveManager'
type MockBrandRepo_RemoveManager_Call struct {
	*mock.Call
}

// RemoveManager is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID string
//   - userID string
func (_e *MockBrandRepo_Expecter) RemoveManager(ctx interface{}, brandID interface{}, userID interface{}) *MockBrandRepo_RemoveManager_Call {
	return &MockBrandRepo_RemoveManager_Call{Call: _e.mock.On("RemoveManager", ctx, brandID, userID)}
}

func (_c *MockBrandRepo_RemoveManager_Call) Run(run func(ctx context.Context, brandID string, userID string)) *MockBrandRepo_RemoveManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrandRepo_RemoveManager_Call) Return(err error) *MockBrandRepo_RemoveManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrandRepo_RemoveManager_Call) RunAndReturn(run func(ctx context.Context, brandID string, userID string) error) *MockBrandRepo_RemoveManager_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBrandRepo
func (_mock *MockBrandRepo) Update(ctx context.Context, id string, name string, logoURL *string) (*repository.BrandRow, error) {
	ret := _mock.Called(ctx, id, name, logoURL)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.BrandRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) (*repository.BrandRow, error)); ok {
		return returnFunc(ctx, id, name, logoURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) *repository.BrandRow); ok {
		r0 = returnFunc(ctx, id, name, logoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.BrandRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = returnFunc(ctx, id, name, logoURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBrandRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - logoURL *string
func (_e *MockBrandRepo_Expecter) Update(ctx interface{}, id interface{}, name interface{}, logoURL interface{}) *MockBrandRepo_Update_Call {
	return &MockBrandRepo_Update_Call{Call: _e.mock.On("Update", ctx, id, name, logoURL)}
}

func (_c *MockBrandRepo_Update_Call) Run(run func(ctx context.Context, id string, name string, logoURL *string)) *MockBrandRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBrandRepo_Update_Call) Return(brandRow *repository.BrandRow, err error) *MockBrandRepo_Update_Call {
	_c.Call.Return(brandRow, err)
	return _c
}

func (_c *MockBrandRepo_Update_Call) RunAndReturn(run func(ctx context.Context, id string, name string, logoURL *string) (*repository.BrandRow, error)) *MockBrandRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}
