/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using refresh token cookie */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and invalidate refresh token
         * @description Public endpoint — identity is derived from the refresh-token cookie, not
         *     from the bearer access token. Allows a client whose access token has
         *     expired to still revoke its session. The Set-Cookie clear is
         *     unconditional (idempotent for clients without a session).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset token */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with a valid token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List brands (admin sees all, manager sees own) */
        get: operations["listBrands"];
        put?: never;
        /** Create a new brand */
        post: operations["createBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
            };
            cookie?: never;
        };
        /** Get brand details with managers */
        get: operations["getBrand"];
        /** Update brand */
        put: operations["updateBrand"];
        post?: never;
        /** Delete brand */
        delete: operations["deleteBrand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandID}/managers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign manager to brand */
        post: operations["assignManager"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit logs (admin only) */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandID}/managers/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
                userID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove manager from brand */
        delete: operations["removeManager"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entries for a public dictionary (categories, cities)
         * @description Returns the active entries of the requested dictionary, sorted by
         *     sort_order then code. Used by the public landing page to render the
         *     category and city pickers. Public endpoint (no authentication).
         */
        get: operations["listDictionary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a creator application from the public landing page
         * @description Public endpoint (no authentication). Accepts creator personal data,
         *     social accounts, selected categories and four mandatory consents, then
         *     atomically stores the application, its related rows and an audit entry
         *     inside a single DB transaction. Returns the new application id and a
         *     Telegram deep-link the creator must open to bind their TG user to the
         *     application.
         */
        post: operations["submitCreatorApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/applications/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List creator applications with filters, search, sorting and pagination (admin only)
         * @description Admin-only paginated list endpoint backing the moderation UI. POST is
         *     used (not GET) because the search field carries PII (IIN, names, social
         *     handles) which `security.md` forbids in URL params. Authorisation is
         *     evaluated before any business logic so non-admin callers get 403
         *     regardless of whether matching applications exist. Pagination, sort
         *     field and sort order are required — there are no server-side defaults,
         *     the client must explicitly choose. The item shape is intentionally lean:
         *     list-views never expose phone, address, consents or the full Telegram
         *     link aggregate (only a `telegramLinked` boolean) — full PII is reserved
         *     for `GET /creators/applications/{id}`.
         */
        post: operations["listCreatorApplications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/applications/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts of creator applications grouped by status (admin only)
         * @description Admin-only read-only endpoint that returns the number of creator
         *     applications grouped by their current status. Powers the moderation UI
         *     notification badge: clients pick which statuses to sum (default —
         *     verification + moderation + awaiting_contract).
         *
         *     The response is **sparse**: only statuses that currently have at least
         *     one application are present in `items`. Statuses without any rows are
         *     omitted entirely (the frontend should look up its known status with
         *     `find(c => c.status === STATUS_X)?.count ?? 0`). This keeps responses
         *     compact and makes "no applications in this status" semantically explicit.
         *
         *     Authorisation is evaluated before any business logic, so non-admin
         *     callers receive 403 regardless of the underlying counts. No audit log
         *     is written for this read-only call.
         */
        get: operations["getCreatorApplicationsCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get full creator application aggregate (admin only)
         * @description Returns the full aggregate of a creator application: main personal
         *     fields plus linked categories, social accounts and consents. Used by
         *     the moderation UI to review a submitted application. Admin role is
         *     required — non-admin callers receive 403 regardless of whether the
         *     application exists, so the endpoint never leaks application IDs.
         */
        get: operations["getCreatorApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/sendpulse/instagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * SendPulse webhook for Instagram DM verification
         * @description SendPulse-driven Instagram DM verification. Bearer-gated by the
         *     SendPulse middleware. Always returns 200 `{}` past the bearer (incl.
         *     no-op outcomes) and 401 `{}` before — anti-fingerprinting.
         */
        post: operations["sendPulseInstagramWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example dev */
            version: string;
        };
        APIError: {
            /**
             * @description Machine-readable error code (e.g. CREATOR_NOT_FOUND)
             * @example VALIDATION_ERROR
             */
            code: string;
            /**
             * @description Human-readable fallback message (English)
             * @example Invalid input
             */
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["APIError"];
        };
        MessageData: {
            /** @example Operation successful */
            message: string;
        };
        MessageResponse: {
            data: components["schemas"]["MessageData"];
        };
        /**
         * @description Role of an authenticated user.
         * @enum {string}
         */
        UserRole: "admin" | "brand_manager";
        /**
         * @description Canonical consent type captured at creator application submission.
         * @enum {string}
         */
        ConsentType: "processing" | "third_party" | "cross_border" | "terms";
        /**
         * @description Lifecycle status of a creator application. Values follow the state
         *     machine described in `_bmad-output/planning-artifacts/creator-application-state-machine.md`.
         * @enum {string}
         */
        CreatorApplicationStatus: "verification" | "moderation" | "awaiting_contract" | "contract_sent" | "signed" | "rejected" | "withdrawn";
        /** @description Shared 1-based pagination payload for body-paginated list endpoints. */
        PaginationInput: {
            /** @description 1-based page index. */
            page: number;
            /** @description Page size, between 1 and 200 inclusive. */
            perPage: number;
        };
        /**
         * @description Single entry from a public dictionary (categories, cities, etc.).
         *     Reused for the dictionary-listing endpoint and for hydrated dictionary
         *     references on creator-application reads, where the backend falls back
         *     to `(code, code, 0)` when the underlying dictionary row has been
         *     deactivated.
         */
        DictionaryItem: {
            /** @description Stable machine-readable identifier (snake_case). */
            code: string;
            /** @description Human-readable label rendered to the user. */
            name: string;
            /** @description Sort key — lower values appear first in the UI. */
            sortOrder: number;
        };
        DictionaryListResult: {
            data: components["schemas"]["ListDictionaryData"];
        };
        ListDictionaryData: {
            /** @description Dictionary type echoed back to the client. */
            type: string;
            items: components["schemas"]["DictionaryItem"][];
        };
        LoginRequest: {
            /**
             * Format: email
             * @example admin@ugcboost.kz
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        LoginData: {
            accessToken: string;
            user: components["schemas"]["User"];
        };
        LoginResult: {
            data: components["schemas"]["LoginData"];
        };
        PasswordResetRequestBody: {
            /** Format: email */
            email: string;
        };
        PasswordResetBody: {
            token: string;
            newPassword: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        /** @description Mutable subset of a brand — used for create and update. */
        BrandInput: {
            name: string;
            logoUrl?: string;
        };
        Brand: {
            id: string;
            name: string;
            logoUrl?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BrandResult: {
            data: components["schemas"]["Brand"];
        };
        BrandListItem: {
            id: string;
            name: string;
            logoUrl?: string;
            managerCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ListBrandsData: {
            brands: components["schemas"]["BrandListItem"][];
        };
        ListBrandsResult: {
            data: components["schemas"]["ListBrandsData"];
        };
        ManagerInfo: {
            userId: string;
            email: string;
            /** Format: date-time */
            assignedAt: string;
        };
        BrandDetailData: {
            id: string;
            name: string;
            logoUrl?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            managers: components["schemas"]["ManagerInfo"][];
        };
        GetBrandResult: {
            data: components["schemas"]["BrandDetailData"];
        };
        AssignManagerRequest: {
            email: string;
        };
        AssignManagerData: {
            userId: string;
            email: string;
            role: string;
            tempPassword?: string;
        };
        AssignManagerResult: {
            data: components["schemas"]["AssignManagerData"];
        };
        AuditLogEntry: {
            id: string;
            /** @description Null for system / public actions (e.g. public creator application submit). */
            actorId?: string | null;
            actorRole: string;
            action: string;
            entityType: string;
            entityId?: string;
            oldValue?: unknown;
            newValue?: unknown;
            ipAddress: string;
            /** Format: date-time */
            createdAt: string;
        };
        ListAuditLogsData: {
            logs: components["schemas"]["AuditLogEntry"][];
            /** Format: int64 */
            total: number;
            page: number;
            perPage: number;
        };
        AuditLogsResult: {
            data: components["schemas"]["ListAuditLogsData"];
        };
        /**
         * @description Supported social network for creator accounts (MVP scope).
         * @enum {string}
         */
        SocialPlatform: "instagram" | "tiktok" | "threads";
        /**
         * @description How a social account was verified. `auto` — webhook from SendPulse caught
         *     the verification code in an Instagram DM. `manual` — admin marked the
         *     social as verified from the application drawer.
         * @enum {string}
         */
        SocialVerificationMethod: "auto" | "manual";
        SocialAccountInput: {
            platform: components["schemas"]["SocialPlatform"];
            /** @description Account handle or public identifier on the given platform. */
            handle: string;
        };
        CreatorApplicationSubmitRequest: {
            lastName: string;
            firstName: string;
            /** @description Optional patronymic (not every applicant has one). */
            middleName?: string;
            /** @description Kazakhstani individual identification number (12 digits). */
            iin: string;
            phone: string;
            city: string;
            /**
             * @description Optional legal/postal address. Empty on the landing form (the bot
             *     collects it later); admins may patch it via moderation tooling.
             */
            address?: string | null;
            /**
             * @description One or more category codes from the categories catalogue. Must be non-empty.
             *     Maximum three codes; submissions with more are rejected with 422.
             */
            categories: string[];
            /**
             * @description Free-text description of the creator's niche when "other" appears in
             *     categories. Required when "other" is present (otherwise the request is
             *     rejected with 422 VALIDATION_ERROR). Ignored when "other" is absent.
             */
            categoryOtherText?: string | null;
            /** @description One or more social accounts. Multiple handles on the same platform are allowed. */
            socials: components["schemas"]["SocialAccountInput"][];
            /**
             * @description Single consent flag covering all four canonical consent types
             *     (processing / third_party / cross_border / terms). The legal model
             *     (privacy-policy.md §9.2) treats acceptance of the Privacy Policy as
             *     unconditional consent to all four. Backend writes four rows in
             *     creator_application_consents bound to the current document versions.
             *     Must be true; otherwise the request is rejected with 422 MISSING_CONSENT.
             */
            acceptedAll: boolean;
        };
        CreatorApplicationSubmitData: {
            /**
             * Format: uuid
             * @description UUID of the newly created application (also embedded into the bot deep-link).
             */
            applicationId: string;
            /**
             * Format: uri
             * @description Deep-link to the Telegram bot carrying application id as start parameter.
             */
            telegramBotUrl: string;
        };
        CreatorApplicationSubmitResult: {
            data: components["schemas"]["CreatorApplicationSubmitData"];
        };
        CreatorApplicationDetailSocial: {
            platform: components["schemas"]["SocialPlatform"];
            handle: string;
            /** @description Whether the creator's ownership of this social account has been confirmed. */
            verified: boolean;
            /** @description Path used to verify ownership; null while the account is unverified. */
            method?: components["schemas"]["SocialVerificationMethod"];
            /**
             * Format: uuid
             * @description Admin who pressed the manual-verify button. Null on auto and on unverified rows.
             */
            verifiedByUserId?: string | null;
            /**
             * Format: date-time
             * @description When verification succeeded; null while the account is unverified.
             */
            verifiedAt?: string | null;
        };
        CreatorApplicationDetailConsent: {
            consentType: components["schemas"]["ConsentType"];
            /** Format: date-time */
            acceptedAt: string;
            /** @description Document version stamp recorded at the moment of consent. */
            documentVersion: string;
            /** @description Client IP recorded at submission (raw stored as-is). */
            ipAddress: string;
            /** @description Truncated User-Agent recorded at submission. */
            userAgent: string;
        };
        /** @description Telegram account linked to a creator application via /start deep-link. */
        TelegramLink: {
            /**
             * Format: int64
             * @description Telegram numeric user id (BIGINT) — stable identifier of the linked account.
             */
            telegramUserId: number;
            /** @description Telegram @username at link time (no leading @). Nullable. */
            telegramUsername?: string | null;
            /** @description Telegram first_name at link time. Nullable. */
            telegramFirstName?: string | null;
            /** @description Telegram last_name at link time. Nullable. */
            telegramLastName?: string | null;
            /**
             * Format: date-time
             * @description Timestamp of the successful link.
             */
            linkedAt: string;
        };
        CreatorApplicationDetailData: {
            /** Format: uuid */
            id: string;
            /**
             * @description 6-digit `UGC-NNNNNN` code the creator must DM to the official
             *     Instagram for auto-verification. Visible only via this admin
             *     endpoint — never returned by public/landing routes.
             */
            verificationCode: string;
            lastName: string;
            firstName: string;
            middleName?: string | null;
            /** @description Kazakhstani individual identification number (12 digits). */
            iin: string;
            /**
             * Format: date
             * @description Birth date derived from the IIN at submission time.
             */
            birthDate: string;
            phone: string;
            city: components["schemas"]["DictionaryItem"];
            address?: string | null;
            /** @description Free-text niche description when categories include "other". */
            categoryOtherText?: string | null;
            status: components["schemas"]["CreatorApplicationStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Categories selected by the creator, sorted by sort_order then code. */
            categories: components["schemas"]["DictionaryItem"][];
            /** @description Social accounts attached to the application, sorted by platform then handle. */
            socials: components["schemas"]["CreatorApplicationDetailSocial"][];
            /**
             * @description Consents in canonical order (processing → third_party → cross_border → terms),
             *     independent of the order they appear in the database.
             */
            consents: components["schemas"]["CreatorApplicationDetailConsent"][];
            /**
             * @description Telegram account linked to this application. Null when the creator
             *     has not yet opened the bot.
             */
            telegramLink?: components["schemas"]["TelegramLink"] | null;
            /**
             * @description Deep-link in form `https://t.me/{bot}?start={applicationId}`. The
             *     admin shares it with the creator (e.g. via WhatsApp) when
             *     `telegramLink` is null. Always returned regardless of link state so
             *     the response shape stays stable; the frontend renders the copy
             *     action only when not yet bound.
             */
            telegramBotUrl: string;
        };
        GetCreatorApplicationResult: {
            data: components["schemas"]["CreatorApplicationDetailData"];
        };
        /**
         * @description Sort field for the admin list. Mapped to a SQL column / expression on
         *     the backend. Unknown values are rejected with 422.
         * @enum {string}
         */
        CreatorApplicationListSortField: "created_at" | "updated_at" | "full_name" | "birth_date" | "city_name";
        /**
         * @description Sort direction.
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * @description Filter, search, sort and pagination payload for the admin list. All
         *     filter fields are optional and combined with AND between fields, OR
         *     (any-of) within a single array. Empty/whitespace `search` is ignored.
         */
        CreatorApplicationsListRequest: components["schemas"]["PaginationInput"] & {
            /** @description Match any of these statuses. Empty/missing → all statuses. */
            statuses?: components["schemas"]["CreatorApplicationStatus"][];
            /** @description Match any of these city codes (from the cities dictionary). */
            cities?: string[];
            /** @description Match applications that include any of these category codes. */
            categories?: string[];
            /**
             * Format: date-time
             * @description Inclusive lower bound for `created_at`.
             */
            dateFrom?: string;
            /**
             * Format: date-time
             * @description Inclusive upper bound for `created_at`.
             */
            dateTo?: string;
            /** @description Inclusive lower bound for the creator's age in full years (computed from birth_date). */
            ageFrom?: number;
            /** @description Inclusive upper bound for the creator's age in full years. */
            ageTo?: number;
            /**
             * @description When true, only applications already bound to a Telegram account
             *     are returned. When false, only those still without a link.
             *     Missing/null disables the filter.
             */
            telegramLinked?: boolean;
            /**
             * @description Free-text search across last_name, first_name, middle_name, IIN
             *     (case-insensitive) and social-account handles. Trimmed; empty/blank
             *     after trim disables the filter. Carries PII — the endpoint is POST
             *     so this never lands in URL params.
             */
            search?: string;
            sort: components["schemas"]["CreatorApplicationListSortField"];
            order: components["schemas"]["SortOrder"];
        };
        CreatorApplicationListItem: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["CreatorApplicationStatus"];
            lastName: string;
            firstName: string;
            middleName?: string | null;
            /** Format: date */
            birthDate: string;
            city: components["schemas"]["DictionaryItem"];
            /** @description Categories selected by the creator, sorted by sort_order then code. */
            categories: components["schemas"]["DictionaryItem"][];
            /** @description Social accounts attached to the application, sorted by platform then handle. */
            socials: components["schemas"]["CreatorApplicationDetailSocial"][];
            /** @description True when the creator has bound a Telegram account via /start. */
            telegramLinked: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatorApplicationsListData: {
            items: components["schemas"]["CreatorApplicationListItem"][];
            /**
             * Format: int64
             * @description Total number of matching applications across all pages.
             */
            total: number;
            page: number;
            perPage: number;
        };
        CreatorApplicationsListResult: {
            data: components["schemas"]["CreatorApplicationsListData"];
        };
        /** @description Single (status, count) pair returned by GET /creators/applications/counts. */
        CreatorApplicationStatusCount: {
            status: components["schemas"]["CreatorApplicationStatus"];
            /**
             * Format: int64
             * @description Number of creator applications currently in this status.
             */
            count: number;
        };
        /**
         * @description Sparse counts payload — see the operation description on the
         *     `getCreatorApplicationsCounts` endpoint for the contract details.
         *     `items` is alphabetically sorted by `status` for deterministic output.
         */
        CreatorApplicationsCountsData: {
            /** @description Sparse list — only statuses with at least one application appear here. */
            items: components["schemas"]["CreatorApplicationStatusCount"][];
        };
        CreatorApplicationsCountsResult: {
            data: components["schemas"]["CreatorApplicationsCountsData"];
        };
        /**
         * @description Custom JSON payload SendPulse delivers from the Instagram chatbot.
         *     `username` and `lastMessage` come from the configured "send custom
         *     data" action; `contactId` is SendPulse's opaque contact identifier
         *     kept for trace correlation.
         */
        SendPulseInstagramWebhookRequest: {
            /** @description Instagram handle of the message sender as SendPulse received it. */
            username: string;
            /** @description Body of the last message in the IG DM thread. */
            lastMessage: string;
            /** @description Optional SendPulse contact id; opaque to backend, kept for correlation. */
            contactId?: string;
        };
        /**
         * @description Empty object — the SendPulse webhook never carries data back. Both
         *     success (200) and the constant-time auth failure (401) emit the
         *     same `{}` body.
         */
        SendPulseInstagramWebhookResult: Record<string, never>;
    };
    responses: {
        /** @description Unexpected error */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 1-based page index. */
        PageQueryParam: number;
        /** @description Page size, between 1 and 200 inclusive. */
        PerPageQueryParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    /** @description httpOnly refresh token cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    /** @description Rotated refresh token cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    /** @description Cleared refresh token cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestBody"];
            };
        };
        responses: {
            /** @description Reset token generated (always 200 to prevent email enumeration) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetBody"];
            };
        };
        responses: {
            /** @description Password updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    listBrands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of brands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBrandsResult"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    createBrand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandInput"];
            };
        };
        responses: {
            /** @description Brand created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResult"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    getBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetBrandResult"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    updateBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandInput"];
            };
        };
        responses: {
            /** @description Brand updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResult"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    deleteBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    assignManager: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignManagerRequest"];
            };
        };
        responses: {
            /** @description Manager assigned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignManagerResult"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                actorId?: string;
                entityType?: string;
                entityId?: string;
                action?: string;
                dateFrom?: string;
                dateTo?: string;
                /** @description 1-based page index. */
                page?: components["parameters"]["PageQueryParam"];
                /** @description Page size, between 1 and 200 inclusive. */
                perPage?: components["parameters"]["PerPageQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogsResult"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    removeManager: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandID: string;
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manager removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    listDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dictionary type to list. */
                type: "categories" | "cities";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dictionary entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryListResult"];
                };
            };
            /** @description Unknown dictionary type */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    submitCreatorApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatorApplicationSubmitRequest"];
            };
        };
        responses: {
            /** @description Application accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorApplicationSubmitResult"];
                };
            };
            /** @description Active application for this IIN already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    listCreatorApplications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatorApplicationsListRequest"];
            };
        };
        responses: {
            /** @description Page of creator applications matching the filter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorApplicationsListResult"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Validation error (unknown sort/order, page/perPage out of range, missing required field) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    getCreatorApplicationsCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sparse list of (status, count) pairs, alphabetically sorted by status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorApplicationsCountsResult"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    getCreatorApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application aggregate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCreatorApplicationResult"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    sendPulseInstagramWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendPulseInstagramWebhookRequest"];
            };
        };
        responses: {
            /** @description Webhook processed (always — including no-op cases). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendPulseInstagramWebhookResult"];
                };
            };
            /** @description Wrong or missing bearer secret. Body is empty — no fingerprinting. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendPulseInstagramWebhookResult"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
}
