/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/test/seed-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a test user with given credentials and role */
        post: operations["seedUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/reset-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the raw reset token captured for the given email */
        get: operations["getResetToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/cleanup-entity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hard-delete a test entity (user or brand) and its references
         * @description Test-only cleanup endpoint used by the e2e cleanup stack when no
         *     business delete exists. For users this is a destructive hard delete
         *     that also wipes audit_logs, brand_managers, refresh_tokens and
         *     password_reset_tokens. For brands it forwards to the regular brand
         *     delete. NEVER enabled in production.
         */
        post: operations["cleanupEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/telegram/sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read recorded outbound Telegram messages
         * @description Returns SentRecord rows captured by the in-process spy store every
         *     time the backend's Telegram Sender is invoked. Filter by chatId
         *     (always required to keep parallel e2e isolated) and optionally
         *     by `since` to bound the lookup. NEVER enabled in production.
         */
        get: operations["getTelegramSent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/telegram/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject a synthetic text message into the Telegram handler
         * @description Builds a minimal Telegram Update from the request body, invokes the
         *     in-process Telegram handler with a spy Sender, and returns whatever
         *     replies the handler produced. No network calls — the real long-polling
         *     client is bypassed entirely. NEVER enabled in production.
         */
        post: operations["sendTelegramMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/telegram/spy/fake-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark chatId as test-synthetic so TeeSender skips the real bot
         * @description Registers chatId in the spy store's fake-chat set. Subsequent
         *     SendMessage calls to that chat_id are recorded with success
         *     without involving the upstream Telegram bot. Needed by chunk-12
         *     e2e: synthetic creator chat_ids have no live chat for staging
         *     Telegram, so without this stub TeeSender would always return
         *     "Bad Request: chat not found" and `undelivered` could never be
         *     empty. NEVER enabled in production.
         */
        post: operations["telegramSpyFakeChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/tma/sign-init-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a valid Telegram WebApp initData payload for tests
         * @description Returns an `init_data` query string signed with the same HMAC the
         *     production middleware verifies. e2e suites paste the value into
         *     `Authorization: tma <init-data>` to exercise /tma/* endpoints
         *     without driving a real Telegram WebApp client. NEVER enabled in
         *     production.
         */
        post: operations["signTMAInitData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/telegram/spy/fail-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force the next outbound bot send to chatId to fail
         * @description Registers a one-shot synthetic failure for the chat_id. The next
         *     SendMessage call to that chat_id returns the canonical Telegram
         *     error string ("Forbidden: bot was blocked by the user" by default).
         *     Used by chunk-12 e2e to exercise partial-success delivery without
         *     a real blocked-by-user account. NEVER enabled in production.
         */
        post: operations["telegramSpyFailNext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SeedUserRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "admin" | "brand_manager";
        };
        SeedUserData: {
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "brand_manager";
        };
        SeedUserResult: {
            data: components["schemas"]["SeedUserData"];
        };
        ResetTokenData: {
            token: string;
        };
        ResetTokenResult: {
            data: components["schemas"]["ResetTokenData"];
        };
        CleanupEntityRequest: {
            /** @enum {string} */
            type: "user" | "brand" | "creator_application" | "creator" | "campaign";
            id: string;
        };
        SendTelegramMessageRequest: {
            /**
             * Format: int64
             * @description Synthetic chat id; echoed in the spy reply for assertions.
             */
            chatId: number;
            /** @description Message text the simulated user sends to the bot. */
            text: string;
            /**
             * Format: int64
             * @description Synthetic Telegram user id (defaults to chatId when omitted).
             */
            userId?: number;
            /** @description Optional Telegram @username (no leading @). */
            username?: string | null;
            firstName?: string | null;
            lastName?: string | null;
        };
        TelegramReply: {
            /** Format: int64 */
            chatId: number;
            text: string;
        };
        SendTelegramMessageResult: {
            replies: components["schemas"]["TelegramReply"][];
        };
        TelegramSentMessage: {
            /** Format: int64 */
            chatId: number;
            text: string;
            /**
             * @description URL embedded into the InlineKeyboardMarkup WebApp button when
             *     the sender attached one. Null for plain-text messages.
             */
            webAppUrl?: string | null;
            /** Format: date-time */
            sentAt: string;
            /**
             * @description Empty when the real upstream Telegram send succeeded (or when
             *     running under the spy-only sender, which never errs); populated
             *     with the upstream error string in TeeSender mode.
             */
            error?: string | null;
        };
        TelegramSentData: {
            messages: components["schemas"]["TelegramSentMessage"][];
        };
        TelegramSentResult: {
            data: components["schemas"]["TelegramSentData"];
        };
        TelegramSpyFailNextRequest: {
            /**
             * Format: int64
             * @description Chat id whose next SendMessage call should fail.
             */
            chatId: number;
            /**
             * @description Optional override for the error string the spy returns. Defaults
             *     to "Forbidden: bot was blocked by the user" so MapTelegramErrorToReason
             *     classifies it as bot_blocked.
             */
            reason?: string;
        };
        SignTMAInitDataRequest: {
            /**
             * Format: int64
             * @description Telegram user id to sign on behalf of.
             */
            telegramUserId: number;
            /**
             * Format: int64
             * @description Optional Unix timestamp (seconds). Defaults to "now" — used by
             *     tests that want to exercise expired / future-dated init_data
             *     paths.
             */
            authDate?: number;
        };
        SignTMAInitDataData: {
            /**
             * @description Signed query-string ready to be passed in
             *     `Authorization: tma <init-data>`.
             */
            initData: string;
        };
        SignTMAInitDataResult: {
            data: components["schemas"]["SignTMAInitDataData"];
        };
        TelegramSpyFakeChatRequest: {
            /**
             * Format: int64
             * @description Chat id to register as test-synthetic.
             */
            chatId: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    seedUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedUserResult"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getResetToken: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetTokenResult"];
                };
            };
            /** @description No token found for this email */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cleanupEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupEntityRequest"];
            };
        };
        responses: {
            /** @description Entity deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTelegramSent: {
        parameters: {
            query: {
                /** @description Telegram chat id (== TG user id for private DMs). */
                chatId: number;
                /** @description Only records sent at or after this timestamp. */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recorded messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramSentResult"];
                };
            };
        };
    };
    sendTelegramMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendTelegramMessageRequest"];
            };
        };
        responses: {
            /** @description Replies captured by the spy Sender */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendTelegramMessageResult"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    telegramSpyFakeChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramSpyFakeChatRequest"];
            };
        };
        responses: {
            /** @description Fake chat registered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    signTMAInitData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignTMAInitDataRequest"];
            };
        };
        responses: {
            /** @description Signed initData payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignTMAInitDataResult"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    telegramSpyFailNext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramSpyFailNextRequest"];
            };
        };
        responses: {
            /** @description Failure registered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
