// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOutboxRunner creates a new instance of MockOutboxRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRunner {
	mock := &MockOutboxRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutboxRunner is an autogenerated mock type for the OutboxRunner type
type MockOutboxRunner struct {
	mock.Mock
}

type MockOutboxRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRunner) EXPECT() *MockOutboxRunner_Expecter {
	return &MockOutboxRunner_Expecter{mock: &_m.Mock}
}

// RunOnce provides a mock function for the type MockOutboxRunner
func (_mock *MockOutboxRunner) RunOnce(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockOutboxRunner_RunOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOnce'
type MockOutboxRunner_RunOnce_Call struct {
	*mock.Call
}

// RunOnce is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOutboxRunner_Expecter) RunOnce(ctx interface{}) *MockOutboxRunner_RunOnce_Call {
	return &MockOutboxRunner_RunOnce_Call{Call: _e.mock.On("RunOnce", ctx)}
}

func (_c *MockOutboxRunner_RunOnce_Call) Run(run func(ctx context.Context)) *MockOutboxRunner_RunOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOutboxRunner_RunOnce_Call) Return() *MockOutboxRunner_RunOnce_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOutboxRunner_RunOnce_Call) RunAndReturn(run func(ctx context.Context)) *MockOutboxRunner_RunOnce_Call {
	_c.Run(run)
	return _c
}
