// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/handler/trustmeport"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSpyStore creates a new instance of MockSpyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpyStore {
	mock := &MockSpyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpyStore is an autogenerated mock type for the SpyStore type
type MockSpyStore struct {
	mock.Mock
}

type MockSpyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpyStore) EXPECT() *MockSpyStore_Expecter {
	return &MockSpyStore_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockSpyStore
func (_mock *MockSpyStore) Clear() {
	_mock.Called()
	return
}

// MockSpyStore_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockSpyStore_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockSpyStore_Expecter) Clear() *MockSpyStore_Clear_Call {
	return &MockSpyStore_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockSpyStore_Clear_Call) Run(run func()) *MockSpyStore_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSpyStore_Clear_Call) Return() *MockSpyStore_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSpyStore_Clear_Call) RunAndReturn(run func()) *MockSpyStore_Clear_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function for the type MockSpyStore
func (_mock *MockSpyStore) List() []trustmeport.SentRecord {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []trustmeport.SentRecord
	if returnFunc, ok := ret.Get(0).(func() []trustmeport.SentRecord); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trustmeport.SentRecord)
		}
	}
	return r0
}

// MockSpyStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSpyStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockSpyStore_Expecter) List() *MockSpyStore_List_Call {
	return &MockSpyStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockSpyStore_List_Call) Run(run func()) *MockSpyStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSpyStore_List_Call) Return(sentRecords []trustmeport.SentRecord) *MockSpyStore_List_Call {
	_c.Call.Return(sentRecords)
	return _c
}

func (_c *MockSpyStore_List_Call) RunAndReturn(run func() []trustmeport.SentRecord) *MockSpyStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDocument provides a mock function for the type MockSpyStore
func (_mock *MockSpyStore) RegisterDocument(additionalInfo string, documentID string, shortURL string, contractStatus int) {
	_mock.Called(additionalInfo, documentID, shortURL, contractStatus)
	return
}

// MockSpyStore_RegisterDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDocument'
type MockSpyStore_RegisterDocument_Call struct {
	*mock.Call
}

// RegisterDocument is a helper method to define mock.On call
//   - additionalInfo string
//   - documentID string
//   - shortURL string
//   - contractStatus int
func (_e *MockSpyStore_Expecter) RegisterDocument(additionalInfo interface{}, documentID interface{}, shortURL interface{}, contractStatus interface{}) *MockSpyStore_RegisterDocument_Call {
	return &MockSpyStore_RegisterDocument_Call{Call: _e.mock.On("RegisterDocument", additionalInfo, documentID, shortURL, contractStatus)}
}

func (_c *MockSpyStore_RegisterDocument_Call) Run(run func(additionalInfo string, documentID string, shortURL string, contractStatus int)) *MockSpyStore_RegisterDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSpyStore_RegisterDocument_Call) Return() *MockSpyStore_RegisterDocument_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSpyStore_RegisterDocument_Call) RunAndReturn(run func(additionalInfo string, documentID string, shortURL string, contractStatus int)) *MockSpyStore_RegisterDocument_Call {
	_c.Run(run)
	return _c
}

// RegisterFailNext provides a mock function for the type MockSpyStore
func (_mock *MockSpyStore) RegisterFailNext(additionalInfo string, reason string, count int) {
	_mock.Called(additionalInfo, reason, count)
	return
}

// MockSpyStore_RegisterFailNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFailNext'
type MockSpyStore_RegisterFailNext_Call struct {
	*mock.Call
}

// RegisterFailNext is a helper method to define mock.On call
//   - additionalInfo string
//   - reason string
//   - count int
func (_e *MockSpyStore_Expecter) RegisterFailNext(additionalInfo interface{}, reason interface{}, count interface{}) *MockSpyStore_RegisterFailNext_Call {
	return &MockSpyStore_RegisterFailNext_Call{Call: _e.mock.On("RegisterFailNext", additionalInfo, reason, count)}
}

func (_c *MockSpyStore_RegisterFailNext_Call) Run(run func(additionalInfo string, reason string, count int)) *MockSpyStore_RegisterFailNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSpyStore_RegisterFailNext_Call) Return() *MockSpyStore_RegisterFailNext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSpyStore_RegisterFailNext_Call) RunAndReturn(run func(additionalInfo string, reason string, count int)) *MockSpyStore_RegisterFailNext_Call {
	_c.Run(run)
	return _c
}
