// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBrandAccessChecker creates a new instance of MockBrandAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrandAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrandAccessChecker {
	mock := &MockBrandAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrandAccessChecker is an autogenerated mock type for the BrandAccessChecker type
type MockBrandAccessChecker struct {
	mock.Mock
}

type MockBrandAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrandAccessChecker) EXPECT() *MockBrandAccessChecker_Expecter {
	return &MockBrandAccessChecker_Expecter{mock: &_m.Mock}
}

// IsManager provides a mock function for the type MockBrandAccessChecker
func (_mock *MockBrandAccessChecker) IsManager(ctx context.Context, userID string, brandID string) (bool, error) {
	ret := _mock.Called(ctx, userID, brandID)

	if len(ret) == 0 {
		panic("no return value specified for IsManager")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, brandID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, brandID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, brandID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandAccessChecker_IsManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsManager'
type MockBrandAccessChecker_IsManager_Call struct {
	*mock.Call
}

// IsManager is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - brandID string
func (_e *MockBrandAccessChecker_Expecter) IsManager(ctx interface{}, userID interface{}, brandID interface{}) *MockBrandAccessChecker_IsManager_Call {
	return &MockBrandAccessChecker_IsManager_Call{Call: _e.mock.On("IsManager", ctx, userID, brandID)}
}

func (_c *MockBrandAccessChecker_IsManager_Call) Run(run func(ctx context.Context, userID string, brandID string)) *MockBrandAccessChecker_IsManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrandAccessChecker_IsManager_Call) Return(b bool, err error) *MockBrandAccessChecker_IsManager_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBrandAccessChecker_IsManager_Call) RunAndReturn(run func(ctx context.Context, userID string, brandID string) (bool, error)) *MockBrandAccessChecker_IsManager_Call {
	_c.Call.Return(run)
	return _c
}
