// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorNotifier creates a new instance of MockCreatorNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorNotifier {
	mock := &MockCreatorNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorNotifier is an autogenerated mock type for the CreatorNotifier type
type MockCreatorNotifier struct {
	mock.Mock
}

type MockCreatorNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorNotifier) EXPECT() *MockCreatorNotifier_Expecter {
	return &MockCreatorNotifier_Expecter{mock: &_m.Mock}
}

// NotifyContractSent provides a mock function for the type MockCreatorNotifier
func (_mock *MockCreatorNotifier) NotifyContractSent(ctx context.Context, creatorTelegramUserID int64) {
	_mock.Called(ctx, creatorTelegramUserID)
	return
}

// MockCreatorNotifier_NotifyContractSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyContractSent'
type MockCreatorNotifier_NotifyContractSent_Call struct {
	*mock.Call
}

// NotifyContractSent is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorTelegramUserID int64
func (_e *MockCreatorNotifier_Expecter) NotifyContractSent(ctx interface{}, creatorTelegramUserID interface{}) *MockCreatorNotifier_NotifyContractSent_Call {
	return &MockCreatorNotifier_NotifyContractSent_Call{Call: _e.mock.On("NotifyContractSent", ctx, creatorTelegramUserID)}
}

func (_c *MockCreatorNotifier_NotifyContractSent_Call) Run(run func(ctx context.Context, creatorTelegramUserID int64)) *MockCreatorNotifier_NotifyContractSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorNotifier_NotifyContractSent_Call) Return() *MockCreatorNotifier_NotifyContractSent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCreatorNotifier_NotifyContractSent_Call) RunAndReturn(run func(ctx context.Context, creatorTelegramUserID int64)) *MockCreatorNotifier_NotifyContractSent_Call {
	_c.Run(run)
	return _c
}
