// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/contract"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// ExtractPlaceholders provides a mock function for the type MockExtractor
func (_mock *MockExtractor) ExtractPlaceholders(pdfBytes []byte) ([]contract.Placeholder, error) {
	ret := _mock.Called(pdfBytes)

	if len(ret) == 0 {
		panic("no return value specified for ExtractPlaceholders")
	}

	var r0 []contract.Placeholder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]contract.Placeholder, error)); ok {
		return returnFunc(pdfBytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []contract.Placeholder); ok {
		r0 = returnFunc(pdfBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contract.Placeholder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(pdfBytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExtractor_ExtractPlaceholders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractPlaceholders'
type MockExtractor_ExtractPlaceholders_Call struct {
	*mock.Call
}

// ExtractPlaceholders is a helper method to define mock.On call
//   - pdfBytes []byte
func (_e *MockExtractor_Expecter) ExtractPlaceholders(pdfBytes interface{}) *MockExtractor_ExtractPlaceholders_Call {
	return &MockExtractor_ExtractPlaceholders_Call{Call: _e.mock.On("ExtractPlaceholders", pdfBytes)}
}

func (_c *MockExtractor_ExtractPlaceholders_Call) Run(run func(pdfBytes []byte)) *MockExtractor_ExtractPlaceholders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExtractor_ExtractPlaceholders_Call) Return(placeholders []contract.Placeholder, err error) *MockExtractor_ExtractPlaceholders_Call {
	_c.Call.Return(placeholders, err)
	return _c
}

func (_c *MockExtractor_ExtractPlaceholders_Call) RunAndReturn(run func(pdfBytes []byte) ([]contract.Placeholder, error)) *MockExtractor_ExtractPlaceholders_Call {
	_c.Call.Return(run)
	return _c
}
