// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alikhanmurzayev/ugcboost/backend/internal/dbutil"
	"github.com/alikhanmurzayev/ugcboost/backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContractSenderRepoFactory creates a new instance of MockContractSenderRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContractSenderRepoFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContractSenderRepoFactory {
	mock := &MockContractSenderRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContractSenderRepoFactory is an autogenerated mock type for the ContractSenderRepoFactory type
type MockContractSenderRepoFactory struct {
	mock.Mock
}

type MockContractSenderRepoFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContractSenderRepoFactory) EXPECT() *MockContractSenderRepoFactory_Expecter {
	return &MockContractSenderRepoFactory_Expecter{mock: &_m.Mock}
}

// NewAuditRepo provides a mock function for the type MockContractSenderRepoFactory
func (_mock *MockContractSenderRepoFactory) NewAuditRepo(db dbutil.DB) repository.AuditRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewAuditRepo")
	}

	var r0 repository.AuditRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.AuditRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AuditRepo)
		}
	}
	return r0
}

// MockContractSenderRepoFactory_NewAuditRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAuditRepo'
type MockContractSenderRepoFactory_NewAuditRepo_Call struct {
	*mock.Call
}

// NewAuditRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockContractSenderRepoFactory_Expecter) NewAuditRepo(db interface{}) *MockContractSenderRepoFactory_NewAuditRepo_Call {
	return &MockContractSenderRepoFactory_NewAuditRepo_Call{Call: _e.mock.On("NewAuditRepo", db)}
}

func (_c *MockContractSenderRepoFactory_NewAuditRepo_Call) Run(run func(db dbutil.DB)) *MockContractSenderRepoFactory_NewAuditRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContractSenderRepoFactory_NewAuditRepo_Call) Return(auditRepo repository.AuditRepo) *MockContractSenderRepoFactory_NewAuditRepo_Call {
	_c.Call.Return(auditRepo)
	return _c
}

func (_c *MockContractSenderRepoFactory_NewAuditRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.AuditRepo) *MockContractSenderRepoFactory_NewAuditRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewCampaignCreatorRepo provides a mock function for the type MockContractSenderRepoFactory
func (_mock *MockContractSenderRepoFactory) NewCampaignCreatorRepo(db dbutil.DB) repository.CampaignCreatorRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewCampaignCreatorRepo")
	}

	var r0 repository.CampaignCreatorRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.CampaignCreatorRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CampaignCreatorRepo)
		}
	}
	return r0
}

// MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCampaignCreatorRepo'
type MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call struct {
	*mock.Call
}

// NewCampaignCreatorRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockContractSenderRepoFactory_Expecter) NewCampaignCreatorRepo(db interface{}) *MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call {
	return &MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call{Call: _e.mock.On("NewCampaignCreatorRepo", db)}
}

func (_c *MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call) Run(run func(db dbutil.DB)) *MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call) Return(campaignCreatorRepo repository.CampaignCreatorRepo) *MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call {
	_c.Call.Return(campaignCreatorRepo)
	return _c
}

func (_c *MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.CampaignCreatorRepo) *MockContractSenderRepoFactory_NewCampaignCreatorRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewContractsRepo provides a mock function for the type MockContractSenderRepoFactory
func (_mock *MockContractSenderRepoFactory) NewContractsRepo(db dbutil.DB) repository.ContractRepo {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for NewContractsRepo")
	}

	var r0 repository.ContractRepo
	if returnFunc, ok := ret.Get(0).(func(dbutil.DB) repository.ContractRepo); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ContractRepo)
		}
	}
	return r0
}

// MockContractSenderRepoFactory_NewContractsRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewContractsRepo'
type MockContractSenderRepoFactory_NewContractsRepo_Call struct {
	*mock.Call
}

// NewContractsRepo is a helper method to define mock.On call
//   - db dbutil.DB
func (_e *MockContractSenderRepoFactory_Expecter) NewContractsRepo(db interface{}) *MockContractSenderRepoFactory_NewContractsRepo_Call {
	return &MockContractSenderRepoFactory_NewContractsRepo_Call{Call: _e.mock.On("NewContractsRepo", db)}
}

func (_c *MockContractSenderRepoFactory_NewContractsRepo_Call) Run(run func(db dbutil.DB)) *MockContractSenderRepoFactory_NewContractsRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dbutil.DB
		if args[0] != nil {
			arg0 = args[0].(dbutil.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContractSenderRepoFactory_NewContractsRepo_Call) Return(contractRepo repository.ContractRepo) *MockContractSenderRepoFactory_NewContractsRepo_Call {
	_c.Call.Return(contractRepo)
	return _c
}

func (_c *MockContractSenderRepoFactory_NewContractsRepo_Call) RunAndReturn(run func(db dbutil.DB) repository.ContractRepo) *MockContractSenderRepoFactory_NewContractsRepo_Call {
	_c.Call.Return(run)
	return _c
}
