// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatorTelegramResolver creates a new instance of MockCreatorTelegramResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatorTelegramResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatorTelegramResolver {
	mock := &MockCreatorTelegramResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatorTelegramResolver is an autogenerated mock type for the CreatorTelegramResolver type
type MockCreatorTelegramResolver struct {
	mock.Mock
}

type MockCreatorTelegramResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatorTelegramResolver) EXPECT() *MockCreatorTelegramResolver_Expecter {
	return &MockCreatorTelegramResolver_Expecter{mock: &_m.Mock}
}

// GetTelegramUserIDsByIDs provides a mock function for the type MockCreatorTelegramResolver
func (_mock *MockCreatorTelegramResolver) GetTelegramUserIDsByIDs(ctx context.Context, ids []string) (map[string]int64, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetTelegramUserIDsByIDs")
	}

	var r0 map[string]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTelegramUserIDsByIDs'
type MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call struct {
	*mock.Call
}

// GetTelegramUserIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockCreatorTelegramResolver_Expecter) GetTelegramUserIDsByIDs(ctx interface{}, ids interface{}) *MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call {
	return &MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call{Call: _e.mock.On("GetTelegramUserIDsByIDs", ctx, ids)}
}

func (_c *MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call) Return(stringToInt64 map[string]int64, err error) *MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call {
	_c.Call.Return(stringToInt64, err)
	return _c
}

func (_c *MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string) (map[string]int64, error)) *MockCreatorTelegramResolver_GetTelegramUserIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}
