// Package testclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package testclient

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SeedUserDataRole.
const (
	SeedUserDataRoleAdmin        SeedUserDataRole = "admin"
	SeedUserDataRoleBrandManager SeedUserDataRole = "brand_manager"
)

// Valid indicates whether the value is a known member of the SeedUserDataRole enum.
func (e SeedUserDataRole) Valid() bool {
	switch e {
	case SeedUserDataRoleAdmin:
		return true
	case SeedUserDataRoleBrandManager:
		return true
	default:
		return false
	}
}

// Defines values for SeedUserRequestRole.
const (
	SeedUserRequestRoleAdmin        SeedUserRequestRole = "admin"
	SeedUserRequestRoleBrandManager SeedUserRequestRole = "brand_manager"
)

// Valid indicates whether the value is a known member of the SeedUserRequestRole enum.
func (e SeedUserRequestRole) Valid() bool {
	switch e {
	case SeedUserRequestRoleAdmin:
		return true
	case SeedUserRequestRoleBrandManager:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// ResetTokenData defines model for ResetTokenData.
type ResetTokenData struct {
	Token string `json:"token"`
}

// ResetTokenResult defines model for ResetTokenResult.
type ResetTokenResult struct {
	Data ResetTokenData `json:"data"`
}

// SeedBrandData defines model for SeedBrandData.
type SeedBrandData struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// SeedBrandRequest defines model for SeedBrandRequest.
type SeedBrandRequest struct {
	// ManagerEmail If provided, assigns this user as manager (creates user if needed)
	ManagerEmail *openapi_types.Email `json:"managerEmail,omitempty"`
	Name         string               `json:"name"`
}

// SeedBrandResult defines model for SeedBrandResult.
type SeedBrandResult struct {
	Data SeedBrandData `json:"data"`
}

// SeedUserData defines model for SeedUserData.
type SeedUserData struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Role  SeedUserDataRole    `json:"role"`
}

// SeedUserDataRole defines model for SeedUserData.Role.
type SeedUserDataRole string

// SeedUserRequest defines model for SeedUserRequest.
type SeedUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Role     SeedUserRequestRole `json:"role"`
}

// SeedUserRequestRole defines model for SeedUserRequest.Role.
type SeedUserRequestRole string

// SeedUserResult defines model for SeedUserResult.
type SeedUserResult struct {
	Data SeedUserData `json:"data"`
}

// GetResetTokenParams defines parameters for GetResetToken.
type GetResetTokenParams struct {
	Email openapi_types.Email `form:"email" json:"email"`
}

// SeedBrandJSONRequestBody defines body for SeedBrand for application/json ContentType.
type SeedBrandJSONRequestBody = SeedBrandRequest

// SeedUserJSONRequestBody defines body for SeedUser for application/json ContentType.
type SeedUserJSONRequestBody = SeedUserRequest
