// Package testclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package testclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CleanupEntityRequestType.
const (
	Brand              CleanupEntityRequestType = "brand"
	Campaign           CleanupEntityRequestType = "campaign"
	Creator            CleanupEntityRequestType = "creator"
	CreatorApplication CleanupEntityRequestType = "creator_application"
	User               CleanupEntityRequestType = "user"
)

// Valid indicates whether the value is a known member of the CleanupEntityRequestType enum.
func (e CleanupEntityRequestType) Valid() bool {
	switch e {
	case Brand:
		return true
	case Campaign:
		return true
	case Creator:
		return true
	case CreatorApplication:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SeedUserDataRole.
const (
	SeedUserDataRoleAdmin        SeedUserDataRole = "admin"
	SeedUserDataRoleBrandManager SeedUserDataRole = "brand_manager"
)

// Valid indicates whether the value is a known member of the SeedUserDataRole enum.
func (e SeedUserDataRole) Valid() bool {
	switch e {
	case SeedUserDataRoleAdmin:
		return true
	case SeedUserDataRoleBrandManager:
		return true
	default:
		return false
	}
}

// Defines values for SeedUserRequestRole.
const (
	SeedUserRequestRoleAdmin        SeedUserRequestRole = "admin"
	SeedUserRequestRoleBrandManager SeedUserRequestRole = "brand_manager"
)

// Valid indicates whether the value is a known member of the SeedUserRequestRole enum.
func (e SeedUserRequestRole) Valid() bool {
	switch e {
	case SeedUserRequestRoleAdmin:
		return true
	case SeedUserRequestRoleBrandManager:
		return true
	default:
		return false
	}
}

// CleanupEntityRequest defines model for CleanupEntityRequest.
type CleanupEntityRequest struct {
	Id   string                   `json:"id"`
	Type CleanupEntityRequestType `json:"type"`
}

// CleanupEntityRequestType defines model for CleanupEntityRequest.Type.
type CleanupEntityRequestType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// ResetTokenData defines model for ResetTokenData.
type ResetTokenData struct {
	Token string `json:"token"`
}

// ResetTokenResult defines model for ResetTokenResult.
type ResetTokenResult struct {
	Data ResetTokenData `json:"data"`
}

// SeedUserData defines model for SeedUserData.
type SeedUserData struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Role  SeedUserDataRole    `json:"role"`
}

// SeedUserDataRole defines model for SeedUserData.Role.
type SeedUserDataRole string

// SeedUserRequest defines model for SeedUserRequest.
type SeedUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Role     SeedUserRequestRole `json:"role"`
}

// SeedUserRequestRole defines model for SeedUserRequest.Role.
type SeedUserRequestRole string

// SeedUserResult defines model for SeedUserResult.
type SeedUserResult struct {
	Data SeedUserData `json:"data"`
}

// SendTelegramMessageRequest defines model for SendTelegramMessageRequest.
type SendTelegramMessageRequest struct {
	// ChatId Synthetic chat id; echoed in the spy reply for assertions.
	ChatId    int64   `json:"chatId"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`

	// Text Message text the simulated user sends to the bot.
	Text string `json:"text"`

	// UserId Synthetic Telegram user id (defaults to chatId when omitted).
	UserId *int64 `json:"userId,omitempty"`

	// Username Optional Telegram @username (no leading @).
	Username *string `json:"username,omitempty"`
}

// SendTelegramMessageResult defines model for SendTelegramMessageResult.
type SendTelegramMessageResult struct {
	Replies []TelegramReply `json:"replies"`
}

// SignTMAInitDataData defines model for SignTMAInitDataData.
type SignTMAInitDataData struct {
	// InitData Signed query-string ready to be passed in
	// `Authorization: tma <init-data>`.
	InitData string `json:"initData"`
}

// SignTMAInitDataRequest defines model for SignTMAInitDataRequest.
type SignTMAInitDataRequest struct {
	// AuthDate Optional Unix timestamp (seconds). Defaults to "now" — used by
	// tests that want to exercise expired / future-dated init_data
	// paths.
	AuthDate *int64 `json:"authDate,omitempty"`

	// TelegramUserId Telegram user id to sign on behalf of.
	TelegramUserId int64 `json:"telegramUserId"`
}

// SignTMAInitDataResult defines model for SignTMAInitDataResult.
type SignTMAInitDataResult struct {
	Data SignTMAInitDataData `json:"data"`
}

// TelegramReply defines model for TelegramReply.
type TelegramReply struct {
	ChatId int64  `json:"chatId"`
	Text   string `json:"text"`
}

// TelegramSentData defines model for TelegramSentData.
type TelegramSentData struct {
	Messages []TelegramSentMessage `json:"messages"`
}

// TelegramSentMessage defines model for TelegramSentMessage.
type TelegramSentMessage struct {
	ChatId int64 `json:"chatId"`

	// Error Empty when the real upstream Telegram send succeeded (or when
	// running under the spy-only sender, which never errs); populated
	// with the upstream error string in TeeSender mode.
	Error  *string   `json:"error,omitempty"`
	SentAt time.Time `json:"sentAt"`
	Text   string    `json:"text"`

	// WebAppUrl URL embedded into the InlineKeyboardMarkup WebApp button when
	// the sender attached one. Null for plain-text messages.
	WebAppUrl *string `json:"webAppUrl,omitempty"`
}

// TelegramSentResult defines model for TelegramSentResult.
type TelegramSentResult struct {
	Data TelegramSentData `json:"data"`
}

// TelegramSpyFailNextRequest defines model for TelegramSpyFailNextRequest.
type TelegramSpyFailNextRequest struct {
	// ChatId Chat id whose next SendMessage call should fail.
	ChatId int64 `json:"chatId"`

	// Reason Optional override for the error string the spy returns. Defaults
	// to "Forbidden: bot was blocked by the user" so MapTelegramErrorToReason
	// classifies it as bot_blocked.
	Reason *string `json:"reason,omitempty"`
}

// TelegramSpyFakeChatRequest defines model for TelegramSpyFakeChatRequest.
type TelegramSpyFakeChatRequest struct {
	// ChatId Chat id to register as test-synthetic.
	ChatId int64 `json:"chatId"`
}

// GetResetTokenParams defines parameters for GetResetToken.
type GetResetTokenParams struct {
	Email openapi_types.Email `form:"email" json:"email"`
}

// GetTelegramSentParams defines parameters for GetTelegramSent.
type GetTelegramSentParams struct {
	// ChatId Telegram chat id (== TG user id for private DMs).
	ChatId int64 `form:"chatId" json:"chatId"`

	// Since Only records sent at or after this timestamp.
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`
}

// CleanupEntityJSONRequestBody defines body for CleanupEntity for application/json ContentType.
type CleanupEntityJSONRequestBody = CleanupEntityRequest

// SeedUserJSONRequestBody defines body for SeedUser for application/json ContentType.
type SeedUserJSONRequestBody = SeedUserRequest

// SendTelegramMessageJSONRequestBody defines body for SendTelegramMessage for application/json ContentType.
type SendTelegramMessageJSONRequestBody = SendTelegramMessageRequest

// TelegramSpyFailNextJSONRequestBody defines body for TelegramSpyFailNext for application/json ContentType.
type TelegramSpyFailNextJSONRequestBody = TelegramSpyFailNextRequest

// TelegramSpyFakeChatJSONRequestBody defines body for TelegramSpyFakeChat for application/json ContentType.
type TelegramSpyFakeChatJSONRequestBody = TelegramSpyFakeChatRequest

// SignTMAInitDataJSONRequestBody defines body for SignTMAInitData for application/json ContentType.
type SignTMAInitDataJSONRequestBody = SignTMAInitDataRequest
